interface=wlan0
driver=nl80211
ctrl_interface=/run/open-radio-hostapd
ctrl_interface_group=network
ssid=codex_he20_wpa
country_code=DE
hw_mode=g
channel=11
ieee80211n=1
ht_capab=[SHORT-GI-20]
ieee80211ax=1
wmm_enabled=1
auth_algs=1
wpa=2
wpa_passphrase=open-radio-perf-2026
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
