[package]
name = "open-esp-radio-wifi-softmac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Executor-independent Wi-Fi SoftMAC service contract"

[dependencies]
open-esp-radio-ieee80211 = { path = "../ieee80211" }
zeroize = { version = "1.9.0", default-features = false, features = ["derive"] }

[lints]
workspace = true
