//! What the Claude Code hooks read from the tools instead of restating it.
//!
//! `.claude/hooks/pre_tool_use.py` refuses a foreground build, test, check
//! or HIL run. Which commands those are is exported here into
//! [`PATH`] (`cargo xtask hooks` writes it; a test holds the committed file
//! to [`document`]), so the hook carries no list of its own. The session
//! start hook reads CI's state through `oer-xtask ci-status`
//! ([`crate::ci_status`]).

use std::path::Path;

use serde::Serialize;

use crate::Result;

/// The generated file, relative to the root.
pub const PATH: &str = ".claude/hooks/heavy-commands.json";

/// Cargo subcommands (and their short aliases) that build or run code.
pub const CARGO: &[&str] = &[
    "build", "b", "test", "t", "clippy", "check", "c", "doc", "d", "nextest", "bench", "miri",
];

/// `cargo xtask` subcommands that build, check or run long work; a
/// subcommand matches when it starts with one of them.
pub const XTASK: &[&str] = &[
    "check",
    "push",
    "build",
    "doc",
    "compare",
    "evidence",
    "vendor-scenario",
    "register-inventory",
];

/// Flags with which a heavy xtask subcommand only lists.
pub const XTASK_LISTING: &[&str] = &["--list"];

/// `cargo hil` subcommands that build images, flash or run on the stand.
pub const HIL: &[&str] = &["run", "run-all", "wait", "lease", "flash"];

/// `cargo hil` subcommand pairs that build.
pub const HIL_PAIRS: &[[&str; 2]] = &[["image", "build"]];

/// Flags with which a heavy `cargo hil` subcommand (other than `wait`) only
/// queues or validates.
pub const HIL_DEFERRED: &[&str] = &["--enqueue", "--validate-only"];

#[derive(Serialize)]
struct Document {
    #[serde(rename = "//")]
    note: &'static str,
    cargo: &'static [&'static str],
    xtask: &'static [&'static str],
    xtask_listing: &'static [&'static str],
    hil: &'static [&'static str],
    hil_pairs: &'static [[&'static str; 2]],
    hil_deferred: &'static [&'static str],
}

/// The generated file's text.
pub fn document() -> String {
    let document = Document {
        note: "Generated by `cargo xtask hooks` from oer_xtask::hooks; do not edit.",
        cargo: CARGO,
        xtask: XTASK,
        xtask_listing: XTASK_LISTING,
        hil: HIL,
        hil_pairs: HIL_PAIRS,
        hil_deferred: HIL_DEFERRED,
    };
    serde_json::to_string_pretty(&document).expect("the document serializes") + "\n"
}

/// Write [`PATH`] below `root`, or with `check` fail when it differs.
pub fn run(root: &Path, check: bool) -> Result<()> {
    let path = root.join(PATH);
    let current = std::fs::read_to_string(&path).unwrap_or_default();
    if current == document() {
        println!("{PATH} is current");
        return Ok(());
    }
    if check {
        return Err(format!("{PATH} is stale; run `cargo xtask hooks`").into());
    }
    oer_durable::atomic_write(&path, document().as_bytes())?;
    println!("wrote {PATH}");
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn the_committed_hook_list_is_generated() {
        let root = oer_process::built_root();
        let committed = std::fs::read_to_string(root.join(super::PATH)).unwrap();
        assert_eq!(
            committed,
            super::document(),
            "run `cargo xtask hooks` to regenerate {}",
            super::PATH
        );
    }
}
