//! What the Claude Code hooks read from the tools instead of restating it.
//!
//! `.claude/hooks/pre_tool_use.py` refuses a foreground build, test, check
//! or HIL run. Which commands those are is exported here into
//! [`PATH`] (`cargo xtask hooks` writes it; a test holds the committed file
//! to [`document`]), so the hook carries no list of its own. The session
//! start hook reads CI's state through `oer-xtask ci-status`
//! ([`crate::ci_status`]).

use std::path::Path;

use serde::Serialize;

use crate::Result;

/// The generated file, relative to the root.
pub const PATH: &str = ".claude/hooks/heavy-commands.json";

/// Cargo subcommands (and their short aliases) that build or run code.
pub const CARGO: &[&str] = &[
    "build", "b", "test", "t", "clippy", "check", "c", "doc", "d", "nextest", "bench", "miri",
];

/// `cargo xtask` subcommands that build, check or run long work; a
/// subcommand matches when it starts with one of them.
pub const XTASK: &[&str] = &["check", "push", "doc"];

/// Flags with which a heavy xtask subcommand only lists.
pub const XTASK_LISTING: &[&str] = &["--list"];

/// The heavy commands of one cargo alias tool (`cargo <name> ...`).
#[derive(Serialize)]
pub struct Tool {
    /// The alias, as `cargo <name>`.
    pub name: &'static str,
    /// Subcommands that build, flash, analyze or wait on the stand.
    pub heavy: &'static [&'static str],
    /// Subcommand pairs that do so (`cargo <name> <a> <b>`).
    pub pairs: &'static [[&'static str; 2]],
    /// Flags with which a heavy subcommand (other than `wait`) only queues
    /// or validates.
    pub deferred: &'static [&'static str],
}

/// The cargo alias tools other than xtask whose commands run long.
pub const TOOLS: &[Tool] = &[
    Tool {
        name: "hil",
        heavy: &["run", "run-all", "wait", "bisect", "ab"],
        pairs: &[
            ["image", "build"],
            ["images", "check"],
            ["images", "compare"],
            ["firmware", "build"],
        ],
        deferred: &["--enqueue", "--validate-only"],
    },
    Tool {
        name: "fw",
        heavy: &["build", "flash", "monitor", "compare"],
        pairs: &[],
        deferred: &[],
    },
    Tool {
        name: "stand",
        heavy: &["wait", "lease", "install", "fixture"],
        pairs: &[["board", "soak"]],
        deferred: &[],
    },
    Tool {
        name: "verification",
        heavy: &[
            "fetch",
            "diff",
            "provenance",
            "scenario",
            "evidence",
            "probes",
            "check",
        ],
        pairs: &[],
        deferred: &[],
    },
    Tool {
        name: "registers",
        heavy: &["inventory"],
        pairs: &[],
        deferred: &[],
    },
];

#[derive(Serialize)]
struct Document {
    #[serde(rename = "//")]
    note: &'static str,
    cargo: &'static [&'static str],
    xtask: &'static [&'static str],
    xtask_listing: &'static [&'static str],
    tools: &'static [Tool],
}

/// The generated file's text.
pub fn document() -> String {
    let document = Document {
        note: "Generated by `cargo xtask hooks` from oer_xtask::hooks; do not edit.",
        cargo: CARGO,
        xtask: XTASK,
        xtask_listing: XTASK_LISTING,
        tools: TOOLS,
    };
    serde_json::to_string_pretty(&document).expect("the document serializes") + "\n"
}

/// Write [`PATH`] below `root`, or with `check` fail when it differs.
pub fn run(root: &Path, check: bool) -> Result<()> {
    let path = root.join(PATH);
    let current = std::fs::read_to_string(&path).unwrap_or_default();
    if current == document() {
        println!("{PATH} is current");
        return Ok(());
    }
    if check {
        return Err(format!("{PATH} is stale; run `cargo xtask hooks`").into());
    }
    oer_durable::atomic_write(&path, document().as_bytes())?;
    println!("wrote {PATH}");
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn the_committed_hook_list_is_generated() {
        let root = oer_process::built_root();
        let committed = std::fs::read_to_string(root.join(super::PATH)).unwrap();
        assert_eq!(
            committed,
            super::document(),
            "run `cargo xtask hooks` to regenerate {}",
            super::PATH
        );
    }
}
