//! Value-only hardware contracts exposed above the PAC boundary.
//!
//! The defining register domains remain in the restricted PAC, while this
//! module is the only public path used by HAL consumers.  No peripheral owner,
//! register block, raw accessor, or generic MMIO capability is re-exported.

pub use oer_esp32s31_pac::{
    BluetoothControllerSramAddress, BluetoothControllerSramAddressError,
    BluetoothMemoryListSelector, BluetoothPhyEnvironmentAddress,
    BluetoothPhyEnvironmentAddressError, BluetoothPhyRegisterInitInputs, CfrValue,
    CoexTimerClientValue, CoexTimerPtiValue, CoexTimerRegister, ExtraSoftApRxBlockAckEntrySnapshot,
    ForcedRxGain, Ieee802154ObservedEventState, Ieee802154OperationRxAbortEnableObservation,
    Ieee802154RxAbortReason, Ieee802154RxAbortReasonObservation, Ieee802154TimingPrerequisite,
    Ieee802154TimingReady, Ieee802154ValidationEdDurationState,
    Ieee802154ValidationEventEnableState, MAC_TX_POWER_RATE_COUNT, MacApReceivePolicySnapshot,
    MacAssociationId, MacCcmpKeyIdentity, MacCoexPrioritySnapshot,
    MacExtraSoftApRxBlockAckEntryIndex, MacHe20PeerConfig, MacHe20PeerError,
    MacHeBeamformingReportProfile, MacHeBeamformingReportProfileError, MacHeBssColor,
    MacHeDefaultPacketExtensionDuration, MacHeErSuAckRateProfile, MacHeFecCoding,
    MacHeGuardIntervalAndLtf, MacHeMcs, MacHePacketPaddingDuration, MacHeRate,
    MacHeTbLinkReservation, MacHeTbProgramError, MacHeTbTidLimit, MacHeTid,
    MacHeTriggerRxDiagnostics, MacHeTriggerTxQueueSnapshot, MacHeTxFormat, MacHeTxParameters,
    MacHeTxProgram, MacHtAmpduCompletionObservation, MacHtChannelWidth, MacHtGuardInterval,
    MacHtMcs, MacHtProtectionSpacing, MacHtRate, MacHtTxFormat, MacHtTxParameters, MacHtTxProgram,
    MacInterface, MacInterruptEnableState, MacInterruptEvents, MacInterruptMask,
    MacInterruptObservation, MacInterruptSnapshot, MacItwtClearIndex, MacKeyEntryIndex,
    MacKeyInstallOutcome, MacLegacyRate, MacLegacyTxParameters, MacLegacyTxProgram,
    MacMinimumMpduStartSpacing, MacOrdinaryTxQueueSnapshot, MacPartialRuPowerSelector,
    MacPowerInterruptObservation, MacPowerInterruptSnapshot, MacPowerWakeCause, MacPti,
    MacRoleReceivePolicy, MacRxBlockAckEntryIndex, MacRxBlockAckStartingSequence, MacRxBlockAckTid,
    MacRxBlockAckWindow, MacRxDecodeErrorStatistics, MacRxDecodeErrorStatisticsDelta,
    MacRxDmaSnapshot, MacRxHangStatistics, MacRxHangStatisticsDelta, MacRxPrimaryStatistics,
    MacRxPrimaryStatisticsDelta, MacRxStatisticsSnapshot, MacStaApReceivePlan, MacStaPolicyMode,
    MacStaReceivePolicySnapshot, MacTsfTimerIndex, MacTxCompletionObservation, MacTxDetachOutcome,
    MacTxDetachReason, MacTxPowerPair, MacTxPowerTable, MacTxPtiCount, MacTxPtiProgram,
    MacTxQueueDetached, MacTxQueueIndex, MacTxStatisticsSnapshot, PbusMemoryGroupBoundary,
    PhyAdcRate, PhyForcedPowerIndex, PhyFtmEnableVendorArgument, PhyGainMemoryEntry,
    PhyMemoryError, RxBlockAckEntrySnapshot, RxDcoControlPrepareError, RxDcoControlRestoreError,
    StaBeaconMissLimit, StaBeaconMissTimeoutRaw, StaModemSleepLimit, StaModemWakeConfig,
    StaModemWakePrepareError, StaModemWakeRestore, StaModemWakeRestoreError,
    StaModemWakeRestoreFailure, StaTbttAutoPeriod, StaTbttWakePrepareError, StaTbttWakeRestore,
    StaTbttWakeRestoreError, StaTbttWakeRestoreFailure, StaWakeProtectEarlyTimeRaw,
    TxBlockAckPayload, TxIqToneControlPrepareError, TxIqToneControlRestoreError,
};
