//! ESP32-S31 radio clock, power, reset and recovered clock-gate registers.
//!
//! @generated by `tools/generate-esp32s31-radio-pac.py` from
//! `svd/esp32s31-radio.svd`; edit the SVD, not this file.

use crate::Register32;

/// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Names and offsets come from
/// the pinned ESP32-S31 register structure; writable use is independently exercised by its LL
/// setters and the clock oracle.
pub mod modem_syscon {
    use crate::{Register32, RegisterAccess};

    /// Peripheral base address. SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
    /// Names and offsets come from the pinned ESP32-S31 register structure; writable use is
    /// independently exercised by its LL setters and the clock oracle.
    pub const BASE: usize = 0x20109c00;

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Modem test and force
    /// configuration.
    pub const TEST_CONF: Register32 =
        Register32::described(0x20109c00, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`TEST_CONF`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Modem test and force configuration.
    pub mod test_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const CLK_EN: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const MODEM_ANT_FORCE_SEL_BT: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const MODEM_ANT_FORCE_SEL_WIFI: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const FPGA_DEBUG_CLKSWITCH: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const FPGA_DEBUG_CLK80: Field32 = Field32::new(4, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const FPGA_DEBUG_CLK40: Field32 = Field32::new(5, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const FPGA_DEBUG_CLK20: Field32 = Field32::new(6, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const FPGA_DEBUG_CLK10: Field32 = Field32::new(7, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const MODEM_MEM_MODE_FORCE: Field32 = Field32::new(8, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem test and force configuration.
        pub const MODEM_DIS_WIFI6_FORCE: Field32 = Field32::new(9, 1);
    }

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Modem peripheral clock
    /// configuration.
    pub const CLK_CONF: Register32 =
        Register32::described(0x20109c04, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`CLK_CONF`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Modem peripheral clock configuration.
    pub mod clk_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const PWDET_SAR_CLOCK_ENA: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const PWDET_CLK_DIV_NUM: Field32 = Field32::new(1, 8);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_TX_DAC_INV_ENA: Field32 = Field32::new(9, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_RX_ADC_INV_ENA: Field32 = Field32::new(10, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_PWDET_ADC_INV_ENA: Field32 = Field32::new(11, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_I2C_MST_SEL_160M: Field32 = Field32::new(12, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_DATA_DUMP_MUX: Field32 = Field32::new(21, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_ETM_EN: Field32 = Field32::new(22, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_ZB_APB_EN: Field32 = Field32::new(23, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_ZBMAC_EN: Field32 = Field32::new(24, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_MODEM_SEC_ECB_EN: Field32 = Field32::new(25, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_MODEM_SEC_CCM_EN: Field32 = Field32::new(26, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_MODEM_SEC_BAH_EN: Field32 = Field32::new(27, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_MODEM_SEC_APB_EN: Field32 = Field32::new(28, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_MODEM_SEC_EN: Field32 = Field32::new(29, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_BLE_TIMER_EN: Field32 = Field32::new(30, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem peripheral clock configuration.
        pub const CLK_DATA_DUMP_EN: Field32 = Field32::new(31, 1);
    }

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Force-on bits for modem
    /// domain clocks.
    pub const CLK_CONF_FORCE_ON: Register32 =
        Register32::described(0x20109c08, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`CLK_CONF_FORCE_ON`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Force-on bits for modem domain clocks.
    pub mod clk_conf_force_on {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_WIFIBB_FO: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_WIFIMAC_FO: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_WIFI_APB_FO: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_FE_FO: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_FE_APB_FO: Field32 = Field32::new(4, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_BTBB_FO: Field32 = Field32::new(5, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_BTMAC_FO: Field32 = Field32::new(6, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_BT_APB_FO: Field32 = Field32::new(7, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_ZBMAC_FO: Field32 = Field32::new(8, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_ZBMAC_APB_FO: Field32 = Field32::new(9, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_ETM_FO: Field32 = Field32::new(28, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_MODEM_SEC_FO: Field32 = Field32::new(29, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_BLE_TIMER_FO: Field32 = Field32::new(30, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on bits for modem domain clocks.
        pub const CLK_DATA_DUMP_FO: Field32 = Field32::new(31, 1);
    }

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Four-bit power-state
    /// clock maps.
    pub const CLK_CONF_POWER_ST: Register32 =
        Register32::described(0x20109c0c, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`CLK_CONF_POWER_ST`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Four-bit power-state clock maps.
    pub mod clk_conf_power_st {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit power-state clock maps.
        pub const CLK_ZB_ST_MAP: Field32 = Field32::new(8, 4);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit power-state clock maps.
        pub const CLK_FE_ST_MAP: Field32 = Field32::new(12, 4);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit power-state clock maps.
        pub const CLK_BT_ST_MAP: Field32 = Field32::new(16, 4);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit power-state clock maps.
        pub const CLK_WIFI_ST_MAP: Field32 = Field32::new(20, 4);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit power-state clock maps.
        pub const CLK_MODEM_PERI_ST_MAP: Field32 = Field32::new(24, 4);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit power-state clock maps.
        pub const CLK_MODEM_APB_ST_MAP: Field32 = Field32::new(28, 4);
    }

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Modem subsystem reset
    /// lines.
    pub const MODEM_RST_CONF: Register32 =
        Register32::described(0x20109c10, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`MODEM_RST_CONF`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Modem subsystem reset lines.
    pub mod modem_rst_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_WIFIBB: Field32 = Field32::new(8, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_WIFIMAC: Field32 = Field32::new(9, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_FE_PWDET_ADC: Field32 = Field32::new(10, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_FE_DAC: Field32 = Field32::new(11, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_FE_ADC: Field32 = Field32::new(12, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_FE_AHB: Field32 = Field32::new(13, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_FE: Field32 = Field32::new(14, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_BTMAC_APB: Field32 = Field32::new(15, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_BTMAC: Field32 = Field32::new(16, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_BTBB_APB: Field32 = Field32::new(17, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_BTBB: Field32 = Field32::new(18, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_COEX_BTMAC_APB: Field32 = Field32::new(19, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_COEX_BTMAC: Field32 = Field32::new(20, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_ETM: Field32 = Field32::new(22, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_ZBMAC_APB: Field32 = Field32::new(23, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_ZBMAC: Field32 = Field32::new(24, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_MODEM_ECB: Field32 = Field32::new(25, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_MODEM_CCM: Field32 = Field32::new(26, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_MODEM_BAH: Field32 = Field32::new(27, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_MODEM_SEC: Field32 = Field32::new(29, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_BLE_TIMER: Field32 = Field32::new(30, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem subsystem reset lines.
        pub const RST_DATA_DUMP: Field32 = Field32::new(31, 1);
    }

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Wi-Fi, frontend and
    /// Bluetooth functional clock gates.
    pub const CLK_CONF1: Register32 =
        Register32::described(0x20109c14, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`CLK_CONF1`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Wi-Fi, frontend and Bluetooth functional clock gates.
    pub mod clk_conf1 {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_22M_EN: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_40M_EN: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_44M_EN: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_80M_EN: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_40X_EN: Field32 = Field32::new(4, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_80X_EN: Field32 = Field32::new(5, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_40X1_EN: Field32 = Field32::new(6, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_80X1_EN: Field32 = Field32::new(7, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIBB_160X1_EN: Field32 = Field32::new(8, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFIMAC_EN: Field32 = Field32::new(9, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_WIFI_APB_EN: Field32 = Field32::new(10, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_20M_EN: Field32 = Field32::new(11, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_40M_EN: Field32 = Field32::new(12, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_80M_EN: Field32 = Field32::new(13, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_160M_EN: Field32 = Field32::new(14, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_APB_EN: Field32 = Field32::new(15, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_BT_APB_EN: Field32 = Field32::new(16, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_BTBB_EN: Field32 = Field32::new(17, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_BTMAC_EN: Field32 = Field32::new(18, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_PWDET_ADC_EN: Field32 = Field32::new(19, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_ADC_EN: Field32 = Field32::new(20, 1);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi, frontend and Bluetooth functional clock gates.
        pub const CLK_FE_DAC_EN: Field32 = Field32::new(21, 1);
    }

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[register-exact-fields-unknown]. OPAQUE Wi-Fi
    /// baseband configuration word.
    pub const WIFI_BB_CFG: Register32 =
        Register32::described(0x20109c18, RegisterAccess::ReadWrite, None);

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[register-exact-fields-unknown]. OPAQUE radio
    /// frontend configuration word.
    pub const FE_CFG: Register32 =
        Register32::described(0x20109c1c, RegisterAccess::ReadWrite, None);

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[register-exact-fields-unknown]. OPAQUE modem
    /// memory RF1 configuration.
    pub const MEM_RF1_CONF: Register32 =
        Register32::described(0x20109c20, RegisterAccess::ReadWrite, None);

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[register-exact-fields-unknown]. OPAQUE modem
    /// memory RF2 configuration.
    pub const MEM_RF2_CONF: Register32 =
        Register32::described(0x20109c24, RegisterAccess::ReadWrite, None);

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Bluetooth MAC low-rate
    /// clock selection.
    pub const BTMAC_CLK_CFG: Register32 =
        Register32::described(0x20109c28, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`BTMAC_CLK_CFG`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Bluetooth MAC low-rate clock selection.
    pub mod btmac_clk_cfg {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Bluetooth MAC low-rate clock selection.
        pub const CLK_BTMAC_LOW_RATE: Field32 = Field32::new(0, 1);
    }

    /// SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Modem RF memory mode
    /// selection.
    pub const MEM_MODE_CONF: Register32 =
        Register32::described(0x20109c2c, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`MEM_MODE_CONF`]. SOURCE[S31_MODEM_SYSCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Modem RF memory mode selection.
    pub mod mem_mode_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem RF memory mode selection.
        pub const MODEM_RF1_MEM_SEL: Field32 = Field32::new(0, 4);
        /// Field layout from SOURCE[S31_MODEM_SYSCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem RF memory mode selection.
        pub const MODEM_RF2_MEM_SEL: Field32 = Field32::new(4, 4);
    }
}

/// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Names and offsets come from
/// the pinned ESP32-S31 low-power modem structure; writable use is independently exercised by
/// its LL setters and the clock oracle.
pub mod modem_lpcon {
    use crate::{Register32, RegisterAccess};

    /// Peripheral base address. SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
    /// Names and offsets come from the pinned ESP32-S31 low-power modem structure; writable use
    /// is independently exercised by its LL setters and the clock oracle.
    pub const BASE: usize = 0x2010f000;

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Low-power modem test clock
    /// control.
    pub const TEST_CONF: Register32 =
        Register32::described(0x2010f000, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`TEST_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Low-power modem test clock control.
    pub mod test_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Low-power modem test clock control.
        pub const CLK_EN: Field32 = Field32::new(0, 1);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Low-power timer clock
    /// source and divider.
    pub const LP_TIMER_CONF: Register32 =
        Register32::described(0x2010f004, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`LP_TIMER_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Low-power timer clock source and divider.
    pub mod lp_timer_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Low-power timer clock source and divider.
        pub const CLK_LP_TIMER_SEL_OSC_SLOW: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Low-power timer clock source and divider.
        pub const CLK_LP_TIMER_SEL_OSC_FAST: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Low-power timer clock source and divider.
        pub const CLK_LP_TIMER_SEL_XTAL: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Low-power timer clock source and divider.
        pub const CLK_LP_TIMER_SEL_XTAL32K: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Low-power timer clock source and divider.
        pub const CLK_LP_TIMER_DIV_NUM: Field32 = Field32::new(4, 12);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Coexistence low-power
    /// clock source and divider.
    pub const COEX_LP_CLK_CONF: Register32 =
        Register32::described(0x2010f008, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`COEX_LP_CLK_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Coexistence low-power clock source and divider.
    pub mod coex_lp_clk_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Coexistence low-power clock source and divider.
        pub const CLK_COEX_LP_SEL_OSC_SLOW: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Coexistence low-power clock source and divider.
        pub const CLK_COEX_LP_SEL_OSC_FAST: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Coexistence low-power clock source and divider.
        pub const CLK_COEX_LP_SEL_XTAL: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Coexistence low-power clock source and divider.
        pub const CLK_COEX_LP_SEL_XTAL32K: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Coexistence low-power clock source and divider.
        pub const CLK_COEX_LP_DIV_NUM: Field32 = Field32::new(4, 12);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Wi-Fi power low-power
    /// clock source and divider.
    pub const WIFI_LP_CLK_CONF: Register32 =
        Register32::described(0x2010f00c, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`WIFI_LP_CLK_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Wi-Fi power low-power clock source and divider.
    pub mod wifi_lp_clk_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi power low-power clock source and divider.
        pub const CLK_WIFIPWR_LP_SEL_OSC_SLOW: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi power low-power clock source and divider.
        pub const CLK_WIFIPWR_LP_SEL_OSC_FAST: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi power low-power clock source and divider.
        pub const CLK_WIFIPWR_LP_SEL_XTAL: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi power low-power clock source and divider.
        pub const CLK_WIFIPWR_LP_SEL_XTAL32K: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Wi-Fi power low-power clock source and divider.
        pub const CLK_WIFIPWR_LP_DIV_NUM: Field32 = Field32::new(4, 12);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Always-on modem and
    /// power-clock source forcing.
    pub const MODEM_SRC_CLK_CONF: Register32 =
        Register32::described(0x2010f010, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`MODEM_SRC_CLK_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Always-on modem and power-clock source forcing.
    pub mod modem_src_clk_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Always-on modem and power-clock source forcing.
        pub const CLK_MODEM_AON_FORCE: Field32 = Field32::new(0, 2);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Always-on modem and power-clock source forcing.
        pub const MODEM_PWR_CLK_SRC_FO: Field32 = Field32::new(2, 1);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Modem 32 kHz source
    /// selector.
    pub const MODEM_32K_CLK_CONF: Register32 =
        Register32::described(0x2010f014, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`MODEM_32K_CLK_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Modem 32 kHz source selector.
    pub mod modem_32k_clk_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem 32 kHz source selector.
        pub const CLK_MODEM_32K_SEL: Field32 = Field32::new(0, 2);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Shared low-power modem
    /// clock gates.
    pub const CLK_CONF: Register32 =
        Register32::described(0x2010f018, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`CLK_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Shared low-power modem clock gates.
    pub mod clk_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem clock gates.
        pub const CLK_WIFIPWR_EN: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem clock gates.
        pub const CLK_COEX_EN: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem clock gates.
        pub const CLK_I2C_MST_EN: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem clock gates.
        pub const CLK_LP_TIMER_EN: Field32 = Field32::new(3, 1);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Force-on controls for
    /// low-power modem clocks and frontend memory.
    pub const CLK_CONF_FORCE_ON: Register32 =
        Register32::described(0x2010f01c, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`CLK_CONF_FORCE_ON`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Force-on controls for low-power modem clocks and frontend
    /// memory.
    pub mod clk_conf_force_on {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on controls for low-power modem clocks and frontend memory.
        pub const CLK_WIFIPWR_FO: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on controls for low-power modem clocks and frontend memory.
        pub const CLK_COEX_FO: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on controls for low-power modem clocks and frontend memory.
        pub const CLK_I2C_MST_FO: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on controls for low-power modem clocks and frontend memory.
        pub const CLK_LP_TIMER_FO: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Force-on controls for low-power modem clocks and frontend memory.
        pub const CLK_FE_MEM_FO: Field32 = Field32::new(4, 1);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Four-bit shared-domain
    /// power-state clock maps.
    pub const CLK_CONF_POWER_ST: Register32 =
        Register32::described(0x2010f020, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`CLK_CONF_POWER_ST`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Four-bit shared-domain power-state clock maps.
    pub mod clk_conf_power_st {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit shared-domain power-state clock maps.
        pub const CLK_WIFIPWR_ST_MAP: Field32 = Field32::new(16, 4);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit shared-domain power-state clock maps.
        pub const CLK_COEX_ST_MAP: Field32 = Field32::new(20, 4);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit shared-domain power-state clock maps.
        pub const CLK_I2C_MST_ST_MAP: Field32 = Field32::new(24, 4);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Four-bit shared-domain power-state clock maps.
        pub const CLK_LP_APB_ST_MAP: Field32 = Field32::new(28, 4);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Shared low-power modem
    /// reset lines.
    pub const RST_CONF: Register32 =
        Register32::described(0x2010f024, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`RST_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Shared low-power modem reset lines.
    pub mod rst_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem reset lines.
        pub const RST_WIFIPWR: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem reset lines.
        pub const RST_COEX: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem reset lines.
        pub const RST_I2C_MST: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem reset lines.
        pub const RST_LP_TIMER: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Shared low-power modem reset lines.
        pub const RST_DCMEM: Field32 = Field32::new(4, 1);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Modem power tick target.
    pub const TICK_CONF: Register32 =
        Register32::described(0x2010f028, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`TICK_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Modem power tick target.
    pub mod tick_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Modem power tick target.
        pub const MODEM_PWR_TICK_TARGET: Field32 = Field32::new(0, 6);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode and force fields for
    /// seven low-power modem memories.
    pub const MEM_CONF: Register32 =
        Register32::described(0x2010f02c, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`MEM_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Mode and force fields for seven low-power modem memories.
    pub mod mem_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const DC_MEM_MODE: Field32 = Field32::new(0, 3);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const DC_MEM_FORCE: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const AGC_MEM_MODE: Field32 = Field32::new(4, 3);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const AGC_MEM_FORCE: Field32 = Field32::new(7, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const PBUS_MEM_MODE: Field32 = Field32::new(8, 3);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const PBUS_MEM_FORCE: Field32 = Field32::new(11, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const BC_MEM_MODE: Field32 = Field32::new(12, 3);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const BC_MEM_FORCE: Field32 = Field32::new(15, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const I2C_MST_MEM_MODE: Field32 = Field32::new(16, 3);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const I2C_MST_MEM_FORCE: Field32 = Field32::new(19, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const CHAN_FREQ_MEM_MODE: Field32 = Field32::new(20, 3);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const CHAN_FREQ_MEM_FORCE: Field32 = Field32::new(23, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const CFR_MEM_MODE: Field32 = Field32::new(24, 3);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Mode
        /// and force fields for seven low-power modem memories.
        pub const CFR_MEM_FORCE: Field32 = Field32::new(27, 1);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[register-exact-fields-unknown]. OPAQUE
    /// low-power memory RF1 control.
    pub const MEM_RF1_AUX_CTRL: Register32 =
        Register32::described(0x2010f030, RegisterAccess::ReadWrite, None);

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[register-exact-fields-unknown]. OPAQUE
    /// low-power memory RF2 control.
    pub const MEM_RF2_AUX_CTRL: Register32 =
        Register32::described(0x2010f034, RegisterAccess::ReadWrite, None);

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. APB selection for modem
    /// memories and power-memory base.
    pub const APB_MEM_SEL: Register32 =
        Register32::described(0x2010f038, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`APB_MEM_SEL`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. APB selection for modem memories and power-memory base.
    pub mod apb_mem_sel {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. APB
        /// selection for modem memories and power-memory base.
        pub const CHAN_FREQ_MEM_EN: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. APB
        /// selection for modem memories and power-memory base.
        pub const PBUS_MEM_EN: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. APB
        /// selection for modem memories and power-memory base.
        pub const AGC_MEM_EN: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. APB
        /// selection for modem memories and power-memory base.
        pub const CFR_MEM_EN: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. APB
        /// selection for modem memories and power-memory base.
        pub const PWR_MEM_BASE: Field32 = Field32::new(4, 16);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Interrupt sources allowed
    /// to wake the modem domain.
    pub const MODEM_INTR_WAKEUP_CONF: Register32 =
        Register32::described(0x2010f04c, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`MODEM_INTR_WAKEUP_CONF`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Interrupt sources allowed to wake the modem domain.
    pub mod modem_intr_wakeup_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const WIFI_MAC_INTR_WAKEUP_EN: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const WIFI_MAC_NMI_WAKEUP_EN: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const WIFI_PWR_INTR_WAKEUP_EN: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const WIFI_BB_INTR_WAKEUP_EN: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const BT_MAC_INTR_WAKEUP_EN: Field32 = Field32::new(4, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const BT_BB_INTR_WAKEUP_EN: Field32 = Field32::new(5, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const BT_BB_NMI_WAKEUP_EN: Field32 = Field32::new(6, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const LP_TIMER_INTR_WAKEUP_EN: Field32 = Field32::new(7, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const COEX_INTR_WAKEUP_EN: Field32 = Field32::new(8, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const BLE_TIMER_INTR_WAKEUP_EN: Field32 = Field32::new(9, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const BLE_SEC_INTR_WAKEUP_EN: Field32 = Field32::new(10, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const I2C_MST_INTR_WAKEUP_EN: Field32 = Field32::new(11, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const ZB_MAC_INTR_WAKEUP_EN: Field32 = Field32::new(12, 1);
        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Interrupt sources allowed to wake the modem domain.
        pub const BT_MAC_INT1_WAKEUP_EN: Field32 = Field32::new(13, 1);
    }

    /// SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout]. Power-memory mode
    /// selection.
    pub const MEM_CONF2: Register32 =
        Register32::described(0x2010f054, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`MEM_CONF2`]. SOURCE[S31_MODEM_LPCON_STRUCT];
    /// CONFIDENCE[exact-s31-layout]. Power-memory mode selection.
    pub mod mem_conf2 {
        use crate::Field32;

        /// Field layout from SOURCE[S31_MODEM_LPCON_STRUCT]; CONFIDENCE[exact-s31-layout].
        /// Power-memory mode selection.
        pub const PWR_MEM_MODE_SEL: Field32 = Field32::new(0, 4);
    }
}

/// SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. ESP32-S31 high-performance clock/reset
/// fields used by the modem sequence.
pub mod hp_sys_clkrst {
    use crate::{Register32, RegisterAccess};

    /// Peripheral base address. SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. ESP32-S31
    /// high-performance clock/reset fields used by the modem sequence.
    pub const BASE: usize = 0x20587000;

    /// SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem register-bus clock enable.
    pub const MODEM_CTRL0: Register32 =
        Register32::described(0x20587040, RegisterAccess::ReadWrite, Some(0x00000001));

    /// Recovered fields of [`MODEM_CTRL0`]. SOURCE[S31_ESP_PACS_SVD];
    /// CONFIDENCE[exact-s31-svd]. Modem register-bus clock enable.
    pub mod modem_ctrl0 {
        use crate::Field32;

        /// Field layout from SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem
        /// register-bus clock enable.
        pub const REG_MODEM_CLK_EN: Field32 = Field32::new(0, 1);
    }

    /// SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem APB, reset and source-clock
    /// configuration.
    pub const MODEM_CONF: Register32 =
        Register32::described(0x205871e0, RegisterAccess::ReadWrite, Some(0x00000025));

    /// Recovered fields of [`MODEM_CONF`]. SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd].
    /// Modem APB, reset and source-clock configuration.
    pub mod modem_conf {
        use crate::Field32;

        /// Field layout from SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem APB,
        /// reset and source-clock configuration.
        pub const MODEM_APB_CLK_EN: Field32 = Field32::new(0, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem APB,
        /// reset and source-clock configuration.
        pub const MODEM_RST_EN: Field32 = Field32::new(1, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem APB,
        /// reset and source-clock configuration.
        pub const MODEM_CLK_EN: Field32 = Field32::new(2, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem APB,
        /// reset and source-clock configuration.
        pub const MODEM_CLK_SOURCE_SEL: Field32 = Field32::new(3, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem APB,
        /// reset and source-clock configuration.
        pub const MODEM_PLL_CLK_EN: Field32 = Field32::new(4, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD]; CONFIDENCE[exact-s31-svd]. Modem APB,
        /// reset and source-clock configuration.
        pub const MODEM_XTAL_CLK_EN: Field32 = Field32::new(5, 1);
    }
}

/// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
/// CONFIDENCE[mixed-per-field]. S31 PMU modem ICG triggers and the active-state clock/power
/// word touched by the rev0 ROM.
pub mod pmu {
    use crate::{Register32, RegisterAccess};

    /// Peripheral base address.
    /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
    /// CONFIDENCE[mixed-per-field]. S31 PMU modem ICG triggers and the active-state clock/power
    /// word touched by the rev0 ROM.
    pub const BASE: usize = 0x20704000;

    /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS]; CONFIDENCE[exact-s31-layout]. HP-active modem
    /// ICG code.
    pub const HP_ACTIVE_ICG_MODEM: Register32 =
        Register32::described(0x20704014, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`HP_ACTIVE_ICG_MODEM`]. SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
    /// CONFIDENCE[exact-s31-layout]. HP-active modem ICG code.
    pub mod hp_active_icg_modem {
        use crate::Field32;

        /// Field layout from SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
        /// CONFIDENCE[exact-s31-layout]. HP-active modem ICG code.
        pub const HP_ACTIVE_DIG_ICG_MODEM_CODE: Field32 = Field32::new(30, 2);
    }

    /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK]; CONFIDENCE[mixed].
    /// Active-state clock power; bits 3:0 are deliberately unnamed beyond the ROM operation.
    pub const HP_ACTIVE_HP_CK_POWER: Register32 =
        Register32::described(0x2070401c, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`HP_ACTIVE_HP_CK_POWER`].
    /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK]; CONFIDENCE[mixed].
    /// Active-state clock power; bits 3:0 are deliberately unnamed beyond the ROM operation.
    pub mod hp_active_hp_ck_power {
        use crate::Field32;

        /// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK];
        /// CONFIDENCE[instruction-exact-semantics-unknown]. Rev0 ROM sets bits 3:0; individual
        /// meanings are unknown.
        pub const ROM_OPEN_FE_BB_UNKNOWN_LOW: Field32 = Field32::new(0, 4);
        /// Field layout from
        /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
        /// CONFIDENCE[mixed]. Active-state clock power; bits 3:0 are deliberately unnamed
        /// beyond the ROM operation.
        pub const HP_ACTIVE_XPD_XTALX2: Field32 = Field32::new(19, 1);
        /// Field layout from
        /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
        /// CONFIDENCE[mixed]. Active-state clock power; bits 3:0 are deliberately unnamed
        /// beyond the ROM operation.
        pub const HP_ACTIVE_I2C_ISO_EN: Field32 = Field32::new(20, 1);
        /// Field layout from
        /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
        /// CONFIDENCE[mixed]. Active-state clock power; bits 3:0 are deliberately unnamed
        /// beyond the ROM operation.
        pub const HP_ACTIVE_I2C_RETENTION: Field32 = Field32::new(21, 1);
        /// Field layout from
        /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
        /// CONFIDENCE[mixed]. Active-state clock power; bits 3:0 are deliberately unnamed
        /// beyond the ROM operation.
        pub const HP_ACTIVE_XPD_BB_I2C: Field32 = Field32::new(22, 1);
        /// Field layout from
        /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
        /// CONFIDENCE[mixed]. Active-state clock power; bits 3:0 are deliberately unnamed
        /// beyond the ROM operation.
        pub const HP_ACTIVE_XPD_PLL_I2C: Field32 = Field32::new(23, 4);
        /// Field layout from
        /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS,ROM_REV0_PHY_OPEN_FE_BB_CLK];
        /// CONFIDENCE[mixed]. Active-state clock power; bits 3:0 are deliberately unnamed
        /// beyond the ROM operation.
        pub const HP_ACTIVE_XPD_PLL: Field32 = Field32::new(27, 4);
    }

    /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS]; CONFIDENCE[exact-s31-layout]. Immediate
    /// system-clock update triggers.
    pub const IMM_SLEEP_SYSCLK: Register32 =
        Register32::described(0x207040f8, RegisterAccess::WriteOnly, None);

    /// Recovered fields of [`IMM_SLEEP_SYSCLK`]. SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
    /// CONFIDENCE[exact-s31-layout]. Immediate system-clock update triggers.
    pub mod imm_sleep_sysclk {
        use crate::Field32;

        /// Field layout from SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
        /// CONFIDENCE[exact-s31-layout]. Immediate system-clock update triggers.
        pub const UPDATE_DIG_ICG_SWITCH: Field32 = Field32::new(28, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
        /// CONFIDENCE[exact-s31-layout]. Immediate system-clock update triggers.
        pub const TIE_LOW_ICG_SLP_SEL: Field32 = Field32::new(29, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
        /// CONFIDENCE[exact-s31-layout]. Immediate system-clock update triggers.
        pub const TIE_HIGH_ICG_SLP_SEL: Field32 = Field32::new(30, 1);
        /// Field layout from SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
        /// CONFIDENCE[exact-s31-layout]. Immediate system-clock update triggers.
        pub const UPDATE_DIG_SYS_CLK_SEL: Field32 = Field32::new(31, 1);
    }

    /// SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS]; CONFIDENCE[exact-s31-layout]. Immediate modem
    /// ICG update trigger.
    pub const IMM_MODEM_ICG: Register32 =
        Register32::described(0x20704104, RegisterAccess::WriteOnly, None);

    /// Recovered fields of [`IMM_MODEM_ICG`]. SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
    /// CONFIDENCE[exact-s31-layout]. Immediate modem ICG update trigger.
    pub mod imm_modem_icg {
        use crate::Field32;

        /// Field layout from SOURCE[S31_ESP_PACS_SVD,S31_PMU_HEADERS];
        /// CONFIDENCE[exact-s31-layout]. Immediate modem ICG update trigger.
        pub const UPDATE_DIG_ICG_MODEM_EN: Field32 = Field32::new(31, 1);
    }
}

/// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK,BLOB_LIBPHY_PHY_CLOSE_FE_BB_CLK];
/// CONFIDENCE[instruction-exact-semantics-unknown]. OPAQUE PHY clock-gate registers recovered
/// from complete no-call ROM/blob leaves.
pub mod phy_clock_oracle {
    use crate::{Register32, RegisterAccess};

    /// Peripheral base address.
    /// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK,BLOB_LIBPHY_PHY_CLOSE_FE_BB_CLK];
    /// CONFIDENCE[instruction-exact-semantics-unknown]. OPAQUE PHY clock-gate registers
    /// recovered from complete no-call ROM/blob leaves.
    pub const BASE: usize = 0x20100000;

    /// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK,BLOB_LIBPHY_PHY_CLOSE_FE_BB_CLK];
    /// CONFIDENCE[instruction-exact-semantics-unknown]. ROM writes 0x1e7 to open and the blob
    /// writes zero to close.
    pub const FE_CLOCK_GATE_OPAQUE: Register32 =
        Register32::described(0x20100400, RegisterAccess::WriteOnly, None);

    /// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK,BLOB_LIBPHY_PHY_CLOSE_FE_BB_CLK];
    /// CONFIDENCE[instruction-exact-semantics-unknown]. ROM sets bits 1:0 and the blob clears
    /// them.
    pub const FE_BB_CLOCK_CONTROL_OPAQUE: Register32 =
        Register32::described(0x20100800, RegisterAccess::ReadWrite, None);

    /// Recovered fields of [`FE_BB_CLOCK_CONTROL_OPAQUE`].
    /// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK,BLOB_LIBPHY_PHY_CLOSE_FE_BB_CLK];
    /// CONFIDENCE[instruction-exact-semantics-unknown]. ROM sets bits 1:0 and the blob clears
    /// them.
    pub mod fe_bb_clock_control_opaque {
        use crate::Field32;

        /// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK,BLOB_LIBPHY_PHY_CLOSE_FE_BB_CLK];
        /// CONFIDENCE[instruction-exact-semantics-unknown]. Two-bit open/close mask; individual
        /// meanings are unknown.
        pub const ROM_FE_BB_ENABLE_UNKNOWN: Field32 = Field32::new(0, 2);
        /// SOURCE[BLOB_LIBPHY_PHY_BB_INIT]; CONFIDENCE[instruction-exact-semantics-unknown].
        /// The phy_bb_init parent sets bit 2 before calibration; the individual hardware
        /// meaning remains unknown.
        pub const PHY_CALIBRATION_CLOCK_UNKNOWN: Field32 = Field32::new(2, 1);
    }

    /// SOURCE[ROM_REV0_PHY_OPEN_FE_BB_CLK,BLOB_LIBPHY_PHY_CLOSE_FE_BB_CLK];
    /// CONFIDENCE[instruction-exact-semantics-unknown]. ROM writes all ones to open and the
    /// blob writes zero to close.
    pub const BB_CLOCK_GATE_OPAQUE: Register32 =
        Register32::described(0x20107c80, RegisterAccess::WriteOnly, None);
}

/// Complete generated register allow-list in ascending SVD order.
pub const ALL: [Register32; 38] = [
    modem_syscon::TEST_CONF,
    modem_syscon::CLK_CONF,
    modem_syscon::CLK_CONF_FORCE_ON,
    modem_syscon::CLK_CONF_POWER_ST,
    modem_syscon::MODEM_RST_CONF,
    modem_syscon::CLK_CONF1,
    modem_syscon::WIFI_BB_CFG,
    modem_syscon::FE_CFG,
    modem_syscon::MEM_RF1_CONF,
    modem_syscon::MEM_RF2_CONF,
    modem_syscon::BTMAC_CLK_CFG,
    modem_syscon::MEM_MODE_CONF,
    modem_lpcon::TEST_CONF,
    modem_lpcon::LP_TIMER_CONF,
    modem_lpcon::COEX_LP_CLK_CONF,
    modem_lpcon::WIFI_LP_CLK_CONF,
    modem_lpcon::MODEM_SRC_CLK_CONF,
    modem_lpcon::MODEM_32K_CLK_CONF,
    modem_lpcon::CLK_CONF,
    modem_lpcon::CLK_CONF_FORCE_ON,
    modem_lpcon::CLK_CONF_POWER_ST,
    modem_lpcon::RST_CONF,
    modem_lpcon::TICK_CONF,
    modem_lpcon::MEM_CONF,
    modem_lpcon::MEM_RF1_AUX_CTRL,
    modem_lpcon::MEM_RF2_AUX_CTRL,
    modem_lpcon::APB_MEM_SEL,
    modem_lpcon::MODEM_INTR_WAKEUP_CONF,
    modem_lpcon::MEM_CONF2,
    hp_sys_clkrst::MODEM_CTRL0,
    hp_sys_clkrst::MODEM_CONF,
    pmu::HP_ACTIVE_ICG_MODEM,
    pmu::HP_ACTIVE_HP_CK_POWER,
    pmu::IMM_SLEEP_SYSCLK,
    pmu::IMM_MODEM_ICG,
    phy_clock_oracle::FE_CLOCK_GATE_OPAQUE,
    phy_clock_oracle::FE_BB_CLOCK_CONTROL_OPAQUE,
    phy_clock_oracle::BB_CLOCK_GATE_OPAQUE,
];
