[package]
name = "open-esp-radio-esp32s31-wifi-esp-hal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP-HAL whole-radio singleton and platform adapter for ESP32-S31"

[features]
default = []
esp32s31 = [
    "dep:esp-hal",
    "dep:open-esp-radio-esp32s31-coex",
    "dep:open-esp-radio-esp32s31-hal",
    "dep:open-esp-radio-esp32s31-phy",
    "dep:open-esp-radio-esp32s31-wifi",
    "dep:open-esp-radio-esp32s31-wifi-mac",
    "dep:critical-section",
]

[dependencies]
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "81cd5c341f71f9d070b5d2b115d3ab2c7595a4df", default-features = false, features = ["esp32s31", "unstable"], optional = true }
open-esp-radio-esp32s31-coex = { path = "../../../chips/esp32s31/coex", optional = true }
open-esp-radio-esp32s31-hal = { path = "../../../chips/esp32s31/hal", optional = true }
open-esp-radio-esp32s31-phy = { path = "../../../chips/esp32s31/phy", optional = true }
open-esp-radio-esp32s31-wifi = { path = "../../../chips/esp32s31/wifi", optional = true }
open-esp-radio-esp32s31-wifi-mac = { path = "../../../chips/esp32s31/wifi/mac", optional = true }
critical-section = { version = "1.2.0", optional = true }

[lints]
workspace = true
