[package]
name = "open-esp-radio-esp32s31-coex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allocation-free ESP32-S31 radio coexistence policy and timer ownership"

[dependencies]
open-esp-radio-esp32s31-pac = { path = "../pac" }

[lints]
workspace = true
