[package]
name = "open-esp-radio-esp32s31-pac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Closed typed ESP32-S31 radio peripheral access crate"

[features]
validation-probes = ["open-esp-radio-esp32s31-pac-raw/validation-probes"]
test-register-catalog = []

[dependencies]
open-esp-radio-dma = { path = "../../../common/dma" }
open-esp-radio-esp32s31-pac-raw = { path = "../pac-raw", features = ["critical-section"] }

[dev-dependencies]
open-esp-radio-esp32s31-pac-raw = { path = "../pac-raw", features = ["validation-probes"] }

[lints]
workspace = true
