//! Application policy supplied when starting one Wi-Fi service.
//!
//! These values contain no peripheral, DMA or executor ownership.  The
//! topology and VIF identities remain in [`crate::WifiPlan`]; a request only
//! describes how an already validated role should operate for one runtime
//! epoch.

use core::{fmt, num::NonZeroU16};

use open_esp_radio_ieee80211::{channel::WifiChannel, ssid::WifiSsid};
pub use open_esp_radio_wifi_ap::{
    AccessPointClientLimit, AccessPointClientLimitError, AccessPointInactiveTimeout,
    AccessPointInactiveTimeoutError,
};
use open_esp_radio_wifi_softmac::{
    MacServiceCapabilities, WifiAccessPointConfig, WifiConfig, WifiConfigError, WifiStationConfig,
};
pub use open_esp_radio_wifi_sta::request::{
    StationDiscovery, StationScanChannelIter, StationScanChannelOrderIter, StationScanChannels,
    StationScanChannelsError, StationScanPolicy,
};
use open_esp_radio_wifi_sta::station::StaReconnectPolicy;
use open_esp_radio_wpa2::Pmk;

use crate::{WifiMonitorConfig, WifiPlan};

/// Finite standalone scan policy.
///
/// The current backend sends a broadcast Probe Request on every selected
/// channel and continues receiving for the complete dwell. It neither joins a
/// BSS nor materializes the station role.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WifiScanRequest {
    channels: StationScanChannels,
    dwell_millis: NonZeroU16,
}

impl WifiScanRequest {
    pub const fn new(channels: StationScanChannels, dwell_millis: NonZeroU16) -> Self {
        Self {
            channels,
            dwell_millis,
        }
    }

    pub const fn channels(self) -> StationScanChannels {
        self.channels
    }

    pub const fn dwell_millis(self) -> u16 {
        self.dwell_millis.get()
    }
}

/// Security material owned by one station runtime request.
///
/// The current production station path implements WPA2-Personal. The request
/// owns the derived PMK rather than retaining a plaintext passphrase across
/// reconnects. [`Pmk`] clears its key bytes on drop.
pub enum StationSecurity {
    Wpa2Personal(Pmk),
}

impl StationSecurity {
    pub const fn wpa2_personal(pmk: Pmk) -> Self {
        Self::Wpa2Personal(pmk)
    }

    pub const fn pmk(&self) -> &Pmk {
        match self {
            Self::Wpa2Personal(pmk) => pmk,
        }
    }

    pub fn into_pmk(self) -> Pmk {
        match self {
            Self::Wpa2Personal(pmk) => pmk,
        }
    }
}

impl fmt::Debug for StationSecurity {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Wpa2Personal(_) => formatter.write_str("Wpa2Personal(<redacted>)"),
        }
    }
}

/// Security material owned by one access-point epoch.
///
/// The public boundary accepts a PMK rather than retaining a plaintext
/// passphrase. Nonces, GTK material and replay counters are generated by the
/// AP owner when the epoch starts.
pub enum AccessPointSecurity {
    Wpa2Personal(Pmk),
}

impl AccessPointSecurity {
    pub const fn wpa2_personal(pmk: Pmk) -> Self {
        Self::Wpa2Personal(pmk)
    }

    pub const fn pmk(&self) -> &Pmk {
        match self {
            Self::Wpa2Personal(pmk) => pmk,
        }
    }

    pub fn into_pmk(self) -> Pmk {
        match self {
            Self::Wpa2Personal(pmk) => pmk,
        }
    }
}

impl fmt::Debug for AccessPointSecurity {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Wpa2Personal(_) => formatter.write_str("Wpa2Personal(<redacted>)"),
        }
    }
}

/// Complete owned policy for one AP service epoch.
///
/// Beacon cadence, DTIM and peer capacity are implementation guarantees, not
/// tuning switches: 100 TU, DTIM period 2 and a validated admission limit of
/// 1..=15 clients. The typed channel owns valid HT20/HT40 geometry before any
/// hardware owner moves.
pub struct AccessPointRequest {
    ssid: WifiSsid,
    security: AccessPointSecurity,
    channel: WifiChannel,
    client_limit: AccessPointClientLimit,
    inactive_timeout: AccessPointInactiveTimeout,
}

impl AccessPointRequest {
    pub const BEACON_INTERVAL_TU: u16 = 100;
    pub const DTIM_PERIOD: u8 = 2;
    pub const PEER_CAPACITY: usize = AccessPointClientLimit::MAX as usize;

    pub fn new(
        ssid: WifiSsid,
        security: AccessPointSecurity,
        channel: WifiChannel,
        client_limit: AccessPointClientLimit,
    ) -> Result<Self, AccessPointRequestError> {
        if channel.primary() == 14 {
            return Err(AccessPointRequestError::UnsupportedPrimaryChannel(14));
        }
        Ok(Self {
            ssid,
            security,
            channel,
            client_limit,
            inactive_timeout: AccessPointInactiveTimeout::default(),
        })
    }

    pub const fn ssid(&self) -> &WifiSsid {
        &self.ssid
    }

    pub const fn security(&self) -> &AccessPointSecurity {
        &self.security
    }

    pub const fn channel(&self) -> WifiChannel {
        self.channel
    }

    pub const fn client_limit(&self) -> AccessPointClientLimit {
        self.client_limit
    }

    pub const fn inactive_timeout(&self) -> AccessPointInactiveTimeout {
        self.inactive_timeout
    }

    pub const fn with_inactive_timeout(mut self, timeout: AccessPointInactiveTimeout) -> Self {
        self.inactive_timeout = timeout;
        self
    }

    pub fn into_parts(
        self,
    ) -> (
        WifiSsid,
        AccessPointSecurity,
        WifiChannel,
        AccessPointClientLimit,
        AccessPointInactiveTimeout,
    ) {
        (
            self.ssid,
            self.security,
            self.channel,
            self.client_limit,
            self.inactive_timeout,
        )
    }
}

impl fmt::Debug for AccessPointRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AccessPointRequest")
            .field("ssid", &self.ssid)
            .field("security", &self.security)
            .field("channel", &self.channel)
            .field("client_limit", &self.client_limit)
            .field("inactive_timeout", &self.inactive_timeout)
            .finish()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AccessPointRequestError {
    UnsupportedPrimaryChannel(u8),
}

impl fmt::Display for AccessPointRequestError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnsupportedPrimaryChannel(channel) => write!(
                formatter,
                "the current access-point service does not support primary channel {channel}"
            ),
        }
    }
}

impl core::error::Error for AccessPointRequestError {}

/// Complete owned request for one station service epoch.
pub struct StationRequest {
    ssid: WifiSsid,
    security: StationSecurity,
    reconnect: StaReconnectPolicy,
    scan: StationScanPolicy,
}

impl StationRequest {
    pub const fn new(
        ssid: WifiSsid,
        security: StationSecurity,
        reconnect: StaReconnectPolicy,
        scan: StationScanPolicy,
    ) -> Self {
        Self {
            ssid,
            security,
            reconnect,
            scan,
        }
    }

    pub const fn ssid(&self) -> &WifiSsid {
        &self.ssid
    }

    pub const fn security(&self) -> &StationSecurity {
        &self.security
    }

    pub const fn reconnect_policy(&self) -> StaReconnectPolicy {
        self.reconnect
    }

    pub const fn scan_policy(&self) -> StationScanPolicy {
        self.scan
    }

    pub fn into_parts(self) -> (StationDiscovery, StationSecurity, StaReconnectPolicy) {
        (
            StationDiscovery::new(self.ssid, self.scan),
            self.security,
            self.reconnect,
        )
    }
}

impl fmt::Debug for StationRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("StationRequest")
            .field("ssid", &self.ssid)
            .field("security", &self.security)
            .field("reconnect", &self.reconnect)
            .field("scan", &self.scan)
            .finish()
    }
}

/// One same-channel station plus SoftAP service request.
///
/// The station is connected first. Its associated channel becomes the sole
/// physical channel context; the AP is started only when its requested
/// channel is exactly that channel. No multi-channel scheduling fallback is
/// permitted.
pub struct StationAccessPointRequest {
    station: StationRequest,
    access_point: AccessPointRequest,
}

impl StationAccessPointRequest {
    pub const fn new(station: StationRequest, access_point: AccessPointRequest) -> Self {
        Self {
            station,
            access_point,
        }
    }

    pub const fn station(&self) -> &StationRequest {
        &self.station
    }

    pub const fn access_point(&self) -> &AccessPointRequest {
        &self.access_point
    }

    pub const fn required_channel(&self) -> WifiChannel {
        self.access_point.channel()
    }

    pub fn into_parts(self) -> (StationRequest, AccessPointRequest) {
        (self.station, self.access_point)
    }
}

impl fmt::Debug for StationAccessPointRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("StationAccessPointRequest")
            .field("station", &self.station)
            .field("access_point", &self.access_point)
            .field("channel_policy", &"station-associated-channel")
            .finish()
    }
}

/// Host/export capture policy independent of the DMA ring size.
///
/// Queue capacity and DMA placement belong to `RadioResources<Profile>`.
/// Saturation is always best-effort drop with accounting; no request may turn
/// a slow capture consumer into RX-DMA backpressure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MonitorCapturePolicy {
    snapshot_length: Option<NonZeroU16>,
}

impl MonitorCapturePolicy {
    pub const fn complete_frames() -> Self {
        Self {
            snapshot_length: None,
        }
    }

    pub const fn truncate_at(snapshot_length: NonZeroU16) -> Self {
        Self {
            snapshot_length: Some(snapshot_length),
        }
    }

    pub const fn snapshot_length(self) -> Option<u16> {
        match self.snapshot_length {
            Some(length) => Some(length.get()),
            None => None,
        }
    }
}

impl Default for MonitorCapturePolicy {
    fn default() -> Self {
        Self::complete_frames()
    }
}

/// Complete value-only request for one standalone monitor epoch.
pub struct MonitorRequest {
    channel: WifiChannel,
    monitor: WifiMonitorConfig,
    capture: MonitorCapturePolicy,
}

impl MonitorRequest {
    pub const fn new(channel: WifiChannel, monitor: WifiMonitorConfig) -> Self {
        Self {
            channel,
            monitor,
            capture: MonitorCapturePolicy::complete_frames(),
        }
    }

    pub const fn with_capture_policy(mut self, capture: MonitorCapturePolicy) -> Self {
        self.capture = capture;
        self
    }

    pub const fn channel(&self) -> WifiChannel {
        self.channel
    }

    pub const fn monitor_config(&self) -> WifiMonitorConfig {
        self.monitor
    }

    pub const fn capture_policy(&self) -> MonitorCapturePolicy {
        self.capture
    }
}

impl fmt::Debug for MonitorRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("MonitorRequest")
            .field("channel", &self.channel)
            .field("monitor", &self.monitor)
            .field("capture", &self.capture)
            .finish()
    }
}

/// One capability-checked Wi-Fi owner graph requested from the supervisor.
///
/// The implemented station and standalone-monitor graphs are physically
/// exclusive, so invalid mixtures are unrepresentable. Future STA+AP or
/// monitor-tap compositions require their own explicit variants and lifecycle
/// contracts rather than combinations of optional fields.
pub enum WifiServiceRequest {
    StandaloneScan {
        plan: WifiPlan,
        request: WifiScanRequest,
    },
    Station {
        plan: WifiPlan,
        request: StationRequest,
    },
    AccessPoint {
        plan: WifiPlan,
        request: AccessPointRequest,
    },
    StationAccessPoint {
        plan: WifiPlan,
        request: StationAccessPointRequest,
    },
    StandaloneMonitor {
        plan: WifiPlan,
        request: MonitorRequest,
    },
}

impl WifiServiceRequest {
    /// Join a finite scan request to the station-capable hardware topology.
    pub fn standalone_scan(
        plan: WifiPlan,
        request: WifiScanRequest,
    ) -> Result<Self, WifiServiceRequestFailure<WifiScanRequest>> {
        if plan.station().is_none() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::MissingScanTopology,
            ));
        }
        if plan.access_point().is_some() || plan.monitor().is_some() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::UnexpectedTopologyRole,
            ));
        }
        Ok(Self::StandaloneScan { plan, request })
    }

    /// Join a checked station-only topology to its runtime policy.
    pub fn station(
        plan: WifiPlan,
        request: StationRequest,
    ) -> Result<Self, WifiServiceRequestFailure<StationRequest>> {
        if plan.station().is_none() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::MissingStationTopology,
            ));
        }
        if plan.access_point().is_some() || plan.monitor().is_some() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::UnexpectedTopologyRole,
            ));
        }
        Ok(Self::Station { plan, request })
    }

    /// Join a checked access-point-only topology to its runtime policy.
    pub fn access_point(
        plan: WifiPlan,
        request: AccessPointRequest,
    ) -> Result<Self, WifiServiceRequestFailure<AccessPointRequest>> {
        if plan.access_point().is_none() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::MissingAccessPointTopology,
            ));
        }
        if plan.station().is_some() || plan.monitor().is_some() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::UnexpectedTopologyRole,
            ));
        }
        Ok(Self::AccessPoint { plan, request })
    }

    /// Join a checked same-channel STA+AP topology to one combined request.
    #[allow(
        clippy::result_large_err,
        reason = "a rejected no-alloc combined request must return both exact credential owners"
    )]
    pub fn station_access_point(
        plan: WifiPlan,
        request: StationAccessPointRequest,
    ) -> Result<Self, WifiServiceRequestFailure<StationAccessPointRequest>> {
        if plan.station().is_none() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::MissingStationTopology,
            ));
        }
        if plan.access_point().is_none() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::MissingAccessPointTopology,
            ));
        }
        if plan.monitor().is_some() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::UnexpectedTopologyRole,
            ));
        }
        Ok(Self::StationAccessPoint { plan, request })
    }

    /// Join a checked standalone-monitor topology to its runtime policy.
    pub fn standalone_monitor(
        plan: WifiPlan,
        request: MonitorRequest,
    ) -> Result<Self, WifiServiceRequestFailure<MonitorRequest>> {
        let Some(checked) = plan.standalone_monitor() else {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::NotStandaloneMonitorTopology,
            ));
        };
        if checked.monitor() != request.monitor_config() {
            return Err(WifiServiceRequestFailure::new(
                request,
                WifiServiceRequestError::MonitorPolicyMismatch,
            ));
        }
        Ok(Self::StandaloneMonitor { plan, request })
    }

    pub const fn plan(&self) -> WifiPlan {
        match self {
            Self::StandaloneScan { plan, .. }
            | Self::Station { plan, .. }
            | Self::AccessPoint { plan, .. }
            | Self::StationAccessPoint { plan, .. }
            | Self::StandaloneMonitor { plan, .. } => *plan,
        }
    }

    pub const fn scan_request(&self) -> Option<&WifiScanRequest> {
        match self {
            Self::StandaloneScan { request, .. } => Some(request),
            Self::Station { .. }
            | Self::AccessPoint { .. }
            | Self::StationAccessPoint { .. }
            | Self::StandaloneMonitor { .. } => None,
        }
    }

    pub const fn station_request(&self) -> Option<&StationRequest> {
        match self {
            Self::StandaloneScan { .. } => None,
            Self::Station { request, .. } => Some(request),
            Self::StationAccessPoint { request, .. } => Some(request.station()),
            Self::AccessPoint { .. } | Self::StandaloneMonitor { .. } => None,
        }
    }

    pub const fn access_point_request(&self) -> Option<&AccessPointRequest> {
        match self {
            Self::AccessPoint { request, .. } => Some(request),
            Self::StationAccessPoint { request, .. } => Some(request.access_point()),
            Self::StandaloneScan { .. } | Self::Station { .. } | Self::StandaloneMonitor { .. } => {
                None
            }
        }
    }

    pub const fn monitor_request(&self) -> Option<&MonitorRequest> {
        match self {
            Self::StandaloneScan { .. }
            | Self::Station { .. }
            | Self::AccessPoint { .. }
            | Self::StationAccessPoint { .. } => None,
            Self::StandaloneMonitor { request, .. } => Some(request),
        }
    }

    pub const fn station_access_point_request(&self) -> Option<&StationAccessPointRequest> {
        match self {
            Self::StationAccessPoint { request, .. } => Some(request),
            Self::StandaloneScan { .. }
            | Self::Station { .. }
            | Self::AccessPoint { .. }
            | Self::StandaloneMonitor { .. } => None,
        }
    }
}

impl fmt::Debug for WifiServiceRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::StandaloneScan { plan, request } => formatter
                .debug_struct("StandaloneScan")
                .field("plan", plan)
                .field("request", request)
                .finish(),
            Self::Station { plan, request } => formatter
                .debug_struct("Station")
                .field("plan", plan)
                .field("request", request)
                .finish(),
            Self::AccessPoint { plan, request } => formatter
                .debug_struct("AccessPoint")
                .field("plan", plan)
                .field("request", request)
                .finish(),
            Self::StationAccessPoint { plan, request } => formatter
                .debug_struct("StationAccessPoint")
                .field("plan", plan)
                .field("request", request)
                .finish(),
            Self::StandaloneMonitor { plan, request } => formatter
                .debug_struct("StandaloneMonitor")
                .field("plan", plan)
                .field("request", request)
                .finish(),
        }
    }
}

/// Runtime request does not match its independently checked owner topology.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WifiServiceRequestError {
    MissingScanTopology,
    MissingStationTopology,
    MissingAccessPointTopology,
    UnexpectedTopologyRole,
    NotStandaloneMonitorTopology,
    MonitorPolicyMismatch,
}

impl fmt::Display for WifiServiceRequestError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::MissingScanTopology => {
                "standalone scan requires a checked station-capable topology"
            }
            Self::MissingStationTopology => {
                "station service request requires a checked station topology"
            }
            Self::MissingAccessPointTopology => {
                "access-point service request requires a checked access-point topology"
            }
            Self::UnexpectedTopologyRole => {
                "station-only service request cannot contain another active Wi-Fi role"
            }
            Self::NotStandaloneMonitorTopology => {
                "standalone monitor request requires an exclusive checked monitor topology"
            }
            Self::MonitorPolicyMismatch => {
                "monitor runtime policy differs from the checked monitor topology"
            }
        })
    }
}

impl core::error::Error for WifiServiceRequestError {}

/// Request/topology mismatch retaining the exact role request.
#[derive(Debug)]
pub struct WifiServiceRequestFailure<R> {
    pub request: R,
    pub error: WifiServiceRequestError,
}

impl<R> WifiServiceRequestFailure<R> {
    const fn new(request: R, error: WifiServiceRequestError) -> Self {
        Self { request, error }
    }
}

/// Wi-Fi roles for which a supervisor composition owns complete static
/// resources.
///
/// This is not the currently active topology. In particular, provisioning
/// both station and standalone monitor allows sequential STA -> stopped ->
/// monitor transitions even on hardware which cannot run both concurrently.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WifiSupervisorConfiguration {
    capabilities: MacServiceCapabilities,
    station: Option<WifiStationConfig>,
    access_point: Option<WifiAccessPointConfig>,
    standalone_scan: bool,
    standalone_monitor: bool,
}

impl WifiSupervisorConfiguration {
    pub const fn new(capabilities: MacServiceCapabilities) -> Self {
        Self {
            capabilities,
            station: None,
            access_point: None,
            standalone_scan: false,
            standalone_monitor: false,
        }
    }

    pub const fn with_station(mut self, station: WifiStationConfig) -> Self {
        self.station = Some(station);
        self
    }

    pub const fn with_access_point(mut self, access_point: WifiAccessPointConfig) -> Self {
        self.access_point = Some(access_point);
        self
    }

    pub const fn with_standalone_scan(mut self) -> Self {
        self.standalone_scan = true;
        self
    }

    pub fn plan_scan(
        self,
        request: WifiScanRequest,
    ) -> Result<WifiServiceRequest, WifiServicePlanningFailure<WifiScanRequest>> {
        if !self.standalone_scan {
            return Err(WifiServicePlanningFailure {
                request,
                error: WifiServicePlanningError::ScanNotProvisioned,
            });
        }
        let Some(station) = self.station else {
            return Err(WifiServicePlanningFailure {
                request,
                error: WifiServicePlanningError::StationNotProvisioned,
            });
        };
        let plan = match WifiConfig::station(station).validate(self.capabilities) {
            Ok(plan) => plan,
            Err(error) => {
                return Err(WifiServicePlanningFailure {
                    request,
                    error: WifiServicePlanningError::Topology(error),
                });
            }
        };
        WifiServiceRequest::standalone_scan(plan, request).map_err(|failure| {
            WifiServicePlanningFailure {
                request: failure.request,
                error: WifiServicePlanningError::Request(failure.error),
            }
        })
    }

    pub const fn with_standalone_monitor(mut self) -> Self {
        self.standalone_monitor = true;
        self
    }

    pub fn plan_station(
        self,
        request: StationRequest,
    ) -> Result<WifiServiceRequest, WifiServicePlanningFailure<StationRequest>> {
        let Some(station) = self.station else {
            return Err(WifiServicePlanningFailure {
                request,
                error: WifiServicePlanningError::StationNotProvisioned,
            });
        };
        let plan = match WifiConfig::station(station).validate(self.capabilities) {
            Ok(plan) => plan,
            Err(error) => {
                return Err(WifiServicePlanningFailure {
                    request,
                    error: WifiServicePlanningError::Topology(error),
                });
            }
        };
        WifiServiceRequest::station(plan, request).map_err(|failure| WifiServicePlanningFailure {
            request: failure.request,
            error: WifiServicePlanningError::Request(failure.error),
        })
    }

    pub fn plan_access_point(
        self,
        request: AccessPointRequest,
    ) -> Result<WifiServiceRequest, WifiServicePlanningFailure<AccessPointRequest>> {
        let Some(access_point) = self.access_point else {
            return Err(WifiServicePlanningFailure {
                request,
                error: WifiServicePlanningError::AccessPointNotProvisioned,
            });
        };
        let plan = match WifiConfig::access_point(access_point).validate(self.capabilities) {
            Ok(plan) => plan,
            Err(error) => {
                return Err(WifiServicePlanningFailure {
                    request,
                    error: WifiServicePlanningError::Topology(error),
                });
            }
        };
        WifiServiceRequest::access_point(plan, request).map_err(|failure| {
            WifiServicePlanningFailure {
                request: failure.request,
                error: WifiServicePlanningError::Request(failure.error),
            }
        })
    }

    #[allow(
        clippy::result_large_err,
        reason = "planning is no-alloc and must return the untouched combined credential owner"
    )]
    pub fn plan_station_access_point(
        self,
        request: StationAccessPointRequest,
    ) -> Result<WifiServiceRequest, WifiServicePlanningFailure<StationAccessPointRequest>> {
        let Some(station) = self.station else {
            return Err(WifiServicePlanningFailure {
                request,
                error: WifiServicePlanningError::StationNotProvisioned,
            });
        };
        let Some(access_point) = self.access_point else {
            return Err(WifiServicePlanningFailure {
                request,
                error: WifiServicePlanningError::AccessPointNotProvisioned,
            });
        };
        let plan = match WifiConfig::station_access_point(station, access_point)
            .validate(self.capabilities)
        {
            Ok(plan) => plan,
            Err(error) => {
                return Err(WifiServicePlanningFailure {
                    request,
                    error: WifiServicePlanningError::Topology(error),
                });
            }
        };
        WifiServiceRequest::station_access_point(plan, request).map_err(|failure| {
            WifiServicePlanningFailure {
                request: failure.request,
                error: WifiServicePlanningError::Request(failure.error),
            }
        })
    }

    pub fn plan_monitor(
        self,
        request: MonitorRequest,
    ) -> Result<WifiServiceRequest, WifiServicePlanningFailure<MonitorRequest>> {
        if !self.standalone_monitor {
            return Err(WifiServicePlanningFailure {
                request,
                error: WifiServicePlanningError::MonitorNotProvisioned,
            });
        }
        let plan = match WifiConfig::monitor(request.monitor_config()).validate(self.capabilities) {
            Ok(plan) => plan,
            Err(error) => {
                return Err(WifiServicePlanningFailure {
                    request,
                    error: WifiServicePlanningError::Topology(error),
                });
            }
        };
        WifiServiceRequest::standalone_monitor(plan, request).map_err(|failure| {
            WifiServicePlanningFailure {
                request: failure.request,
                error: WifiServicePlanningError::Request(failure.error),
            }
        })
    }
}

/// Why a provisioned supervisor cannot construct a checked service request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WifiServicePlanningError {
    ScanNotProvisioned,
    StationNotProvisioned,
    AccessPointNotProvisioned,
    MonitorNotProvisioned,
    Topology(WifiConfigError),
    Request(WifiServiceRequestError),
}

/// Planning failure retaining the untouched application request.
#[derive(Debug)]
pub struct WifiServicePlanningFailure<R> {
    pub request: R,
    pub error: WifiServicePlanningError,
}

#[cfg(test)]
mod tests {
    use super::*;
    use open_esp_radio_ieee80211::{channel::WifiChannelWidth, station::StaAssociationPreference};
    use open_esp_radio_wifi_softmac::{
        MacInterfaceCapabilities, MacOperationOwner, MacOperationOwnership, MacResourceLimits,
        MacServiceCapabilities, WifiConfig, WifiMacAddress, WifiStationConfig,
    };

    const TEST_CAPABILITIES: MacServiceCapabilities = MacServiceCapabilities {
        interfaces: MacInterfaceCapabilities {
            station_interfaces: 1,
            access_point_interfaces: 0,
            simultaneous_station_access_point: false,
            standalone_monitor: true,
            monitor_with_interfaces: false,
            raw_monitor_tap: false,
            normalized_monitor_tap: true,
            protocol_validated_monitor_tap: false,
        },
        operations: MacOperationOwnership {
            tx_fcs_generation: MacOperationOwner::Hardware,
            immediate_ack_response: MacOperationOwner::Hardware,
            csma_ca_backoff_countdown: MacOperationOwner::Hardware,
            unicast_retry_policy: MacOperationOwner::Software,
            tx_sequence_assignment: MacOperationOwner::Software,
            ccmp_key_selection: MacOperationOwner::Software,
            ccmp_packet_number: MacOperationOwner::Software,
            ccmp_transform: MacOperationOwner::Hardware,
            rx_block_ack_matching: MacOperationOwner::Hardware,
            rx_reorder: MacOperationOwner::Software,
            tx_block_ack_capture: MacOperationOwner::Hardware,
            tx_ampdu_retry_selection: MacOperationOwner::Software,
        },
        resources: MacResourceLimits {
            channel_contexts: 1,
            ordinary_tx_queues: 4,
            rx_block_ack_entries: 8,
            rx_block_ack_max_tid: 7,
            rx_block_ack_max_window: 64,
            tx_block_ack_max_window: 32,
            tx_ampdu_max_subframes: 32,
            station_pairwise_ccmp_slots: 1,
            station_group_ccmp_slots: 1,
            access_point_pairwise_ccmp_slots: 0,
            access_point_group_ccmp_slots: 0,
            access_point_association_entries: 0,
            access_point_encrypted_clients: 0,
        },
    };

    const AP_TEST_CAPABILITIES: MacServiceCapabilities = MacServiceCapabilities {
        interfaces: MacInterfaceCapabilities {
            station_interfaces: 1,
            access_point_interfaces: 1,
            simultaneous_station_access_point: false,
            standalone_monitor: true,
            monitor_with_interfaces: false,
            raw_monitor_tap: false,
            normalized_monitor_tap: true,
            protocol_validated_monitor_tap: false,
        },
        resources: MacResourceLimits {
            access_point_pairwise_ccmp_slots: 15,
            access_point_group_ccmp_slots: 1,
            access_point_association_entries: 15,
            access_point_encrypted_clients: 15,
            ..TEST_CAPABILITIES.resources
        },
        ..TEST_CAPABILITIES
    };

    const STA_AP_TEST_CAPABILITIES: MacServiceCapabilities = MacServiceCapabilities {
        interfaces: MacInterfaceCapabilities {
            simultaneous_station_access_point: true,
            ..AP_TEST_CAPABILITIES.interfaces
        },
        ..AP_TEST_CAPABILITIES
    };

    fn station_request() -> StationRequest {
        StationRequest::new(
            WifiSsid::new(b"test-network").unwrap(),
            StationSecurity::wpa2_personal(Pmk::derive(b"password", b"test-network").unwrap()),
            StaReconnectPolicy::new(3, 100, 1_000, 100).unwrap(),
            StationScanPolicy::new(
                StationScanChannels::CHANNELS_1_TO_13,
                NonZeroU16::new(20).unwrap(),
                StaAssociationPreference::Automatic,
            ),
        )
    }

    fn access_point_request() -> AccessPointRequest {
        AccessPointRequest::new(
            WifiSsid::new(b"test-access-point").unwrap(),
            AccessPointSecurity::wpa2_personal(
                Pmk::derive(b"password", b"test-access-point").unwrap(),
            ),
            WifiChannel::mhz20(6).unwrap(),
            AccessPointClientLimit::new(4).unwrap(),
        )
        .unwrap()
    }

    #[test]
    fn station_debug_never_formats_key_material() {
        let request = station_request();
        let debug = std::format!("{request:?}");
        assert!(debug.contains("<redacted>"));
        assert!(!debug.contains("password"));
    }

    #[test]
    fn access_point_request_is_narrow_and_never_formats_key_material() {
        let request = access_point_request();
        assert_eq!(request.channel().primary(), 6);
        assert_eq!(AccessPointRequest::BEACON_INTERVAL_TU, 100);
        assert_eq!(AccessPointRequest::DTIM_PERIOD, 2);
        assert_eq!(AccessPointRequest::PEER_CAPACITY, 15);
        assert_eq!(request.client_limit().get(), 4);
        assert_eq!(request.inactive_timeout().seconds(), 300);
        let debug = std::format!("{request:?}");
        assert!(debug.contains("<redacted>"));
        assert!(!debug.contains("password"));

        let wide = AccessPointRequest::new(
            WifiSsid::new(b"wide").unwrap(),
            AccessPointSecurity::wpa2_personal(Pmk::derive(b"password", b"wide").unwrap()),
            WifiChannel::new_2_4_ghz(6, WifiChannelWidth::Mhz40Above).unwrap(),
            AccessPointClientLimit::new(4).unwrap(),
        )
        .unwrap();
        assert_eq!(wide.channel().width(), WifiChannelWidth::Mhz40Above);

        let request = access_point_request().with_inactive_timeout(
            AccessPointInactiveTimeout::new(30).expect("valid inactivity timeout"),
        );
        assert_eq!(request.inactive_timeout().seconds(), 30);
        let (_, _, _, _, timeout) = request.into_parts();
        assert_eq!(timeout.seconds(), 30);
    }

    #[test]
    fn combined_request_requires_one_checked_same_channel_owner_graph() {
        let station = WifiStationConfig::new(WifiMacAddress::new([0x02, 0, 0, 0, 0, 1]).unwrap());
        let access_point =
            WifiAccessPointConfig::new(WifiMacAddress::new([0x02, 0, 0, 0, 0, 2]).unwrap());
        let configuration = WifiSupervisorConfiguration::new(STA_AP_TEST_CAPABILITIES)
            .with_station(station)
            .with_access_point(access_point);
        let service = configuration
            .plan_station_access_point(StationAccessPointRequest::new(
                station_request(),
                access_point_request(),
            ))
            .unwrap();

        assert!(service.plan().station().is_some());
        assert!(service.plan().access_point().is_some());
        assert_eq!(
            service
                .station_access_point_request()
                .unwrap()
                .required_channel(),
            WifiChannel::mhz20(6).unwrap()
        );
    }

    #[test]
    fn monitor_request_separates_capture_from_dma_capacity() {
        let request = MonitorRequest::new(
            WifiChannel::new_2_4_ghz(6, WifiChannelWidth::Mhz20).unwrap(),
            WifiMonitorConfig::normalized(),
        )
        .with_capture_policy(MonitorCapturePolicy::truncate_at(
            NonZeroU16::new(512).unwrap(),
        ));
        assert_eq!(request.channel().primary(), 6);
        assert_eq!(request.capture_policy().snapshot_length(), Some(512));
    }

    #[test]
    fn service_request_checks_runtime_policy_against_topology() {
        let address = WifiMacAddress::new([0x02, 0, 0, 0, 0, 1]).unwrap();
        let station_plan = WifiConfig::station(WifiStationConfig::new(address))
            .validate(TEST_CAPABILITIES)
            .unwrap();
        let service = WifiServiceRequest::station(station_plan, station_request()).unwrap();
        assert!(service.station_request().is_some());
        assert!(service.monitor_request().is_none());

        let channel = WifiChannel::mhz20(6).unwrap();
        let monitor = MonitorRequest::new(channel, WifiMonitorConfig::normalized());
        let failure = WifiServiceRequest::standalone_monitor(station_plan, monitor).unwrap_err();
        assert_eq!(
            failure.error,
            WifiServiceRequestError::NotStandaloneMonitorTopology
        );
        assert_eq!(failure.request.channel().primary(), 6);
    }

    #[test]
    fn supervisor_provisions_sequential_station_and_monitor_topologies() {
        let address = WifiMacAddress::new([0x02, 0, 0, 0, 0, 1]).unwrap();
        let configuration = WifiSupervisorConfiguration::new(TEST_CAPABILITIES)
            .with_station(WifiStationConfig::new(address))
            .with_standalone_monitor();

        let station = configuration.plan_station(station_request()).unwrap();
        assert!(station.plan().station().is_some());
        assert!(station.plan().monitor().is_none());

        let monitor_request = MonitorRequest::new(
            WifiChannel::mhz20(11).unwrap(),
            WifiMonitorConfig::normalized(),
        );
        let monitor = configuration.plan_monitor(monitor_request).unwrap();
        assert!(monitor.plan().station().is_none());
        assert!(monitor.plan().standalone_monitor().is_some());
    }

    #[test]
    fn supervisor_provisions_an_exclusive_access_point_epoch() {
        let address = WifiMacAddress::new([0x02, 0, 0, 0, 0, 2]).unwrap();
        let configuration = WifiSupervisorConfiguration::new(AP_TEST_CAPABILITIES)
            .with_access_point(WifiAccessPointConfig::new(address));

        let service = configuration
            .plan_access_point(access_point_request())
            .unwrap();
        assert!(service.plan().station().is_none());
        assert!(service.plan().access_point().is_some());
        assert!(service.access_point_request().is_some());
    }

    #[test]
    fn supervisor_provisions_finite_scan_on_the_station_owner_graph() {
        let address = WifiMacAddress::new([0x02, 0, 0, 0, 0, 1]).unwrap();
        let request = WifiScanRequest::new(
            StationScanChannels::CHANNELS_1_TO_13,
            NonZeroU16::new(20).unwrap(),
        );
        let configuration = WifiSupervisorConfiguration::new(TEST_CAPABILITIES)
            .with_station(WifiStationConfig::new(address))
            .with_standalone_scan();

        let scan = configuration.plan_scan(request).unwrap();
        assert!(scan.plan().station().is_some());
        assert!(scan.scan_request().is_some());
        assert!(scan.station_request().is_none());
    }

    #[test]
    fn unprovisioned_scan_is_rejected_before_materialization() {
        let request = WifiScanRequest::new(
            StationScanChannels::CHANNELS_1_TO_13,
            NonZeroU16::new(37).unwrap(),
        );
        let failure = WifiSupervisorConfiguration::new(TEST_CAPABILITIES)
            .plan_scan(request)
            .unwrap_err();
        assert_eq!(failure.error, WifiServicePlanningError::ScanNotProvisioned);
        assert_eq!(failure.request.dwell_millis(), 37);
    }

    #[test]
    fn unprovisioned_role_rejection_returns_the_exact_request() {
        let configuration = WifiSupervisorConfiguration::new(TEST_CAPABILITIES);
        let request = MonitorRequest::new(
            WifiChannel::mhz20(9).unwrap(),
            WifiMonitorConfig::normalized(),
        );
        let failure = configuration.plan_monitor(request).unwrap_err();
        assert_eq!(
            failure.error,
            WifiServicePlanningError::MonitorNotProvisioned
        );
        assert_eq!(failure.request.channel().primary(), 9);
    }
}
