schema = 1
default-address-space = "cpu"

[[address-spaces]]
id = "cpu"
address-width = 32
endianness = "little"

[[regions]]
name = "modem-ieee802154"
address-space = "cpu"
kind = "mmio"
start = 0x600A3000
end-exclusive = 0x600A4000
permissions = "rw"

[[regions]]
name = "modem-etm-ieee802154"
address-space = "cpu"
kind = "mmio"
start = 0x600A8800
end-exclusive = 0x600A8828
permissions = "rw"

[[regions]]
name = "ieee802154-core0-route"
address-space = "cpu"
kind = "mmio"
start = 0x60010030
end-exclusive = 0x60010034
permissions = "rw"
