[package]
name = "open-esp-radio-hil-esp32s31-trace-probes-elf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[dependencies]
open-esp-radio-hil-esp32s31-trace-probes = { path = "../trace-probes" }

[lints.rust]
unexpected_cfgs = "allow"
