use super::*;

// Independently specified Action-body vectors, including binary strings and
// unknown extensions. They are not generated by the encoders under test.
const REPORT: &[u8] = &[
    52, 21, 2, 0, 0, 0, 0, 9, 0x44, 0x33, 0x22, 0x11, 81, 6, 7, 3, 1, 200, 221, 3, 1, 2, 3,
];

#[test]
fn neighbor_request_preserves_binary_ssid_and_unknown_elements() {
    let fixture = [5, 4, 9, 0, 3, b'A', 0, b'B', 221, 2, 7, 8];
    let request = NeighborReportRequest::parse(&fixture).unwrap();
    assert_eq!(request.ssid().unwrap(), Some(&b"A\0B"[..]));
    let mut output = [0; 64];
    let len = request.encode(&mut output).unwrap();
    assert_eq!(&output[..len], fixture);
    assert_eq!(
        NeighborReportRequest::parse(&[5, 4, 1])
            .unwrap()
            .ssid()
            .unwrap(),
        None
    );
    assert_eq!(
        NeighborReportRequest::parse(&[5, 4, 1, 0, 0])
            .unwrap()
            .ssid()
            .unwrap(),
        Some(&[][..])
    );
}

#[test]
fn neighbor_response_preserves_all_subelements() {
    let fixture: std::vec::Vec<_> = [5, 5, 9]
        .into_iter()
        .chain(REPORT.iter().copied())
        .chain([221, 1, 77])
        .collect();
    let response = NeighborReportResponse::parse(&fixture).unwrap();
    let report = response.reports().next().unwrap().unwrap();
    assert_eq!(report.bssid, [2, 0, 0, 0, 0, 9]);
    assert_eq!(report.bssid_information, 0x11223344);
    assert_eq!(report.preference().unwrap(), Some(200));
    assert_eq!(
        report.subelements.unique(221).unwrap(),
        Some(&[1, 2, 3][..])
    );
    let mut output = [0; 64];
    let len = response.encode(&mut output).unwrap();
    assert_eq!(&output[..len], fixture);
    let mut report_out = [0; 64];
    let len = report.encode(&mut report_out).unwrap();
    assert_eq!(&report_out[..len], REPORT);
}

#[test]
fn btm_optional_fields_and_extensions_round_trip_external_vector() {
    let fixture: std::vec::Vec<_> = [
        10, 7, 9, 27, 42, 0, 3, 4, 10, 1, 2, 3, 4, 5, 6, 7, 8, 2, 0, 3, 0, 255, b'x',
    ]
    .into_iter()
    .chain(REPORT.iter().copied())
    .chain([221, 2, 31, 32])
    .collect();
    let request = BtmRequest::parse(&fixture).unwrap();
    assert_eq!(request.disassociation_timer, 42);
    assert_eq!(
        request.termination,
        Some(BssTerminationDuration {
            tsf: 0x0807060504030201,
            duration_minutes: 2
        })
    );
    assert_eq!(request.session_url, Some(&[0, 255, b'x'][..]));
    let mut output = [0; 80];
    let len = request.encode(&mut output).unwrap();
    assert_eq!(&output[..len], fixture);
}

#[test]
fn btm_query_and_responses_preserve_candidates_and_status() {
    let query: std::vec::Vec<_> = [10, 6, 4, 19]
        .into_iter()
        .chain(REPORT.iter().copied())
        .collect();
    let mut output = [0; 80];
    let len = BtmQuery::parse(&query)
        .unwrap()
        .encode(&mut output)
        .unwrap();
    assert_eq!(&output[..len], query);
    let accept: std::vec::Vec<_> = [10, 8, 4, 0, 0, 2, 0, 0, 0, 0, 9]
        .into_iter()
        .chain(REPORT.iter().copied())
        .collect();
    let response = BtmResponse::parse(&accept).unwrap();
    assert_eq!(response.target_bssid, Some([2, 0, 0, 0, 0, 9]));
    let len = response.encode(&mut output).unwrap();
    assert_eq!(&output[..len], accept);
    let reject = [10, 8, 4, 250, 7, 221, 1, 42];
    let response = BtmResponse::parse(&reject).unwrap();
    assert_eq!(response.status, BtmStatus(250));
    let len = response.encode(&mut output).unwrap();
    assert_eq!(&output[..len], reject);
    assert_eq!(
        BtmResponse::parse(&[10, 8, 4, 0, 0]),
        Err(WireError::Truncated)
    );
}

#[test]
fn malformed_bodies_and_duplicate_singletons_fail_closed() {
    for bytes in [
        &[5, 4, 0][..],
        &[5, 4, 1, 0][..],
        &[5, 4, 1, 0, 2, 1][..],
        &[5, 4, 1, 0, 0, 0, 0][..],
    ] {
        assert!(NeighborReportRequest::parse(bytes).is_err());
    }
    for length in 4..REPORT.len() {
        let bytes: std::vec::Vec<_> = [5, 5, 1]
            .into_iter()
            .chain(REPORT[..length].iter().copied())
            .collect();
        assert!(NeighborReportResponse::parse(&bytes).is_err());
    }
    let mut duplicate = REPORT[2..15].to_vec();
    duplicate.extend_from_slice(&[3, 1, 10, 3, 1, 20]);
    assert_eq!(
        NeighborReport::parse(&duplicate),
        Err(WireError::DuplicateElement(3))
    );
    let mut invalid = REPORT[2..15].to_vec();
    invalid.extend_from_slice(&[3, 2, 10, 20]);
    assert_eq!(
        NeighborReport::parse(&invalid),
        Err(WireError::InvalidElementLength(3))
    );
    for fixture in [
        &[10, 7, 1, 8, 0, 0, 1][..],
        &[10, 7, 1, 16, 0, 0, 1, 2, 1][..],
    ] {
        assert!(BtmRequest::parse(fixture).is_err());
    }
    assert!(BtmResponse::parse(&[10, 8, 1, 1, 0, 221]).is_err());
}

#[test]
fn encoders_refuse_before_modifying_output() {
    let request = BtmRequest::parse(&[10, 7, 9, 0, 0, 0, 1]).unwrap();
    let mut short = [0xa5; 6];
    assert_eq!(
        request.encode(&mut short),
        Err(WireError::OutputTooSmall { required: 7 })
    );
    assert_eq!(short, [0xa5; 6]);
    let mut invalid = request;
    invalid.mode = BtmRequestMode::TERMINATION;
    let mut output = [0xa5; 32];
    assert_eq!(
        invalid.encode(&mut output),
        Err(WireError::InconsistentFields)
    );
    assert_eq!(output, [0xa5; 32]);
    let mut extended = request;
    extended.mode = BtmRequestMode(0x80);
    let len = extended.encode(&mut output).unwrap();
    assert_eq!(
        BtmRequest::parse(&output[..len]).unwrap().mode,
        BtmRequestMode(0x80)
    );
}
