[package]
name = "open-esp-radio-esp32s31-wifi-sta"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Executor-independent ESP32-S31 Wi-Fi station composition"

[dependencies]
open-esp-radio-esp32s31-hal = { path = "../../hal" }
open-esp-radio-esp32s31-phy = { path = "../../phy" }
open-esp-radio-esp32s31-wifi-mac = { path = "../mac" }
open-esp-radio-esp32s31-wifi-dma = { path = "../dma" }
open-esp-radio-esp32s31-wifi = { path = ".." }
open-esp-radio-ieee80211 = { path = "../../../../wifi/ieee80211" }
open-esp-radio-wifi-softmac = { path = "../../../../wifi/softmac" }
open-esp-radio-wpa2 = { path = "../../../../wifi/wpa2" }
open-esp-radio-wifi-sta = { path = "../../../../wifi/sta" }

[lints]
workspace = true
