[package]
name = "oer-xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
oer-process = { path = "../process" }
fs2 = "0.4"
serialport = { version = "4.8.1", default-features = false }
oer-firmware = { path = "../firmware" }
open-esp-radio-memory-report = { path = "../memory-report" }
cargo_metadata = "=0.23.1"
clap = { version = "=4.5.48", features = ["derive"] }
object = { version = "=0.39.1", default-features = false, features = ["archive", "elf", "read", "std"] }
rustc-demangle = "=0.1.28"
serde_json = "=1.0.151"
tempfile = "=3.27.0"
toml = "=1.1.4"

[target.'cfg(unix)'.dependencies]
libc = "=0.2.189"

[lints]
workspace = true
