[package]
name = "open-esp-radio-wifi-sta"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Executor- and chip-independent Wi-Fi station MLME and policy"

[dependencies]
open-esp-radio-ieee80211 = { path = "../mac" }

[lints]
workspace = true
