[package]
name = "open-esp-radio-esp32s31-wifi-dma"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Audited ESP32-S31 Wi-Fi MAC DMA ownership and descriptor ring"

[features]
default = []
validation-raw-dma = []

[dependencies]
open-esp-radio-dma = { path = "../../../../common/dma" }
open-esp-radio-esp32s31-pac = { path = "../../pac" }
pin-project = "1.1.13"
vcell = "0.1.3"

[lints]
workspace = true
