[package]
name = "open-esp-radio-esp32s31-wifi-embassy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Embassy runtime adapter for the open ESP32-S31 Wi-Fi radio"

[dependencies]
embassy-futures = "0.1.2"
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
open-esp-radio-embassy-net = { path = "../../embassy-net" }
open-esp-radio-esp32s31-hal = { path = "../../../chips/esp32s31/hal" }
open-esp-radio-esp32s31-registers = { path = "../../../chips/esp32s31/registers" }
open-esp-radio-esp32s31-phy = { path = "../../../chips/esp32s31/phy" }
open-esp-radio-esp32s31-wifi-mac = { path = "../../../chips/esp32s31/wifi/mac" }
open-esp-radio-esp32s31-wifi-sta = { path = "../../../chips/esp32s31/wifi/sta" }
open-esp-radio-ieee80211 = { path = "../../../wifi/ieee80211" }
open-esp-radio-wifi-softmac = { path = "../../../wifi/softmac" }
open-esp-radio-wifi-sta = { path = "../../../wifi/sta" }
open-esp-radio-wpa2 = { path = "../../../wifi/wpa2" }
open-esp-radio-wifi-embassy = { path = "../wifi" }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
embassy-time = { version = "0.5.1", features = ["generic-queue-64", "std"] }

[lints]
workspace = true
