// @generated by vendor-binary-workbench from the reviewed PAC API pack.
// Do not edit this file; edit registers/api.toml and run project publish.

/// Reviewed writable images for the MAC interrupt-enable register.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MacInterruptMask(u32);

impl MacInterruptMask {
    /// Keep every MAC interrupt source disabled.
    pub const NONE: Self = Self(0x00000000);
    /// Complete mask published by the qualified cold receive initializer.
    pub const COLD_RX: Self = Self(0x19a879e0);

    /// Combine reviewed writable values.
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    /// Test whether all bits in `other` are present.
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }

    /// Read-only numeric image for diagnostics and the private raw-PAC bridge.
    /// There is intentionally no inverse integer constructor.
    pub const fn bits(self) -> u32 {
        self.0
    }
}

impl core::ops::BitOr for MacInterruptMask {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self::Output {
        self.union(rhs)
    }
}

/// Typed bridge for the reviewed `mac_interrupt_enable` complete-register transaction.
#[inline]
pub(crate) fn mac_interrupt_enable(
    registers: &crate::svd::WifiMacInterrupt,
    value: MacInterruptMask,
) {
    crate::svd::full_register_write::mac_interrupt_enable(registers, value.bits());
}
