[workspace]
resolver = "3"
members = ["board", "bootstrap", "runtime"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "bee3369c35dfc10048b1d524150d99869f8a4352", default-features = false }
esp-bootloader-esp-idf = { git = "https://github.com/ermacv/esp-hal", rev = "bee3369c35dfc10048b1d524150d99869f8a4352", default-features = false }
static_cell = "2.1.1"
open-esp-radio-esp32s31-platform-pac = { path = "../../driver/adapters/esp-hal/esp32s31/soc", features = ["esp32s31"] }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
debug = true
panic = "abort"
strip = false

[patch."https://github.com/esp-rs/esp-pacs"]
esp32s31 = { git = "https://github.com/ermacv/esp-pacs", rev = "507d14dbccfc26128b929b044d76f09cf2d1d2f6" }

[patch."https://github.com/ermacv/embassy.git"]
embassy-futures = { version = "0.1.2", registry = "crates-io" }
embassy-sync = { version = "0.8.0", registry = "crates-io" }
embassy-time = { version = "0.5.1", registry = "crates-io" }
