// @generated by `cargo registers` from the reviewed PAC API policy.
// Do not edit this file; edit the publication's API policy and run
// `cargo registers generate`.

/// Reviewed Wi-Fi MAC interface selector shared by address, BSSID, crypto, TX and ordinary receive-BlockAck transactions.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum MacInterface {
    /// Infrastructure-station hardware context; traced from STA callers into interface and key-control fields.
    Station = 0x00000000,
    /// SoftAP hardware context; traced from AP callers into interface and key-control fields.
    AccessPoint = 0x00000001,
    /// Reviewed third hardware selector accepted by the complete EDCA and RX BlockAck leaves; its protocol-role semantics are not assigned.
    Context2 = 0x00000002,
    /// Reviewed fourth hardware selector accepted by the complete EDCA and RX BlockAck leaves; its protocol-role semantics are not assigned.
    Context3 = 0x00000003,
}

impl MacInterface {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Typed bridge for the reviewed `enable_mac_interface_receive_policy` fixed field-replacement transaction.
#[inline]
pub(crate) fn enable_mac_interface_receive_policy(
    registers: &crate::svd::WifiMacInterfaceAddress,
    index: usize,
) {
    crate::svd::field_replace_modify::enable_mac_interface_receive_policy(registers, index);
}
