[package]
name = "open-esp-radio-hil-esp32s31-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[features]
default = ["code-psram", "profile-psram-data"]
code-flash = []
code-psram = []
profile-psram-data = []
profile-sram-data = []
boot-smoke = []
open-radio-hil = [
    "dep:embassy-futures",
    "dep:embassy-net",
    "dep:embassy-net-driver",
    "dep:embassy-sync",
    "dep:embedded-io-async",
    "dep:log",
    "dep:open-esp-radio",
    "dep:open-esp-radio-esp32s31-wifi-esp-hal",
]

[dependencies]
embassy-executor.workspace = true
embassy-futures = { workspace = true, optional = true }
embassy-net = { workspace = true, optional = true }
embassy-net-driver = { workspace = true, optional = true }
embassy-sync = { workspace = true, optional = true }
embassy-time.workspace = true
embedded-io-async = { workspace = true, optional = true }
esp-hal = { workspace = true, features = ["esp32s31", "rt", "unstable"] }
log = { workspace = true, optional = true }
open-esp-radio = { workspace = true, optional = true }
open-esp-radio-esp32s31-wifi-esp-hal = { workspace = true, features = ["esp32s31"], optional = true }
open-esp-radio-hil-esp32s31-runtime-support = { path = "../runtime-support" }
static_cell.workspace = true

[lints.rust]
unexpected_cfgs = "allow"
