[package]
name = "open-esp-radio-esp32s31-bluetooth-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP32-S31 Bluetooth controller-memory layouts and ownership"

[dependencies]
open-esp-radio-esp32s31-hal = { path = "../../hal" }
pin-project = "1.1.13"

[lints]
workspace = true
