[package]
name = "open-esp-radio-esp32s31-ieee802154-embassy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Embassy runtime adapter for the ESP32-S31 IEEE 802.15.4 radio"

[dependencies]
embassy-sync = "0.8.0"
open-esp-radio-esp32s31-ieee802154-dma = { path = "../../../chips/esp32s31/ieee802154/dma" }
open-esp-radio-esp32s31-ieee802154-irq = { path = "../../../chips/esp32s31/ieee802154/irq" }
open-esp-radio-esp32s31-ieee802154-mac = { path = "../../../chips/esp32s31/ieee802154/mac" }
open-esp-radio-esp32s31-ieee802154-runtime = { path = "../../../chips/esp32s31/ieee802154/runtime" }

[dev-dependencies]
embassy-futures = "0.1.2"
open-esp-radio-esp32s31-ieee802154-runtime = { path = "../../../chips/esp32s31/ieee802154/runtime", features = ["validation-probes"] }

[lints]
workspace = true
