[package]
name = "oer-esp32s31-bluetooth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP32-S31 Bluetooth controller hardware boundary"

[features]
validation-probes = [
    "oer-esp32s31-pac/validation-probes",
    "oer-esp32s31-phy/validation-probes",
]

[dependencies]
critical-section = "1.2.0"
embassy-sync = "0.8.0"
oer-bluetooth-hci = { path = "../../../../protocols/bluetooth/hci" }
oer-bluetooth-ll = { path = "../../../../protocols/bluetooth/le/ll" }
oer-esp32s31-hal = { path = "../../hal" }
oer-esp32s31-bluetooth-memory = { path = "memory" }
oer-esp32s31-pac = { path = "../../pac" }
oer-esp32s31-phy = { path = "../../phy" }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
embassy-futures = "0.1.2"
oer-esp32s31-hal = { path = "../../hal", features = ["validation-probes"] }
oer-esp32s31-pac = { path = "../../pac", features = ["validation-probes"] }

[lints]
workspace = true

[package.metadata.open-radio]
scope = "production"
layer = "hardware"
platform = "esp32s31"
