[package]
name = "open-esp-radio-esp32s31-wifi-esp-hal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP-HAL Wi-Fi singleton and platform adapter for the open ESP32-S31 radio"

[features]
default = []
esp32s31 = [
    "dep:esp-hal",
    "dep:open-esp-radio-esp32s31-hal",
    "dep:open-esp-radio-esp32s31-phy",
    "dep:open-esp-radio-esp32s31-wifi-mac",
    "dep:open-esp-radio-esp32s31-pac",
    "dep:static_cell",
]

[dependencies]
esp-hal = { git = "https://github.com/ermacv/esp-hal", branch = "esp32s31-async-platform", default-features = false, features = ["esp32s31", "unstable"], optional = true }
open-esp-radio-esp32s31-hal = { path = "../../../esp32s31/hal", optional = true }
open-esp-radio-esp32s31-phy = { path = "../../../esp32s31/phy", optional = true }
open-esp-radio-esp32s31-pac = { path = "../../../esp32s31/pac", optional = true }
open-esp-radio-esp32s31-wifi-mac = { path = "../../../esp32s31/wifi/mac", optional = true }
static_cell = { version = "2.1.1", optional = true }

[lints]
workspace = true
