[package]
name = "open-esp-radio-esp32s31-wifi-lmac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allocation-free source-owned ESP32-S31 Wi-Fi MAC primitives"

[features]
default = []
large-rx-pool-48 = []
rx-ba-window-8 = []

[dependencies]
open-esp-radio-esp32s31-registers = { path = "../../registers" }
open-esp-radio-ieee80211 = { path = "../../../wifi/ieee80211" }
open-esp-radio-wifi-lmac = { path = "../../../wifi/lmac" }
pin-project = "1.1.13"
vcell = "0.1.3"

[lints]
workspace = true
