[package]
name = "open-esp-radio-esp32s31-wifi-ap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Executor-independent ESP32-S31 Wi-Fi access-point composition"

[dependencies]
open-esp-radio-esp32s31-registers = { path = "../../registers" }
open-esp-radio-esp32s31-phy = { path = "../../phy" }
open-esp-radio-esp32s31-wifi = { path = ".." }
open-esp-radio-esp32s31-wifi-mac = { path = "../mac" }
open-esp-radio-ieee80211 = { path = "../../../../wifi/ieee80211" }
open-esp-radio-wifi-ap = { path = "../../../../wifi/ap" }
open-esp-radio-wifi-softmac = { path = "../../../../wifi/softmac" }
open-esp-radio-wpa2 = { path = "../../../../wifi/wpa2" }

[lints]
workspace = true
