[package]
name = "oer-esp32s31-example-access-point"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = ["owned-network"]
owned-network = ["dep:embassy-net-owned", "oer/owned-xarxa"]

[dependencies]
edge-dhcp = { version = "0.8.0", default-features = false }
embassy-net-owned = { package = "embassy-net", optional = true, git = "https://github.com/ermacv/embassy.git", rev = "4868fd9acfd4191173cd6531b537d6009d3ae5d0", features = ["icmp-ping-reply", "medium-ethernet", "ipv4", "ipv4-fragmentation", "ipv4-reassembly", "tcp", "tcp-listener", "udp"] }
embassy-time = "0.5.1"
static_cell = "2.1.1"

[target.'cfg(target_arch = "riscv32")'.dependencies]
oer-esp32s31-platform-runtime = { path = "../../../platform/esp32s31/runtime" }
embassy-executor = { version = "0.10.0", default-features = false }
embassy-futures = "0.1.2"
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "d61af210475ed9268806765d4940565371c75c80", default-features = false, features = ["esp32s31", "static-interrupts", "rt", "unstable"] }
esp-println = { git = "https://github.com/ermacv/esp-hal", rev = "d61af210475ed9268806765d4940565371c75c80", default-features = false, features = ["auto", "esp32s31", "log-04"] }
oer = { package = "open-esp-radio", path = "../../../crates/oer", default-features = false, features = ["wifi"] }
oer-esp32s31-executor-embassy = { path = "../../../crates/adapters/embassy/esp32s31/executor", features = ["esp32s31"] }

[build-dependencies]
oer-esp32s31-platform-layout = { path = "../../../platform/esp32s31/layout", features = ["build"] }

[dev-dependencies]
embassy-time = { version = "0.5.1", features = ["std"] }
critical-section = { version = "1.2.0", features = ["std"] }

[package.metadata.open-radio]
layer = "application"
platform = "chip"
chip = "esp32s31"

[lints]
workspace = true
