[package]
name = "open-esp-radio-wifi-ap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Executor- and chip-independent single-peer Wi-Fi access-point MLME"

[dependencies]
open-esp-radio-ieee80211 = { path = "../ieee80211" }
open-esp-radio-wpa2 = { path = "../wpa2" }

[lints]
workspace = true
