// @generated by `cargo registers` from the reviewed PAC API policy.
// Do not edit this file; edit the publication's API policy and run
// `cargo registers generate`.

/// The sole transmit-on delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154TxOnDelay {
    /// Literal ten-bit TXON_DELAY image written by ieee802154_txon_delay_set.
    Delay40 = 0x00000028,
}

impl Ieee802154TxOnDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// The sole transmit-off delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154TxOffDelay {
    /// Six-bit TXOFF_DELAY image cleared to zero by ieee802154_txon_delay_set.
    Delay0 = 0x00000000,
}

impl Ieee802154TxOffDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// The sole receive-on delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154RxOnDelay {
    /// Literal eleven-bit RXON_DELAY image written by ieee802154_txon_delay_set.
    Delay50 = 0x00000032,
}

impl Ieee802154RxOnDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// The sole transmit/receive turnaround delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154TxRxSwitchDelay {
    /// Literal ten-bit TXRX_SWITCH_DELAY image written by ieee802154_txon_delay_set.
    Delay122 = 0x0000007a,
}

impl Ieee802154TxRxSwitchDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Boolean state accepted by reviewed modem clock-gate transactions.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ModemClockGateState {
    /// The selected modem clock gate is disabled.
    Disabled = 0x00000000,
    /// The selected modem clock gate is enabled.
    Enabled = 0x00000001,
}

impl ModemClockGateState {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Boolean state accepted by reviewed modem reset transactions.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ModemResetState {
    /// The selected modem reset is released.
    Released = 0x00000000,
    /// The selected modem reset is asserted.
    Asserted = 0x00000001,
}

impl ModemResetState {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Rate bit phy_adc_rate_set copies into the baseband configuration word.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PhyRateBit {
    /// The rate bit is clear.
    Clear = 0x00000000,
    /// The rate bit is set.
    Set = 0x00000001,
}

impl PhyRateBit {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// RX IQ scale byte phy_rxiq_scale_set selects by phy_param byte 0x28A.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PhyRxIqScale {
    /// No scaling.
    Zero = 0x00000000,
    /// The byte -6.
    MinusSix = 0x000000fa,
}

impl PhyRxIqScale {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Power-detector initialization modes.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PhyPowerDetectorMode {
    /// phy_pwdet_reg_init.
    RegisterInitialization = 0x00000002,
    /// phy_pwdet_sar2_init.
    Sar2Initialization = 0x00000006,
}

impl PhyPowerDetectorMode {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// SAR2 power-detector capacitor codes the PHY selects.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PhySar2PowerDetectorCapacitor {
    /// phy_pwdet_sar2_init without IQ swap.
    Two = 0x00000002,
    /// phy_pwdet_reg_init, and phy_pwdet_sar2_init with IQ swap.
    Four = 0x00000004,
}

impl PhySar2PowerDetectorCapacitor {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// DAC scale byte phy_dac_scale_set selects.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PhyDacScale {
    /// Argument zero.
    Zero = 0x00000000,
    /// Nonzero argument.
    Full = 0x000000ff,
}

impl PhyDacScale {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// BBPLL calibration modes phy_bbpll_cal and phy_bbpll_recal select.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PhyBbpllCalibrationMode {
    /// phy_bbpll_cal with a zero argument.
    One = 0x00000001,
    /// phy_bbpll_cal with a nonzero argument, and phy_bbpll_recal before it.
    Two = 0x00000002,
}

impl PhyBbpllCalibrationMode {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// RX EVM control bits 2:0 phy_rxevm_init_cfg writes.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PhyRxEvmEnable {
    /// A zero first argument.
    Disabled = 0x00000000,
    /// A nonzero first argument.
    Enabled = 0x00000005,
}

impl PhyRxEvmEnable {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Sixteen-bit energy-detection duration subset accepted by the reviewed public IEEE 802.15.4 common LL setter; physical units remain outside the PAC.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154EdDurationUnits(u32);

impl Ieee802154EdDurationUnits {
    pub const MIN: u32 = 0x00000000;
    pub const MAX: u32 = 0x0000ffff;

    /// Construct a value only when it lies in the reviewed inclusive range.
    pub const fn new(value: u32) -> Option<Self> {
        if value <= 0x0000ffff {
            Some(Self(value))
        } else {
            None
        }
    }

    /// Return the checked numeric value.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Raw five-bit IEEE 802.15.4 transmit-power field accepted by the public common LL; no dBm conversion or calibration-table meaning is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154TxPowerCode(u32);

impl Ieee802154TxPowerCode {
    pub const MIN: u32 = 0x00000000;
    pub const MAX: u32 = 0x0000001f;

    /// Construct a value only when it lies in the reviewed inclusive range.
    pub const fn new(value: u32) -> Option<Self> {
        if value <= 0x0000001f {
            Some(Self(value))
        } else {
            None
        }
    }

    /// Return the checked numeric value.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Five-bit SDA side guard of an analog I2C host timing word.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PhyI2cSdaSideGuard(u32);

impl PhyI2cSdaSideGuard {
    pub const MIN: u32 = 0x00000000;
    pub const MAX: u32 = 0x0000001f;

    /// Construct a value only when it lies in the reviewed inclusive range.
    pub const fn new(value: u32) -> Option<Self> {
        if value <= 0x0000001f {
            Some(Self(value))
        } else {
            None
        }
    }

    /// Return the checked numeric value.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Six-bit SCL pulse duration of an analog I2C host timing word.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PhyI2cSclPulseDuration(u32);

impl PhyI2cSclPulseDuration {
    pub const MIN: u32 = 0x00000000;
    pub const MAX: u32 = 0x0000003f;

    /// Construct a value only when it lies in the reviewed inclusive range.
    pub const fn new(value: u32) -> Option<Self> {
        if value <= 0x0000003f {
            Some(Self(value))
        } else {
            None
        }
    }

    /// Return the checked numeric value.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Seven-bit RX EVM configuration parameter of phy_rxevm_init_cfg.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PhyRxEvmParameter(u32);

impl PhyRxEvmParameter {
    pub const MIN: u32 = 0x00000000;
    pub const MAX: u32 = 0x0000007f;

    /// Construct a value only when it lies in the reviewed inclusive range.
    pub const fn new(value: u32) -> Option<Self> {
        if value <= 0x0000007f {
            Some(Self(value))
        } else {
            None
        }
    }

    /// Return the checked numeric value.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER0 threshold word accepted by the public common LL; no clock source, unit, or deadline policy is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer0ThresholdWord(u32);

impl Ieee802154Timer0ThresholdWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER0 counter observation returned by the public common LL; no clock source or unit is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer0ValueWord(u32);

impl Ieee802154Timer0ValueWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER1 threshold word accepted by the public common LL; no clock source, unit, or deadline policy is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer1ThresholdWord(u32);

impl Ieee802154Timer1ThresholdWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER1 counter observation returned by the public common LL; no clock source or unit is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer1ValueWord(u32);

impl Ieee802154Timer1ValueWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete transmit frame-buffer address. Buffer provenance, alignment and lifetime remain HAL obligations.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154TxDmaAddress(u32);

impl Ieee802154TxDmaAddress {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete receive frame-buffer address. Buffer provenance, alignment and lifetime remain HAL obligations.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154RxDmaAddress(u32);

impl Ieee802154RxDmaAddress {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Typed bridge for the reviewed `publish_ieee802154_tx_dma_address` complete-register transaction.
#[inline]
pub(crate) fn publish_ieee802154_tx_dma_address(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxDmaAddress,
) {
    crate::svd::full_register_write::publish_ieee802154_tx_dma_address(registers, value.get());
}

/// Typed bridge for the reviewed `publish_ieee802154_rx_dma_address` complete-register transaction.
#[inline]
pub(crate) fn publish_ieee802154_rx_dma_address(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154RxDmaAddress,
) {
    crate::svd::full_register_write::publish_ieee802154_rx_dma_address(registers, value.get());
}

/// Typed bridge for the reviewed `set_ieee802154_ed_duration` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_ed_duration(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154EdDurationUnits,
) {
    crate::svd::masked_register_modify::set_ieee802154_ed_duration(registers, value.get());
}

/// Typed bridge for the reviewed `set_ieee802154_tx_power_code` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_tx_power_code(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxPowerCode,
) {
    crate::svd::masked_register_modify::set_ieee802154_tx_power_code(registers, value.get());
}

/// Typed bridge for the reviewed `set_ieee802154_tx_on_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_tx_on_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxOnDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_tx_on_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_tx_off_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_tx_off_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxOffDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_tx_off_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_rx_on_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_rx_on_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154RxOnDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_rx_on_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_txrx_switch_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_txrx_switch_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxRxSwitchDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_txrx_switch_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `enable_ieee802154_etm_channel0` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_ieee802154_etm_channel0(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::enable_ieee802154_etm_channel0(registers);
}

/// Typed bridge for the reviewed `enable_ieee802154_etm_channel1` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_ieee802154_etm_channel1(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::enable_ieee802154_etm_channel1(registers);
}

/// Typed bridge for the reviewed `disable_ieee802154_etm_channel0` fixed field-OR transaction.
#[inline]
pub(crate) fn disable_ieee802154_etm_channel0(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::disable_ieee802154_etm_channel0(registers);
}

/// Typed bridge for the reviewed `disable_ieee802154_etm_channel1` fixed field-OR transaction.
#[inline]
pub(crate) fn disable_ieee802154_etm_channel1(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::disable_ieee802154_etm_channel1(registers);
}

/// Typed bridge for the reviewed `power_rf_analog_i2c` fixed field-OR transaction.
#[inline]
pub(crate) fn power_rf_analog_i2c(registers: &crate::svd::PmuRadio) {
    crate::svd::field_or_modify::power_rf_analog_i2c(registers);
}

/// Typed bridge for the reviewed `tie_high_bb_analog_i2c_power` fixed field-OR transaction.
#[inline]
pub(crate) fn tie_high_bb_analog_i2c_power(registers: &crate::svd::PmuRadio) {
    crate::svd::field_or_modify::tie_high_bb_analog_i2c_power(registers);
}

/// Typed bridge for the reviewed `power_peripheral_analog_i2c` fixed field-OR transaction.
#[inline]
pub(crate) fn power_peripheral_analog_i2c(registers: &crate::svd::PmuRadio) {
    crate::svd::field_or_modify::power_peripheral_analog_i2c(registers);
}

/// Typed bridge for the reviewed `release_peripheral_analog_i2c_reset` fixed field-OR transaction.
#[inline]
pub(crate) fn release_peripheral_analog_i2c_reset(registers: &crate::svd::PmuRadio) {
    crate::svd::field_or_modify::release_peripheral_analog_i2c_reset(registers);
}

/// Typed bridge for the reviewed `power_5g_clock_generator` fixed field-OR transaction.
#[inline]
pub(crate) fn power_5g_clock_generator(registers: &crate::svd::PmuRadio) {
    crate::svd::field_or_modify::power_5g_clock_generator(registers);
}

/// Typed bridge for the reviewed `open_phy_fe_bb_clock` fixed field-OR transaction.
#[inline]
pub(crate) fn open_phy_fe_bb_clock(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::open_phy_fe_bb_clock(registers);
}

/// Typed bridge for the reviewed `enable_phy_i2c_master_registers` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_phy_i2c_master_registers(registers: &crate::svd::I2cAnaMst) {
    crate::svd::field_or_modify::enable_phy_i2c_master_registers(registers);
}

/// Typed bridge for the reviewed `set_phy_front_end_init_0c08` fixed field-OR transaction.
#[inline]
pub(crate) fn set_phy_front_end_init_0c08(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::set_phy_front_end_init_0c08(registers);
}

/// Typed bridge for the reviewed `enable_phy_front_end_0894` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_phy_front_end_0894(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::enable_phy_front_end_0894(registers);
}

/// Typed bridge for the reviewed `enable_phy_front_end_init` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_phy_front_end_init(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::enable_phy_front_end_init(registers);
}

/// Typed bridge for the reviewed `set_phy_rx_iq_correction_modes` fixed field-OR transaction.
#[inline]
pub(crate) fn set_phy_rx_iq_correction_modes(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::set_phy_rx_iq_correction_modes(registers);
}

/// Typed bridge for the reviewed `set_phy_tx_iq_correction_modes` fixed field-OR transaction.
#[inline]
pub(crate) fn set_phy_tx_iq_correction_modes(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::set_phy_tx_iq_correction_modes(registers);
}

/// Typed bridge for the reviewed `set_phy_front_end_iq_swap` fixed field-OR transaction.
#[inline]
pub(crate) fn set_phy_front_end_iq_swap(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::set_phy_front_end_iq_swap(registers);
}

/// Typed bridge for the reviewed `drive_saradc2_from_power_detector` fixed field-OR transaction.
#[inline]
pub(crate) fn drive_saradc2_from_power_detector(registers: &crate::svd::ApbSaradcRadio) {
    crate::svd::field_or_modify::drive_saradc2_from_power_detector(registers);
}

/// Typed bridge for the reviewed `set_phy_power_detector_sar_mode` fixed field-OR transaction.
#[inline]
pub(crate) fn set_phy_power_detector_sar_mode(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::set_phy_power_detector_sar_mode(registers);
}

/// Typed bridge for the reviewed `enable_saradc_register_clock` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_saradc_register_clock(registers: &crate::svd::PcrRadio) {
    crate::svd::field_or_modify::enable_saradc_register_clock(registers);
}

/// Typed bridge for the reviewed `enable_saradc_clocks` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_saradc_clocks(registers: &crate::svd::PcrRadio) {
    crate::svd::field_or_modify::enable_saradc_clocks(registers);
}

/// Typed bridge for the reviewed `enable_tsens_clock` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_tsens_clock(registers: &crate::svd::PcrRadio) {
    crate::svd::field_or_modify::enable_tsens_clock(registers);
}

/// Typed bridge for the reviewed `select_tsens_clock` fixed field-OR transaction.
#[inline]
pub(crate) fn select_tsens_clock(registers: &crate::svd::ApbSaradcRadio) {
    crate::svd::field_or_modify::select_tsens_clock(registers);
}

/// Typed bridge for the reviewed `assert_phy_rx_evm_memory_reset` fixed field-OR transaction.
#[inline]
pub(crate) fn assert_phy_rx_evm_memory_reset(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::assert_phy_rx_evm_memory_reset(registers);
}

/// Typed bridge for the reviewed `assert_phy_rx_evm_memory_reset_2` fixed field-OR transaction.
#[inline]
pub(crate) fn assert_phy_rx_evm_memory_reset_2(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_or_modify::assert_phy_rx_evm_memory_reset_2(registers);
}

/// Typed bridge for the reviewed `set_ieee802154_apb_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_apb_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_ieee802154_apb_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_mac_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_mac_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_ieee802154_mac_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_etm_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_etm_clock(registers: &crate::svd::ModemSysconRadio, value: ModemClockGateState) {
    crate::svd::field_replace_modify::set_etm_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_modem_security_apb_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_modem_security_apb_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_modem_security_apb_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_bluetooth_apb_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_bluetooth_apb_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_bluetooth_apb_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_bluetooth_ieee802154_baseband_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_bluetooth_ieee802154_baseband_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_bluetooth_ieee802154_baseband_clock(
        registers,
        value.bits(),
    );
}

/// Typed bridge for the reviewed `set_ieee802154_mac_reset` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_mac_reset(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemResetState,
) {
    crate::svd::field_replace_modify::set_ieee802154_mac_reset(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_apb_reset` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_apb_reset(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemResetState,
) {
    crate::svd::field_replace_modify::set_ieee802154_apb_reset(registers, value.bits());
}

/// Typed bridge for the reviewed `set_coexistence_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_coexistence_clock(
    registers: &crate::svd::ModemLpconSharedClock,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_coexistence_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `configure_phy_i2c_host_map` fixed field-replacement transaction.
#[inline]
pub(crate) fn configure_phy_i2c_host_map(registers: &crate::svd::I2cAnaMst) {
    crate::svd::field_replace_modify::configure_phy_i2c_host_map(registers);
}

/// Typed bridge for the reviewed `configure_phy_i2c_parallel_host_map` fixed field-replacement transaction.
#[inline]
pub(crate) fn configure_phy_i2c_parallel_host_map(registers: &crate::svd::I2cAnaMst) {
    crate::svd::field_replace_modify::configure_phy_i2c_parallel_host_map(registers);
}

/// Typed bridge for the reviewed `hold_peripheral_analog_i2c_reset` fixed field-replacement transaction.
#[inline]
pub(crate) fn hold_peripheral_analog_i2c_reset(registers: &crate::svd::PmuRadio) {
    crate::svd::field_replace_modify::hold_peripheral_analog_i2c_reset(registers);
}

/// Typed bridge for the reviewed `set_phy_i2c_host0_sda_side_guard` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_host0_sda_side_guard(
    registers: &crate::svd::I2cAnaMst,
    value: PhyI2cSdaSideGuard,
) {
    crate::svd::field_replace_modify::set_phy_i2c_host0_sda_side_guard(registers, value.get());
}

/// Typed bridge for the reviewed `set_phy_i2c_host0_scl_pulse_duration` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_host0_scl_pulse_duration(
    registers: &crate::svd::I2cAnaMst,
    value: PhyI2cSclPulseDuration,
) {
    crate::svd::field_replace_modify::set_phy_i2c_host0_scl_pulse_duration(registers, value.get());
}

/// Typed bridge for the reviewed `set_phy_i2c_host1_sda_side_guard` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_host1_sda_side_guard(
    registers: &crate::svd::I2cAnaMst,
    value: PhyI2cSdaSideGuard,
) {
    crate::svd::field_replace_modify::set_phy_i2c_host1_sda_side_guard(registers, value.get());
}

/// Typed bridge for the reviewed `set_phy_i2c_host1_scl_pulse_duration` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_host1_scl_pulse_duration(
    registers: &crate::svd::I2cAnaMst,
    value: PhyI2cSclPulseDuration,
) {
    crate::svd::field_replace_modify::set_phy_i2c_host1_scl_pulse_duration(registers, value.get());
}

/// Typed bridge for the reviewed `set_phy_i2c_hardware_host_sda_side_guard` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_hardware_host_sda_side_guard(
    registers: &crate::svd::I2cAnaMst,
    value: PhyI2cSdaSideGuard,
) {
    crate::svd::field_replace_modify::set_phy_i2c_hardware_host_sda_side_guard(
        registers,
        value.get(),
    );
}

/// Typed bridge for the reviewed `set_phy_i2c_hardware_host_scl_pulse_duration` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_hardware_host_scl_pulse_duration(
    registers: &crate::svd::I2cAnaMst,
    value: PhyI2cSclPulseDuration,
) {
    crate::svd::field_replace_modify::set_phy_i2c_hardware_host_scl_pulse_duration(
        registers,
        value.get(),
    );
}

/// Typed bridge for the reviewed `set_phy_adc_rate_high` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_adc_rate_high(registers: &crate::svd::PhyBasebandConfig, value: PhyRateBit) {
    crate::svd::field_replace_modify::set_phy_adc_rate_high(registers, value.bits());
}

/// Typed bridge for the reviewed `set_phy_adc_rate_low` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_adc_rate_low(registers: &crate::svd::PhyBasebandConfig, value: PhyRateBit) {
    crate::svd::field_replace_modify::set_phy_adc_rate_low(registers, value.bits());
}

/// Typed bridge for the reviewed `clear_phy_dac_rate_high` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_dac_rate_high(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_dac_rate_high(registers);
}

/// Typed bridge for the reviewed `clear_phy_dac_rate_low` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_dac_rate_low(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_dac_rate_low(registers);
}

/// Typed bridge for the reviewed `set_phy_i2c_master_register_mode` fixed field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_master_register_mode(registers: &crate::svd::I2cAnaMst) {
    crate::svd::field_replace_modify::set_phy_i2c_master_register_mode(registers);
}

/// Typed bridge for the reviewed `clear_phy_front_end_init_0c08_first` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_front_end_init_0c08_first(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_front_end_init_0c08_first(registers);
}

/// Typed bridge for the reviewed `clear_phy_rx_dco_calibration_control` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_rx_dco_calibration_control(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_rx_dco_calibration_control(registers);
}

/// Typed bridge for the reviewed `clear_phy_front_end_clear_first` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_front_end_clear_first(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_front_end_clear_first(registers);
}

/// Typed bridge for the reviewed `set_phy_table_memory_base_index` fixed field-replacement transaction.
#[inline]
pub(crate) fn set_phy_table_memory_base_index(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::set_phy_table_memory_base_index(registers);
}

/// Typed bridge for the reviewed `set_phy_rx_iq_scale_high` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_rx_iq_scale_high(
    registers: &crate::svd::PhyBasebandConfig,
    value: PhyRxIqScale,
) {
    crate::svd::field_replace_modify::set_phy_rx_iq_scale_high(registers, value.bits());
}

/// Typed bridge for the reviewed `set_phy_rx_iq_scale_low` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_rx_iq_scale_low(
    registers: &crate::svd::PhyBasebandConfig,
    value: PhyRxIqScale,
) {
    crate::svd::field_replace_modify::set_phy_rx_iq_scale_low(registers, value.bits());
}

/// Typed bridge for the reviewed `clear_phy_front_end_iq_swap` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_front_end_iq_swap(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_front_end_iq_swap(registers);
}

/// Typed bridge for the reviewed `set_phy_front_end_init_0c20` fixed field-replacement transaction.
#[inline]
pub(crate) fn set_phy_front_end_init_0c20(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::set_phy_front_end_init_0c20(registers);
}

/// Typed bridge for the reviewed `set_phy_pa_on_bt_delay` fixed field-replacement transaction.
#[inline]
pub(crate) fn set_phy_pa_on_bt_delay(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::set_phy_pa_on_bt_delay(registers);
}

/// Typed bridge for the reviewed `set_phy_power_detector_calibration_field` fixed field-replacement transaction.
#[inline]
pub(crate) fn set_phy_power_detector_calibration_field(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::set_phy_power_detector_calibration_field(registers);
}

/// Typed bridge for the reviewed `set_phy_power_detector_mode` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_power_detector_mode(
    registers: &crate::svd::PhyBasebandConfig,
    value: PhyPowerDetectorMode,
) {
    crate::svd::field_replace_modify::set_phy_power_detector_mode(registers, value.bits());
}

/// Typed bridge for the reviewed `set_sar2_power_detector_capacitor` field-replacement transaction.
#[inline]
pub(crate) fn set_sar2_power_detector_capacitor(
    registers: &crate::svd::LpAonRadio,
    value: PhySar2PowerDetectorCapacitor,
) {
    crate::svd::field_replace_modify::set_sar2_power_detector_capacitor(registers, value.bits());
}

/// Typed bridge for the reviewed `set_phy_dac_scale_high` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_dac_scale_high(
    registers: &crate::svd::PhyBasebandConfig,
    value: PhyDacScale,
) {
    crate::svd::field_replace_modify::set_phy_dac_scale_high(registers, value.bits());
}

/// Typed bridge for the reviewed `set_phy_dac_scale_low` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_dac_scale_low(registers: &crate::svd::PhyBasebandConfig, value: PhyDacScale) {
    crate::svd::field_replace_modify::set_phy_dac_scale_low(registers, value.bits());
}

/// Typed bridge for the reviewed `clear_phy_power_detector_sar_config` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_power_detector_sar_config(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_power_detector_sar_config(registers);
}

/// Typed bridge for the reviewed `set_pcr_register_014c_low_byte` fixed field-replacement transaction.
#[inline]
pub(crate) fn set_pcr_register_014c_low_byte(registers: &crate::svd::PcrRadio) {
    crate::svd::field_replace_modify::set_pcr_register_014c_low_byte(registers);
}

/// Typed bridge for the reviewed `release_tsens_reset` fixed field-replacement transaction.
#[inline]
pub(crate) fn release_tsens_reset(registers: &crate::svd::PcrRadio) {
    crate::svd::field_replace_modify::release_tsens_reset(registers);
}

/// Typed bridge for the reviewed `set_tsens_power` field-replacement transaction.
#[inline]
pub(crate) fn set_tsens_power(registers: &crate::svd::ApbSaradcRadio, value: PhyRateBit) {
    crate::svd::field_replace_modify::set_tsens_power(registers, value.bits());
}

/// Typed bridge for the reviewed `set_phy_i2c_bbpll_calibration_mode` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_i2c_bbpll_calibration_mode(
    registers: &crate::svd::I2cAnaMst,
    value: PhyBbpllCalibrationMode,
) {
    crate::svd::field_replace_modify::set_phy_i2c_bbpll_calibration_mode(registers, value.bits());
}

/// Typed bridge for the reviewed `set_phy_rx_evm_mode` fixed field-replacement transaction.
#[inline]
pub(crate) fn set_phy_rx_evm_mode(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::set_phy_rx_evm_mode(registers);
}

/// Typed bridge for the reviewed `set_phy_rx_evm_third_parameter` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_rx_evm_third_parameter(
    registers: &crate::svd::PhyBasebandConfig,
    value: PhyRxEvmParameter,
) {
    crate::svd::field_replace_modify::set_phy_rx_evm_third_parameter(registers, value.get());
}

/// Typed bridge for the reviewed `set_phy_rx_evm_second_parameter` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_rx_evm_second_parameter(
    registers: &crate::svd::PhyBasebandConfig,
    value: PhyRxEvmParameter,
) {
    crate::svd::field_replace_modify::set_phy_rx_evm_second_parameter(registers, value.get());
}

/// Typed bridge for the reviewed `set_phy_rx_evm_enable` field-replacement transaction.
#[inline]
pub(crate) fn set_phy_rx_evm_enable(
    registers: &crate::svd::PhyBasebandConfig,
    value: PhyRxEvmEnable,
) {
    crate::svd::field_replace_modify::set_phy_rx_evm_enable(registers, value.bits());
}

/// Typed bridge for the reviewed `clear_phy_rx_evm_word_7920` fixed field-replacement transaction.
#[inline]
pub(crate) fn clear_phy_rx_evm_word_7920(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::clear_phy_rx_evm_word_7920(registers);
}

/// Typed bridge for the reviewed `release_phy_rx_evm_memory_reset` fixed field-replacement transaction.
#[inline]
pub(crate) fn release_phy_rx_evm_memory_reset(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::release_phy_rx_evm_memory_reset(registers);
}

/// Typed bridge for the reviewed `release_phy_rx_evm_memory_reset_2` fixed field-replacement transaction.
#[inline]
pub(crate) fn release_phy_rx_evm_memory_reset_2(registers: &crate::svd::PhyBasebandConfig) {
    crate::svd::field_replace_modify::release_phy_rx_evm_memory_reset_2(registers);
}
