// @generated by `cargo registers` from the reviewed PAC API policy.
// Do not edit this file; edit the publication's API policy and run
// `cargo registers generate`.

/// The sole transmit-on delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154TxOnDelay {
    /// Literal ten-bit TXON_DELAY image written by ieee802154_txon_delay_set.
    Delay40 = 0x00000028,
}

impl Ieee802154TxOnDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// The sole transmit-off delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154TxOffDelay {
    /// Six-bit TXOFF_DELAY image cleared to zero by ieee802154_txon_delay_set.
    Delay0 = 0x00000000,
}

impl Ieee802154TxOffDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// The sole receive-on delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154RxOnDelay {
    /// Literal eleven-bit RXON_DELAY image written by ieee802154_txon_delay_set.
    Delay50 = 0x00000032,
}

impl Ieee802154RxOnDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// The sole transmit/receive turnaround delay image accepted by the pinned ESP32-C5 IEEE 802.15.4 MAC initialization (ieee802154_txon_delay_set).
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Ieee802154TxRxSwitchDelay {
    /// Literal ten-bit TXRX_SWITCH_DELAY image written by ieee802154_txon_delay_set.
    Delay122 = 0x0000007a,
}

impl Ieee802154TxRxSwitchDelay {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Boolean state accepted by reviewed modem clock-gate transactions.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ModemClockGateState {
    /// The selected modem clock gate is disabled.
    Disabled = 0x00000000,
    /// The selected modem clock gate is enabled.
    Enabled = 0x00000001,
}

impl ModemClockGateState {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Boolean state accepted by reviewed modem reset transactions.
#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ModemResetState {
    /// The selected modem reset is released.
    Released = 0x00000000,
    /// The selected modem reset is asserted.
    Asserted = 0x00000001,
}

impl ModemResetState {
    /// Numeric image for diagnostics and the private raw-PAC bridge.
    pub const fn bits(self) -> u32 {
        self as u32
    }
}

/// Sixteen-bit energy-detection duration subset accepted by the reviewed public IEEE 802.15.4 common LL setter; physical units remain outside the PAC.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154EdDurationUnits(u32);

impl Ieee802154EdDurationUnits {
    pub const MIN: u32 = 0x00000000;
    pub const MAX: u32 = 0x0000ffff;

    /// Construct a value only when it lies in the reviewed inclusive range.
    pub const fn new(value: u32) -> Option<Self> {
        if value <= 0x0000ffff {
            Some(Self(value))
        } else {
            None
        }
    }

    /// Return the checked numeric value.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Raw five-bit IEEE 802.15.4 transmit-power field accepted by the public common LL; no dBm conversion or calibration-table meaning is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154TxPowerCode(u32);

impl Ieee802154TxPowerCode {
    pub const MIN: u32 = 0x00000000;
    pub const MAX: u32 = 0x0000001f;

    /// Construct a value only when it lies in the reviewed inclusive range.
    pub const fn new(value: u32) -> Option<Self> {
        if value <= 0x0000001f {
            Some(Self(value))
        } else {
            None
        }
    }

    /// Return the checked numeric value.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER0 threshold word accepted by the public common LL; no clock source, unit, or deadline policy is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer0ThresholdWord(u32);

impl Ieee802154Timer0ThresholdWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER0 counter observation returned by the public common LL; no clock source or unit is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer0ValueWord(u32);

impl Ieee802154Timer0ValueWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER1 threshold word accepted by the public common LL; no clock source, unit, or deadline policy is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer1ThresholdWord(u32);

impl Ieee802154Timer1ThresholdWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete TIMER1 counter observation returned by the public common LL; no clock source or unit is assigned at the PAC boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154Timer1ValueWord(u32);

impl Ieee802154Timer1ValueWord {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete transmit frame-buffer address. Buffer provenance, alignment and lifetime remain HAL obligations.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154TxDmaAddress(u32);

impl Ieee802154TxDmaAddress {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Register-specific complete receive frame-buffer address. Buffer provenance, alignment and lifetime remain HAL obligations.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Ieee802154RxDmaAddress(u32);

impl Ieee802154RxDmaAddress {
    /// Wrap one register-specific opaque value.
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Return the opaque numeric image.
    pub const fn get(self) -> u32 {
        self.0
    }
}

/// Typed bridge for the reviewed `publish_ieee802154_tx_dma_address` complete-register transaction.
#[inline]
pub(crate) fn publish_ieee802154_tx_dma_address(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxDmaAddress,
) {
    crate::svd::full_register_write::publish_ieee802154_tx_dma_address(registers, value.get());
}

/// Typed bridge for the reviewed `publish_ieee802154_rx_dma_address` complete-register transaction.
#[inline]
pub(crate) fn publish_ieee802154_rx_dma_address(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154RxDmaAddress,
) {
    crate::svd::full_register_write::publish_ieee802154_rx_dma_address(registers, value.get());
}

/// Typed bridge for the reviewed `set_ieee802154_ed_duration` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_ed_duration(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154EdDurationUnits,
) {
    crate::svd::masked_register_modify::set_ieee802154_ed_duration(registers, value.get());
}

/// Typed bridge for the reviewed `set_ieee802154_tx_power_code` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_tx_power_code(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxPowerCode,
) {
    crate::svd::masked_register_modify::set_ieee802154_tx_power_code(registers, value.get());
}

/// Typed bridge for the reviewed `set_ieee802154_tx_on_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_tx_on_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxOnDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_tx_on_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_tx_off_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_tx_off_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxOffDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_tx_off_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_rx_on_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_rx_on_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154RxOnDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_rx_on_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_txrx_switch_delay` masked transaction.
#[inline]
pub(crate) fn set_ieee802154_txrx_switch_delay(
    registers: &crate::svd::Ieee802154Mac,
    value: Ieee802154TxRxSwitchDelay,
) {
    crate::svd::masked_register_modify::set_ieee802154_txrx_switch_delay(registers, value.bits());
}

/// Typed bridge for the reviewed `enable_ieee802154_etm_channel0` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_ieee802154_etm_channel0(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::enable_ieee802154_etm_channel0(registers);
}

/// Typed bridge for the reviewed `enable_ieee802154_etm_channel1` fixed field-OR transaction.
#[inline]
pub(crate) fn enable_ieee802154_etm_channel1(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::enable_ieee802154_etm_channel1(registers);
}

/// Typed bridge for the reviewed `disable_ieee802154_etm_channel0` fixed field-OR transaction.
#[inline]
pub(crate) fn disable_ieee802154_etm_channel0(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::disable_ieee802154_etm_channel0(registers);
}

/// Typed bridge for the reviewed `disable_ieee802154_etm_channel1` fixed field-OR transaction.
#[inline]
pub(crate) fn disable_ieee802154_etm_channel1(registers: &crate::svd::ModemEtm) {
    crate::svd::field_or_modify::disable_ieee802154_etm_channel1(registers);
}

/// Typed bridge for the reviewed `set_ieee802154_apb_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_apb_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_ieee802154_apb_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_mac_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_mac_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_ieee802154_mac_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_etm_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_etm_clock(registers: &crate::svd::ModemSysconRadio, value: ModemClockGateState) {
    crate::svd::field_replace_modify::set_etm_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_modem_security_apb_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_modem_security_apb_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_modem_security_apb_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_bluetooth_apb_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_bluetooth_apb_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_bluetooth_apb_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `set_bluetooth_ieee802154_baseband_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_bluetooth_ieee802154_baseband_clock(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_bluetooth_ieee802154_baseband_clock(
        registers,
        value.bits(),
    );
}

/// Typed bridge for the reviewed `set_ieee802154_mac_reset` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_mac_reset(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemResetState,
) {
    crate::svd::field_replace_modify::set_ieee802154_mac_reset(registers, value.bits());
}

/// Typed bridge for the reviewed `set_ieee802154_apb_reset` field-replacement transaction.
#[inline]
pub(crate) fn set_ieee802154_apb_reset(
    registers: &crate::svd::ModemSysconRadio,
    value: ModemResetState,
) {
    crate::svd::field_replace_modify::set_ieee802154_apb_reset(registers, value.bits());
}

/// Typed bridge for the reviewed `set_coexistence_clock` field-replacement transaction.
#[inline]
pub(crate) fn set_coexistence_clock(
    registers: &crate::svd::ModemLpconSharedClock,
    value: ModemClockGateState,
) {
    crate::svd::field_replace_modify::set_coexistence_clock(registers, value.bits());
}

/// Typed bridge for the reviewed `configure_phy_i2c_host_map` fixed field-replacement transaction.
#[inline]
pub(crate) fn configure_phy_i2c_host_map(registers: &crate::svd::I2cAnaMst) {
    crate::svd::field_replace_modify::configure_phy_i2c_host_map(registers);
}

/// Typed bridge for the reviewed `configure_phy_i2c_parallel_host_map` fixed field-replacement transaction.
#[inline]
pub(crate) fn configure_phy_i2c_parallel_host_map(registers: &crate::svd::I2cAnaMst) {
    crate::svd::field_replace_modify::configure_phy_i2c_parallel_host_map(registers);
}
