[package]
name = "open-esp-radio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Application facade for the source-only Rust ESP radio stack"

[features]
default = ["esp32s31"]
esp32s31 = [
    "dep:open-esp-radio-hal-esp32s31",
    "dep:open-esp-radio-mac-esp32s31",
    "dep:open-esp-radio-pac-esp32s31",
    "dep:open-esp-radio-phy-esp32s31",
]

[dependencies]
open-esp-radio-hal-esp32s31 = { path = "../open-esp-radio-hal-esp32s31", optional = true }
open-esp-radio-ieee80211 = { path = "../open-esp-radio-ieee80211" }
open-esp-radio-mac-esp32s31 = { path = "../open-esp-radio-mac-esp32s31", optional = true }
open-esp-radio-pac-esp32s31 = { path = "../open-esp-radio-pac-esp32s31", optional = true }
open-esp-radio-phy-esp32s31 = { path = "../open-esp-radio-phy-esp32s31", optional = true }
open-esp-radio-wpa2 = { path = "../open-esp-radio-wpa2" }

[lints]
workspace = true
