[package]
name = "oer-esp32s31-radio-platform-esp-hal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP-HAL ownership coordinator for ESP32-S31 radio platform resources"
readme = "README.md"

[features]
default = []
esp32s31 = ["dep:esp-hal"]

[dependencies]
critical-section = "1.2.0"
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "bee3369c35dfc10048b1d524150d99869f8a4352", default-features = false, features = ["esp32s31", "unstable"], optional = true }
oer-bluetooth-hci = { path = "../../../../protocols/bluetooth/hci" }
oer-esp32s31-bluetooth = { path = "../../../../hardware/esp32s31/driver/bluetooth" }
oer-esp32s31-hal = { path = "../../../../hardware/esp32s31/hal" }
oer-esp32s31-phy = { path = "../../../../hardware/esp32s31/phy" }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }

[lints]
workspace = true

[package.metadata.open-radio]
scope = "production"
layer = "adapter"
platform = "chip"
chip = "esp32s31"
