[package]
name = "oer-esp32s31-example-monitor"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
oer-esp32s31-platform-runtime = { path = "../../../platform/esp32s31/runtime" }
embassy-executor = { version = "0.10.0", default-features = false }
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "42b085e245a67e4a845237520f19704cbdb22776", default-features = false, features = ["esp32s31", "rt", "unstable"] }
esp-println = { git = "https://github.com/ermacv/esp-hal", rev = "42b085e245a67e4a845237520f19704cbdb22776", default-features = false, features = ["auto", "esp32s31", "log-04"] }
oer = { package = "open-esp-radio", path = "../../../crates/oer", default-features = false, features = ["owned-xarxa"] }
oer-esp32s31-executor-embassy = { path = "../../../crates/adapters/embassy/esp32s31/executor", features = ["esp32s31"] }
static_cell = "2.1.1"

[build-dependencies]
oer-esp32s31-platform-layout = { path = "../../../platform/esp32s31/layout", features = ["build"] }

[package.metadata.open-radio]
layer = "application"
platform = "chip"
chip = "esp32s31"

[lints]
workspace = true
