[package]
name = "open-esp-radio-hal-esp32s31"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Ownership and async HAL boundaries for the ESP32-S31 radio"

[dependencies]
open-esp-radio-pac-esp32s31 = { path = "../open-esp-radio-pac-esp32s31" }

[lints]
workspace = true
