//! Rust rendering for validated safe PAC transaction declarations.

use std::collections::BTreeSet;

use svd_rs::{Device, MaybeArray};

use crate::{Error, PacApiPack, Result, pac_api_svd};

impl PacApiPack {
    /// Render public value domains for inclusion in the closed PAC crate.
    ///
    /// This output deliberately contains no register addresses, raw PAC
    /// types, pointers, or public integer constructors. Target-owned
    /// capability methods consume these values and keep `bits()` inside the
    /// closed PAC crate.
    pub fn render_facade_rust(&self) -> Result<String> {
        self.validate()?;
        let mut output = String::from(
            "// @generated by blobray from the reviewed PAC API pack.\n\
             // Do not edit this file; edit registers/api.toml and run project publish.\n\n",
        );
        for domain in &self.flag_domains {
            push_doc(&mut output, &domain.description, "");
            output.push_str(&format!(
                "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\n\
                 pub struct {}(u32);\n\n\
                 impl {} {{\n",
                domain.name, domain.name,
            ));
            for value in &domain.values {
                push_doc(&mut output, &value.description, "    ");
                output.push_str(&format!(
                    "    pub const {}: Self = Self(0x{:08x});\n",
                    value.name, value.value,
                ));
            }
            output.push_str(
                "\n    /// Combine reviewed writable values.\n\
                     pub const fn union(self, other: Self) -> Self { Self(self.0 | other.0) }\n\n\
                     /// Test whether all bits in `other` are present.\n\
                     pub const fn contains(self, other: Self) -> bool {\n\
                         self.0 & other.0 == other.0\n\
                     }\n\n\
                     /// Read-only numeric image for diagnostics and the private raw-PAC bridge.\n\
                     /// There is intentionally no inverse integer constructor.\n\
                     pub const fn bits(self) -> u32 { self.0 }\n\
                 }\n\n",
            );
            output.push_str(&format!(
                "impl core::ops::BitOr for {} {{\n\
                     type Output = Self;\n\n\
                     fn bitor(self, rhs: Self) -> Self::Output {{ self.union(rhs) }}\n\
                 }}\n\n",
                domain.name,
            ));
        }
        for domain in &self.enum_domains {
            push_doc(&mut output, &domain.description, "");
            output.push_str(&format!(
                "#[repr(u32)]\n#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\npub enum {} {{\n",
                domain.name,
            ));
            for value in &domain.values {
                push_doc(&mut output, &value.description, "    ");
                output.push_str(&format!("    {} = 0x{:08x},\n", value.name, value.value,));
            }
            output.push_str(&format!(
                "}}\n\nimpl {} {{\n    /// Numeric image for diagnostics and the private raw-PAC bridge.\n    pub const fn bits(self) -> u32 {{ self as u32 }}\n}}\n\n",
                domain.name,
            ));
        }
        for domain in &self.bounded_domains {
            push_doc(&mut output, &domain.description, "");
            let constructor = match (domain.min, domain.max) {
                (0, u32::MAX) => "        Some(Self(value))\n".to_owned(),
                (0, max) => format!(
                    "        if value <= 0x{max:08x} {{ Some(Self(value)) }} else {{ None }}\n"
                ),
                (min, u32::MAX) => format!(
                    "        if value >= 0x{min:08x} {{ Some(Self(value)) }} else {{ None }}\n"
                ),
                (min, max) => format!(
                    "        if value >= 0x{min:08x} && value <= 0x{max:08x} {{ Some(Self(value)) }} else {{ None }}\n"
                ),
            };
            output.push_str(&format!(
                "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\npub struct {}(u32);\n\nimpl {} {{\n    pub const MIN: u32 = 0x{:08x};\n    pub const MAX: u32 = 0x{:08x};\n\n    /// Construct a value only when it lies in the reviewed inclusive range.\n    pub const fn new(value: u32) -> Option<Self> {{\n{}    }}\n\n    /// Return the checked numeric value.\n    pub const fn get(self) -> u32 {{ self.0 }}\n}}\n\n",
                domain.name, domain.name, domain.min, domain.max, constructor,
            ));
        }
        for domain in &self.opaque_domains {
            push_doc(&mut output, &domain.description, "");
            output.push_str(&format!(
                "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\npub struct {}(u32);\n\nimpl {} {{\n    /// Wrap one register-specific opaque value.\n    pub const fn new(value: u32) -> Self {{ Self(value) }}\n\n    /// Return the opaque numeric image.\n    pub const fn get(self) -> u32 {{ self.0 }}\n}}\n\n",
                domain.name, domain.name,
            ));
        }
        for domain in &self.bitwise_composed_domains {
            push_doc(&mut output, &domain.description, "");
            let parameters = domain
                .arguments
                .iter()
                .map(|argument| format!("{}: {}", argument.name, argument.value_type.rust_name()))
                .collect::<Vec<_>>()
                .join(", ");
            let composition = domain
                .arguments
                .iter()
                .map(|argument| {
                    let value = if argument.value_type.requires_u32_cast() {
                        format!("{} as u32", argument.name)
                    } else {
                        argument.name.clone()
                    };
                    if argument.left_shift == 0 {
                        format!("({value})")
                    } else {
                        format!("(({value}) << {})", argument.left_shift)
                    }
                })
                .collect::<Vec<_>>()
                .join(" | ");
            output.push_str(&format!(
                "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\npub struct {}(u32);\n\nimpl {} {{\n    /// Compose one register-specific image from typed logical arguments.\n    pub(crate) const fn compose({parameters}) -> Self {{\n        Self(({composition}) & 0x{:08x})\n    }}\n\n    /// Return the generated numeric image to its private raw-PAC bridge.\n    pub(crate) const fn get(self) -> u32 {{ self.0 }}\n}}\n\n",
                domain.name, domain.name, domain.output_mask,
            ));
        }
        output.push_str(&self.render_indirect_register_field_domains());
        let flag_or_enum_domains = self
            .flag_domains
            .iter()
            .map(|domain| domain.name.as_str())
            .chain(self.enum_domains.iter().map(|domain| domain.name.as_str()))
            .collect::<BTreeSet<_>>();
        for operation in &self.full_register_writes {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let domain = operation.domain.as_str();
            let value = domain_value_expression(domain, &flag_or_enum_domains);
            output.push_str(&format!(
                "/// Typed bridge for the reviewed `{}` complete-register transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, value: {}) {{\n    crate::svd::full_register_write::{}(registers, {});\n}}\n\n",
                operation.name,
                operation.name,
                type_binding_name(&operation.peripheral),
                domain,
                operation.name,
                value,
            ));
        }
        for operation in &self.full_register_reads {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let domain = operation.domain.as_str();
            let raw = format!(
                "crate::svd::full_register_read::{}(registers)",
                operation.name
            );
            let value = if self
                .opaque_domains
                .iter()
                .any(|candidate| candidate.name == operation.domain)
            {
                format!("{domain}::new({raw})")
            } else {
                format!(
                    "{domain}::new({raw}).expect(\"full-register read domain represents every u32\")"
                )
            };
            output.push_str(&format!(
                "/// Typed bridge for the reviewed `{}` complete-register observation.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}) -> {} {{\n    {}\n}}\n\n",
                operation.name,
                operation.name,
                type_binding_name(&operation.peripheral),
                domain,
                value,
            ));
        }
        for operation in &self.register_image_reads {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let domain = operation.domain.as_str();
            let raw = format!(
                "crate::svd::register_image_read::{}(registers)",
                operation.name
            );
            let value = if self
                .opaque_domains
                .iter()
                .any(|candidate| candidate.name == operation.domain)
            {
                format!("{domain}::new({raw})")
            } else {
                format!(
                    "{domain}::new({raw}).expect(\"register-image read domain represents every u32\")"
                )
            };
            output.push_str(&format!(
                "/// Typed bridge for the reviewed `{}` complete-image observation.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}) -> {} {{\n    {}\n}}\n\n",
                operation.name,
                operation.name,
                type_binding_name(&operation.peripheral),
                domain,
                value,
            ));
        }
        for operation in &self.register_image_writes {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let domain = operation.domain.as_str();
            let value = domain_value_expression(domain, &flag_or_enum_domains);
            let (index_parameter, index_argument) = if operation.register.contains("%s") {
                ("index: usize, ", "index, ")
            } else {
                ("", "")
            };
            output.push_str(&format!(
                "/// Typed bridge for the reviewed `{}` complete-image transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, {index_parameter}value: {}) {{\n    crate::svd::register_image_write::{}(registers, {index_argument}{});\n}}\n\n",
                operation.name,
                operation.name,
                type_binding_name(&operation.peripheral),
                domain,
                operation.name,
                value,
            ));
        }
        for operation in &self.masked_register_modifies {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let domain = operation.domain.as_str();
            let value = domain_value_expression(domain, &flag_or_enum_domains);
            let (index_parameter, index_argument) = if operation.register.contains("%s") {
                ("index: usize, ", "index, ")
            } else {
                ("", "")
            };
            output.push_str(&format!(
                "/// Typed bridge for the reviewed `{}` masked transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, {index_parameter}value: {}) {{\n    crate::svd::masked_register_modify::{}(registers, {index_argument}{});\n}}\n\n",
                operation.name,
                operation.name,
                type_binding_name(&operation.peripheral),
                domain,
                operation.name,
                value,
            ));
        }
        for operation in &self.field_or_modifies {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let (index_parameter, index_argument) = if operation.register.contains("%s") {
                ("index: usize, ", "index, ")
            } else {
                ("", "")
            };
            if let Some(domain) = &operation.domain {
                let value = domain_value_expression(domain, &flag_or_enum_domains);
                output.push_str(&format!(
                    "/// Typed bridge for the reviewed `{}` field-OR transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, {index_parameter}value: {}) {{\n    crate::svd::field_or_modify::{}(registers, {index_argument}{value});\n}}\n\n",
                    operation.name,
                    operation.name,
                    type_binding_name(&operation.peripheral),
                    domain,
                    operation.name,
                ));
            } else {
                output.push_str(&format!(
                    "/// Typed bridge for the reviewed `{}` fixed field-OR transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, {index_parameter}) {{\n    crate::svd::field_or_modify::{}(registers, {index_argument});\n}}\n\n",
                    operation.name,
                    operation.name,
                    type_binding_name(&operation.peripheral),
                    operation.name,
                ));
            }
        }
        for operation in &self.field_replace_modifies {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let (index_parameter, index_argument) = if operation.register.contains("%s") {
                ("index: usize, ", "index, ")
            } else {
                ("", "")
            };
            if let Some(domain) = &operation.domain {
                let value = domain_value_expression(domain, &flag_or_enum_domains);
                output.push_str(&format!(
                    "/// Typed bridge for the reviewed `{}` field-replacement transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, {index_parameter}value: {}) {{\n    crate::svd::field_replace_modify::{}(registers, {index_argument}{value});\n}}\n\n",
                    operation.name,
                    operation.name,
                    type_binding_name(&operation.peripheral),
                    domain,
                    operation.name,
                ));
            } else {
                let (fixed_index_parameter, fixed_index_argument) =
                    if operation.register.contains("%s") {
                        (", index: usize", ", index")
                    } else {
                        ("", "")
                    };
                output.push_str(&format!(
                    "/// Typed bridge for the reviewed `{}` fixed field-replacement transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}{fixed_index_parameter}) {{\n    crate::svd::field_replace_modify::{}(registers{fixed_index_argument});\n}}\n\n",
                    operation.name,
                    operation.name,
                    type_binding_name(&operation.peripheral),
                    operation.name,
                ));
            }
        }
        for operation in &self.field_argument_modifies {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let (index_parameter, index_argument) = if operation.register.contains("%s") {
                ("index: usize, ", "index, ")
            } else {
                ("", "")
            };
            let parameters = operation
                .arguments
                .iter()
                .map(|argument| {
                    let argument_type = argument.domain.as_deref().unwrap_or("bool");
                    format!("{}: {argument_type}", argument.name)
                })
                .collect::<Vec<_>>()
                .join(", ");
            let arguments = operation
                .arguments
                .iter()
                .map(|argument| match &argument.domain {
                    None => argument.name.clone(),
                    Some(domain) if flag_or_enum_domains.contains(domain.as_str()) => {
                        format!("{}.bits()", argument.name)
                    }
                    Some(_) => format!("{}.get()", argument.name),
                })
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!(
                "/// Typed bridge for the reviewed `{}` multi-argument field-replacement transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, {index_parameter}{parameters}) {{\n    crate::svd::field_argument_modify::{}(registers, {index_argument}{arguments});\n}}\n\n",
                operation.name,
                operation.name,
                type_binding_name(&operation.peripheral),
                operation.name,
            ));
        }
        for operation in &self.indexed_bit_set_modifies {
            if !operation.exposure.exposes_facade() {
                continue;
            }
            let domain = operation.domain.as_str();
            let index = if flag_or_enum_domains.contains(domain) {
                "index.bits()"
            } else {
                "index.get()"
            };
            let (index_parameter, index_argument) = if operation.register.contains("%s") {
                ("register_index: usize, ", "register_index, ")
            } else {
                ("", "")
            };
            output.push_str(&format!(
                "/// Typed bridge for the reviewed `{}` indexed bit-set transaction.\n#[inline]\npub(crate) fn {}(registers: &crate::svd::{}, {index_parameter}index: {}) {{\n    crate::svd::indexed_bit_set_modify::{}(registers, {index_argument}{});\n}}\n\n",
                operation.name,
                operation.name,
                type_binding_name(&operation.peripheral),
                domain,
                operation.name,
                index,
            ));
        }
        Ok(output)
    }

    fn render_indirect_register_field_domains(&self) -> String {
        let mut output = String::new();
        for domain in &self.indirect_register_field_domains {
            let value_type = match domain.value_bits {
                8 => "u8",
                16 => "u16",
                32 => "u32",
                _ => unreachable!("validated indirect-register value width"),
            };
            push_doc(&mut output, &domain.description, "");
            output.push_str(&format!(
                "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\n\
                 pub struct {} {{\n\
                     bank: u8,\n\
                     register: u8,\n\
                     mask: {},\n\
                     bit_offset: u8,\n\
                 }}\n\n\
                 impl {} {{\n\
                     const fn generated(bank: u8, register: u8, mask: {}, bit_offset: u8) -> Self {{\n\
                         Self {{ bank, register, mask, bit_offset }}\n\
                     }}\n\n\
                     pub(crate) const fn bank(self) -> u8 {{ self.bank }}\n\n\
                     pub(crate) const fn register(self) -> u8 {{ self.register }}\n\n\
                     /// Extract the named field from one sampled indirect-register value.\n\
                     pub const fn extract(self, register_value: {}) -> {} {{\n\
                         (register_value & self.mask) >> self.bit_offset\n\
                     }}\n\n\
                     /// Replace the named field while preserving every other register bit.\n\
                     pub const fn replace(self, register_value: {}, field_value: {}) -> {} {{\n\
                         (register_value & !self.mask) | ((field_value << self.bit_offset) & self.mask)\n\
                     }}\n\
                 }}\n\n",
                domain.name,
                value_type,
                domain.name,
                value_type,
                value_type,
                value_type,
                value_type,
                value_type,
                value_type,
            ));
            output.push_str(&format!(
                "/// Reviewed named fields in the `{}` indirect-register space.\n\
                 pub mod {} {{\n\
                     use super::{};\n\n",
                domain.name, domain.module, domain.name,
            ));
            for field in &domain.fields {
                push_doc(&mut output, &field.description, "    ");
                let low_mask = if field.bit_width == 32 {
                    u32::MAX
                } else {
                    (1_u32 << field.bit_width) - 1
                };
                let mask = low_mask << field.bit_offset;
                output.push_str(&format!(
                    "    pub const {}: {} = {}::generated(0x{:02x}, 0x{:02x}, 0x{:0width$x}, {});\n",
                    field.name,
                    domain.name,
                    domain.name,
                    field.bank,
                    field.register,
                    mask,
                    field.bit_offset,
                    width = usize::from(domain.value_bits / 4),
                ));
            }
            output.push_str("}\n\n");
        }
        output
    }

    /// Render helper modules to append to the svd2rust crate root.
    pub fn render_rust(&self, svd: &str) -> Result<String> {
        self.validate_against_svd(svd)?;
        let device = svd_parser::parse(svd).map_err(|error| Error::message(error.to_string()))?;
        let mut output = String::new();
        output.push_str(&self.render_feature_modules());
        output.push_str(&self.render_sidecar_modules());
        output.push_str(&self.render_interrupt_snapshots(&device)?);
        if !self.ownership_partitions.is_empty() {
            output.push_str(&self.render_peripheral_ownership(&device)?);
        }
        output.push_str(&self.render_full_register_writes());
        output.push_str(&self.render_full_register_reads());
        output.push_str(&self.render_field_reads(&device)?);
        output.push_str(&self.render_field_snapshot_reads(&device)?);
        output.push_str(&self.render_fixed_register_writes());
        output.push_str(&self.render_fixed_register_images(&device)?);
        output.push_str(&self.render_w1c_register_snapshots(&device)?);
        output.push_str(&self.render_register_image_reads(&device)?);
        output.push_str(&self.render_register_image_writes(&device)?);
        output.push_str(&self.render_zero_based_field_writes(&device)?);
        output.push_str(&self.render_sampled_bit_zero_writes());
        output.push_str(&self.render_zero_register_writes(&device)?);
        output.push_str(&self.render_masked_register_modifies(&device)?);
        output.push_str(&self.render_field_or_modifies(&device)?);
        output.push_str(&self.render_field_replace_modifies(&device)?);
        output.push_str(&self.render_field_argument_modifies(&device)?);
        output.push_str(&self.render_indexed_bit_set_modifies(&device)?);
        if self.options.device_access {
            output.push_str(device_access_api());
        }
        Ok(output)
    }

    fn render_feature_modules(&self) -> String {
        let mut output = String::new();
        for module in &self.feature_modules {
            output.push_str(&format!(
                "\n#[cfg(feature = {:?})]\n#[doc(hidden)]\npub mod {};\n",
                module.feature, module.name,
            ));
        }
        output
    }

    fn render_sidecar_modules(&self) -> String {
        let mut output = String::new();
        for module in &self.sidecar_modules {
            output.push_str(&format!("\n#[doc(hidden)]\npub mod {};\n", module.name,));
        }
        output
    }

    fn render_interrupt_snapshots(&self, device: &Device) -> Result<String> {
        if self.interrupt_snapshots.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared read-and-acknowledge interrupt transactions.\n\
             pub mod interrupt_snapshot {\n",
        );
        for binding in &self.interrupt_snapshots {
            let snapshot_type = format!("{}Snapshot", type_binding_name(&binding.name));
            let peripheral_type = type_binding_name(&binding.peripheral);
            let status = member_binding_name(&binding.status_register);
            let clear = member_binding_name(&binding.clear_register);
            let status_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.status_register,
            )?;
            let fields = status_binding.info.fields.as_deref().ok_or_else(|| {
                Error::message(format!(
                    "PAC API interrupt snapshot {:?} status register has no fields",
                    binding.name
                ))
            })?;
            let mut field_accessors = String::new();
            for field in fields {
                let MaybeArray::Single(field) = field else {
                    return Err(Error::message(format!(
                        "PAC API interrupt snapshot {:?} does not support array field {:?}",
                        binding.name, field.name
                    )));
                };
                let width = field.bit_width();
                let offset = field.bit_offset();
                let method = member_binding_name(&field.name);
                let shifted = if offset == 0 {
                    "self.0".to_owned()
                } else {
                    format!("self.0 >> {offset}")
                };
                let (value_type, expression) = match width {
                    1 => ("bool", format!("self.0 & 0x{:08x} != 0", 1_u32 << offset)),
                    2..=8 => (
                        "u8",
                        format!("({shifted} & 0x{:x}) as u8", (1_u64 << width) - 1),
                    ),
                    9..=16 => (
                        "u16",
                        format!("({shifted} & 0x{:x}) as u16", (1_u64 << width) - 1),
                    ),
                    17..=31 => ("u32", format!("{shifted} & 0x{:x}", (1_u64 << width) - 1)),
                    32 => ("u32", "self.0".to_owned()),
                    _ => unreachable!("SVD validation rejects invalid field widths"),
                };
                field_accessors.push_str(&format!(
                    "        /// Sampled value of SVD field `{}`.\n\
                     #[inline]\n\
                     pub const fn {method}(&self) -> {value_type} {{ {expression} }}\n",
                    field.name,
                ));
            }
            output.push_str(&format!(
                "\n    /// Opaque event image sampled from `{}`.`{}`.\n\
                 #[must_use = \"an interrupt snapshot must be inspected and acknowledged\"]\n\
                 #[derive(Debug)]\n\
                 pub struct {snapshot_type}(u32);\n\
                 impl {snapshot_type} {{\n\
                     /// Complete masked event image observed by the status read.\n\
                     #[inline]\n\
                     pub const fn bits(&self) -> u32 {{ self.0 }}\n\
                     /// Whether the sampled register contained no asserted event.\n\
                     #[inline]\n\
                     pub const fn is_empty(&self) -> bool {{ self.0 == 0 }}\n\
{field_accessors}\
                 }}\n\
                 /// Sample the complete masked event image.\n\
                 #[inline]\n\
                 pub fn sample_{}(registers: &crate::{peripheral_type}) -> {snapshot_type} {{\n\
                     {snapshot_type}(registers.{status}().read().bits())\n\
                 }}\n\
                 /// Acknowledge exactly the event image returned by the paired sample.\n\
                 #[inline]\n\
                 pub fn acknowledge_{}(\n\
                     registers: &crate::{peripheral_type},\n\
                     snapshot: {snapshot_type},\n\
                 ) {{\n\
                     // SAFETY: the opaque value can only be constructed by the paired\n\
                     // STATUS read (or in a validation-only build) and CLEAR is an\n\
                     // SVD-validated full-width write-one-to-clear register.\n\
                     unsafe {{\n\
                         registers.{clear}().write_with_zero(|writer| writer.bits(snapshot.0));\n\
                     }}\n\
                 }}\n\
                 #[cfg(feature = \"validation-probes\")]\n\
                 #[doc(hidden)]\n\
                 pub const fn {}_for_validation(bits: u32) -> {snapshot_type} {{\n\
                     {snapshot_type}(bits)\n\
                 }}\n",
                binding.peripheral,
                binding.status_register,
                binding.name,
                binding.name,
                binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_peripheral_ownership(&self, device: &Device) -> Result<String> {
        let peripheral_names = device
            .peripherals
            .iter()
            .map(|peripheral| peripheral.name.clone())
            .collect::<Vec<_>>();
        let mut rendered_members = BTreeSet::new();
        let mut rendered_types = BTreeSet::new();
        for name in &peripheral_names {
            let member = member_binding_name(name);
            if !rendered_members.insert(member.clone()) {
                return Err(Error::message(format!(
                    "PAC API ownership has colliding rendered peripheral member {member:?}"
                )));
            }
            let ty = type_binding_name(name);
            if !rendered_types.insert(ty.clone()) {
                return Err(Error::message(format!(
                    "PAC API ownership has colliding rendered peripheral type {ty:?}"
                )));
            }
        }
        let fields = |names: &[String]| {
            names
                .iter()
                .map(|name| {
                    format!(
                        "    pub {}: crate::{},\n",
                        member_binding_name(name),
                        type_binding_name(name),
                    )
                })
                .collect::<String>()
        };
        let members = |names: &[String], indent: &str| {
            names
                .iter()
                .map(|name| format!("{indent}{},\n", member_binding_name(name)))
                .collect::<String>()
        };
        let mut output = String::from(
            "\n/// Target-declared exhaustive ownership partitions of the raw SVD singleton.\n\
             pub mod peripheral_ownership {\n",
        );
        for partition in &self.ownership_partitions {
            output.push('\n');
            push_doc(&mut output, &partition.description, "    ");
            output.push_str(&format!(
                "    pub struct {} {{\n{}    }}\n",
                partition.name,
                fields(&partition.peripherals),
            ));
        }
        output.push_str("\n    /// Complete target-reviewed ownership decomposition.\n");
        output.push_str("    pub struct PeripheralPartitions {\n");
        for partition in &self.ownership_partitions {
            push_doc(&mut output, &partition.description, "        ");
            output.push_str(&format!(
                "        pub {}: {},\n",
                partition.member, partition.name
            ));
        }
        output.push_str(
            "    }\n\
             \n    /// Consume the singleton and apply the exhaustive target-owned partition.\n\
             #[inline]\n\
             pub fn partition(peripherals: crate::Peripherals) -> PeripheralPartitions {\n\
                 let crate::Peripherals {\n",
        );
        output.push_str(&members(&peripheral_names, "            "));
        output.push_str(
            "        } = peripherals;\n\
                     PeripheralPartitions {\n",
        );
        for partition in &self.ownership_partitions {
            output.push_str(&format!(
                "            {}: {} {{\n{}            }},\n",
                partition.member,
                partition.name,
                members(&partition.peripherals, "                "),
            ));
        }
        output.push_str(
            "        }\n\
                 }\n\
                 \n    /// Acquire a fresh singleton in an isolated compiled-validation image.\n\
                 #[cfg(feature = \"validation-probes\")]\n\
                 #[doc(hidden)]\n\
                 #[inline]\n\
                 pub fn peripherals_for_validation() -> crate::Peripherals {\n\
                     // SAFETY: validation images contain one closed probe and no runtime driver.\n\
                     unsafe { crate::Peripherals::steal() }\n\
                 }\n\
                 }\n",
        );
        Ok(output)
    }

    fn render_full_register_writes(&self) -> String {
        if self.full_register_writes.is_empty() {
            return String::new();
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared writes which cover a complete register.\n\
             pub mod full_register_write {\n",
        );
        for binding in &self.full_register_writes {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let field = member_binding_name(&binding.field);
            output.push_str(&format!(
                "\n    /// Write every bit of `{}`.`{}` through its full-width field.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, value: u32) {{\n\
                     // SAFETY: generator validation proves that this is the only field,\n\
                     // it covers all 32 bits and accepts every `u32`; no zero-filled\n\
                     // reserved or partially described bits remain.\n\
                     unsafe {{\n\
                         registers.{register}().write_with_zero(|writer|\n\
                             writer.{field}().set(value)\n\
                         );\n\
                     }}\n\
                 }}\n",
                binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        output
    }

    fn render_full_register_reads(&self) -> String {
        if self.full_register_reads.is_empty() {
            return String::new();
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared observations which cover a complete register.\n\
             pub mod full_register_read {\n",
        );
        for binding in &self.full_register_reads {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let field = member_binding_name(&binding.field);
            output.push_str(&format!(
                "\n    /// Read every bit of `{}`.`{}` through its full-width field.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}) -> u32 {{\n\
                     registers.{register}().read().{field}().bits()\n\
                 }}\n",
                binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        output
    }

    fn render_field_reads(&self, device: &Device) -> Result<String> {
        if self.field_reads.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe observations through reviewed SVD fields.\n\
             pub mod field_read {\n",
        );
        for binding in &self.field_reads {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let field_name = member_binding_name(&binding.field);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                (", index: usize", "index")
            } else {
                ("", "")
            };
            let selected =
                pac_api_svd::field(&binding.name, register_binding.info, &binding.field)?;
            let (value_type, reader, signed_cast) = match (binding.signed, selected.bit_width()) {
                (true, 8) => ("i8", "bits", " as i8"),
                (true, 16) => ("i16", "bits", " as i16"),
                (true, 32) => ("i32", "bits", " as i32"),
                (true, _) => {
                    return Err(Error::message(format!(
                        "PAC API signed field-read {:?} requires a complete 8-, 16-, or 32-bit field",
                        binding.name
                    )));
                }
                (false, 1) => ("bool", "bit", ""),
                (false, 2..=8) => ("u8", "bits", ""),
                (false, 9..=16) => ("u16", "bits", ""),
                (false, 17..=32) => ("u32", "bits", ""),
                (false, _) => unreachable!("SVD validation rejects invalid field widths"),
            };
            output.push_str(&format!(
                "\n    /// Read `{}`.`{}`.`{}` without exposing its register block.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}{index_parameter}) -> {value_type} {{\n\
                     registers.{register}({index_argument}).read().{field_name}().{reader}(){signed_cast}\n\
                 }}\n",
                binding.peripheral, binding.register, binding.field, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_field_snapshot_reads(&self, device: &Device) -> Result<String> {
        if self.field_snapshot_reads.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe same-sample observations through reviewed SVD fields.\n\
             pub mod field_snapshot_read {\n",
        );
        for binding in &self.field_snapshot_reads {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                (", index: usize", "index")
            } else {
                ("", "")
            };
            let fields = binding
                .fields
                .iter()
                .map(|name| {
                    let selected = pac_api_svd::field(&binding.name, register_binding.info, name)?;
                    let (value_type, reader) = match selected.bit_width() {
                        1 => ("bool", "bit"),
                        2..=8 => ("u8", "bits"),
                        9..=16 => ("u16", "bits"),
                        17..=32 => ("u32", "bits"),
                        _ => unreachable!("SVD validation rejects invalid field widths"),
                    };
                    Ok((name, value_type, reader))
                })
                .collect::<Result<Vec<_>>>()?;
            let return_type = fields
                .iter()
                .map(|(_, value_type, _)| *value_type)
                .collect::<Vec<_>>()
                .join(", ");
            let values = fields
                .iter()
                .map(|(name, _, reader)| {
                    format!("sample.{}().{}()", member_binding_name(name), reader)
                })
                .collect::<Vec<_>>()
                .join(", ");
            let field_list = binding
                .fields
                .iter()
                .map(|field| format!("`{field}`"))
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!(
                "\n    /// Read {field_list} from one `{}`.`{}` sample.\n\
                 #[allow(clippy::type_complexity)]\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}{index_parameter}) -> ({return_type}) {{\n\
                     let sample = registers.{register}({index_argument}).read();\n\
                     ({values})\n\
                 }}\n",
                binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_fixed_register_writes(&self) -> String {
        if self.fixed_register_writes.is_empty() {
            return String::new();
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared complete-register writes of fixed enumerated values.\n\
             pub mod fixed_register_write {\n",
        );
        for binding in &self.fixed_register_writes {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let field = member_binding_name(&binding.field);
            let variant = member_binding_name(&binding.variant);
            output.push_str(&format!(
                "\n    /// Write the `{}` variant to every bit of `{}`.`{}`.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}) {{\n\
                     // SAFETY: generator validation proves that the sole field covers\n\
                     // all 32 bits and the named writable variant exists in the SVD.\n\
                     unsafe {{\n\
                         registers.{register}().write_with_zero(|writer|\n\
                             writer.{field}().{variant}()\n\
                         );\n\
                     }}\n\
                 }}\n",
                binding.variant, binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        output
    }

    fn render_fixed_register_images(&self, device: &Device) -> Result<String> {
        if self.fixed_register_images.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared writes of fixed complete-register images.\n\
             pub mod fixed_register_image {\n",
        );
        for binding in &self.fixed_register_images {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                (", index: usize", "index")
            } else {
                ("", "")
            };
            output.push_str(&format!(
                "\n    /// Publish the SVD-qualified image `0x{:08x}` to `{}`.`{}`.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}{index_parameter}) {{\n\
                     // SAFETY: generator validation proves that the target is a\n\
                     // writable 32-bit ordinary or write-one-to-clear register,\n\
                     // while reviewed provenance qualifies this exact image.\n\
                     unsafe {{\n\
                         registers.{register}({index_argument}).write_with_zero(|writer|\n\
                             writer.bits(0x{:08x})\n\
                         );\n\
                     }}\n\
                 }}\n",
                binding.value, binding.peripheral, binding.register, binding.name, binding.value,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_w1c_register_snapshots(&self, device: &Device) -> Result<String> {
        if self.w1c_register_snapshots.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Affine sample-and-acknowledge transactions for same-register W1C fields.\n\
             pub mod w1c_register_snapshot {\n",
        );
        for binding in &self.w1c_register_snapshots {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            debug_assert!(!register_binding.is_array);
            let fields = register_binding.info.fields.as_deref().ok_or_else(|| {
                Error::message(format!(
                    "PAC API w1c-register-snapshot {:?} register has no fields",
                    binding.name
                ))
            })?;
            let mut mask = 0_u32;
            let mut field_accessors = String::new();
            for field in fields {
                let MaybeArray::Single(field) = field else {
                    return Err(Error::message(format!(
                        "PAC API w1c-register-snapshot {:?} does not support array field {:?}",
                        binding.name, field.name
                    )));
                };
                let width = field.bit_width();
                let offset = field.bit_offset();
                let field_mask = if width == 32 {
                    u32::MAX
                } else {
                    (((1_u64 << width) - 1) << offset) as u32
                };
                mask |= field_mask;
                let method = member_binding_name(&field.name);
                let shifted = if offset == 0 {
                    "self.0".to_owned()
                } else {
                    format!("self.0 >> {offset}")
                };
                let (value_type, expression) = match width {
                    1 => ("bool", format!("self.0 & 0x{field_mask:08x} != 0")),
                    2..=8 => (
                        "u8",
                        format!("({shifted} & 0x{:x}) as u8", (1_u64 << width) - 1),
                    ),
                    9..=16 => (
                        "u16",
                        format!("({shifted} & 0x{:x}) as u16", (1_u64 << width) - 1),
                    ),
                    17..=31 => ("u32", format!("{shifted} & 0x{:x}", (1_u64 << width) - 1)),
                    32 => ("u32", "self.0".to_owned()),
                    _ => unreachable!("SVD validation rejects invalid field widths"),
                };
                field_accessors.push_str(&format!(
                    "        /// Sampled value of SVD field `{}`.\n\
                     #[inline]\n\
                     pub const fn {method}(&self) -> {value_type} {{ {expression} }}\n",
                    field.name,
                ));
            }
            let snapshot_type = format!("{}Snapshot", type_binding_name(&binding.name));
            output.push_str(&format!(
                "\n    /// One unforgeable `{}.{}` field set sampled before acknowledgement.\n\
                 #[must_use = \"a W1C snapshot must be inspected and acknowledged\"]\n\
                 #[derive(Debug)]\n\
                 pub struct {snapshot_type}(u32);\n\
                 impl {snapshot_type} {{\n\
                     /// Whether no declared field was asserted in the sample.\n\
                     #[inline]\n\
                     pub const fn is_clear(&self) -> bool {{ self.0 == 0 }}\n\
{field_accessors}\
                 }}\n\
                 \n\
                 /// Sample `{}.{}` once and retain only its declared fields.\n\
                 #[inline]\n\
                 pub fn sample_{}(registers: &crate::{peripheral_type}) -> {snapshot_type} {{\n\
                     {snapshot_type}(registers.{register}().read().bits() & 0x{mask:08x})\n\
                 }}\n\
                 \n\
                 /// Acknowledge exactly the sampled declared-field set and consume it.\n\
                 #[inline]\n\
                 pub fn acknowledge_{}(\n\
                     registers: &mut crate::{peripheral_type},\n\
                     snapshot: {snapshot_type},\n\
                 ) {{\n\
                     // SAFETY: generator validation binds the affine snapshot to this\n\
                     // exact 32-bit same-register W1C declaration. The token cannot be\n\
                     // forged, cloned or replayed, and every undeclared bit is zero.\n\
                     unsafe {{\n\
                         registers.{register}().write_with_zero(|writer| writer.bits(snapshot.0));\n\
                     }}\n\
                 }}\n",
                binding.peripheral,
                binding.register,
                binding.peripheral,
                binding.register,
                binding.name,
                binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_register_image_reads(&self, device: &Device) -> Result<String> {
        if self.register_image_reads.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared observations of complete ordinary-register images.\n\
             pub mod register_image_read {\n",
        );
        for binding in &self.register_image_reads {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            debug_assert!(!register_binding.is_array);
            output.push_str(&format!(
                "\n    /// Capture the complete image of `{}`.`{}`.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}) -> u32 {{\n\
                     registers.{register}().read().bits()\n\
                 }}\n",
                binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_register_image_writes(&self, device: &Device) -> Result<String> {
        if self.register_image_writes.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared writes of dynamic complete-register images.\n\
             pub mod register_image_write {\n",
        );
        for binding in &self.register_image_writes {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                ("index: usize, ", "index")
            } else {
                ("", "")
            };
            output.push_str(&format!(
                "\n    /// Publish a caller-built complete image to `{}`.`{}`.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, {index_parameter}image: u32) {{\n\
                     // SAFETY: generator validation proves that the target is an\n\
                     // ordinary writable 32-bit register. The SVD extension and\n\
                     // its provenance qualify this semantic whole-image operation.\n\
                     unsafe {{\n\
                         registers.{register}({index_argument}).write_with_zero(|writer|\n\
                             writer.bits(image)\n\
                         );\n\
                     }}\n\
                 }}\n",
                binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_zero_based_field_writes(&self, device: &Device) -> Result<String> {
        if self.zero_based_field_writes.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared field writes based on an all-zero register image.\n\
             pub mod zero_based_field_write {\n",
        );
        for binding in &self.zero_based_field_writes {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                ("index: usize, ", "index")
            } else {
                ("", "")
            };
            let fields = binding
                .fields
                .iter()
                .map(|name| {
                    let field = pac_api_svd::field(&binding.name, register_binding.info, name)?;
                    let value_type = match field.bit_width() {
                        1 => "bool",
                        2..=8 => "u8",
                        9..=16 => "u16",
                        17..=32 => "u32",
                        _ => unreachable!("SVD validation rejects invalid field widths"),
                    };
                    Ok((name, value_type))
                })
                .collect::<Result<Vec<_>>>()?;
            let field_list = fields
                .iter()
                .map(|(name, _)| format!("`{name}`"))
                .collect::<Vec<_>>()
                .join(", ");
            let (value_parameters, field_writes) = if fields.len() == 1 {
                let (name, value_type) = fields[0];
                let field_name = member_binding_name(name);
                let write = if value_type == "bool" {
                    format!("writer.{field_name}().bit(value)")
                } else {
                    format!("writer.{field_name}().set(value)")
                };
                (format!("value: {value_type}"), write)
            } else {
                let parameters = fields
                    .iter()
                    .map(|(name, value_type)| {
                        format!("{}_value: {value_type}", member_binding_name(name))
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let writes = fields
                    .iter()
                    .map(|(name, value_type)| {
                        let field_name = member_binding_name(name);
                        let method = if *value_type == "bool" { "bit" } else { "set" };
                        format!(".{field_name}().{method}({field_name}_value)")
                    })
                    .collect::<String>();
                (parameters, format!("writer{writes}"))
            };
            let argument_lint =
                too_many_arguments_attribute(fields.len(), register_binding.is_array);
            output.push_str(&format!(
                "\n    /// Write {field_list} in `{}`.`{}` while publishing zero to every other register bit.\n\
                 {argument_lint}\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, {index_parameter}{value_parameters}) {{\n\
                     // SAFETY: the SVD extension explicitly qualifies the zero-based\n\
                     // transaction, and generator validation proves every selected field\n\
                     // accepts every value representable by its public argument type.\n\
                     unsafe {{\n\
                         registers.{register}({index_argument}).write_with_zero(|writer|\n\
                             {field_writes}\n\
                         );\n\
                     }}\n\
                 }}\n",
                binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_sampled_bit_zero_writes(&self) -> String {
        if self.sampled_bit_zero_writes.is_empty() {
            return String::new();
        }
        let mut output = String::from(
            "\n/// Safe fresh one-bit samples republished over otherwise zero register images.\n\
             pub mod sampled_bit_zero_write {\n",
        );
        for binding in &self.sampled_bit_zero_writes {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let field = member_binding_name(&binding.field);
            output.push_str(&format!(
                "\n    /// Sample `{}`.`{}`.`{}` and write only that bit into a fresh zero image.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}) {{\n\
                     let sampled = registers.{register}().read().{field}().bit();\n\
                     // SAFETY: generator validation proves that the target is one\n\
                     // ordinary readable/writable bit. Every other register bit is\n\
                     // intentionally published as zero by this reviewed transaction.\n\
                     unsafe {{\n\
                         registers.{register}().write_with_zero(|writer|\n\
                             writer.{field}().bit(sampled)\n\
                         );\n\
                     }}\n\
                 }}\n",
                binding.peripheral, binding.register, binding.field, binding.name,
            ));
        }
        output.push_str("}\n");
        output
    }

    fn render_zero_register_writes(&self, device: &Device) -> Result<String> {
        if self.zero_register_writes.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared complete-register zero writes.\n\
             pub mod zero_register_write {\n",
        );
        for binding in &self.zero_register_writes {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                (", index: usize", "index")
            } else {
                ("", "")
            };
            output.push_str(&format!(
                "\n    /// Publish zero to every bit of `{}`.`{}`.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}{index_parameter}) {{\n\
                     // SAFETY: the SVD extension and its provenance explicitly\n\
                     // qualify a complete zero write to this ordinary register.\n\
                     unsafe {{\n\
                         registers.{register}({index_argument}).write_with_zero(|writer| writer);\n\
                     }}\n\
                 }}\n",
                binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_masked_register_modifies(&self, device: &Device) -> Result<String> {
        if self.masked_register_modifies.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared masked read-modify-write transactions.\n\
             pub mod masked_register_modify {\n",
        );
        for binding in &self.masked_register_modifies {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                ("index: usize, ", "index")
            } else {
                ("", "")
            };
            let image_expression = masked_image_expression(
                binding.preserve_mask,
                binding.input_mask,
                binding.set_mask,
            );
            output.push_str(&format!(
                "\n    /// Preserve mask 0x{:08x}, accept input mask 0x{:08x}, and set 0x{:08x} in {}.{}.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, {index_parameter}input: u32) {{\n\
                     registers.{register}({index_argument}).modify(|reader, writer| {{\n\
                         let image = {image_expression};\n\
                         // SAFETY: generator validation proves the three masks are\n\
                         // disjoint and partition every bit of this ordinary register.\n\
                         unsafe {{ writer.bits(image) }}\n\
                     }});\n\
                 }}\n",
                binding.preserve_mask,
                binding.input_mask,
                binding.set_mask,
                binding.peripheral,
                binding.register,
                binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_field_or_modifies(&self, device: &Device) -> Result<String> {
        if self.field_or_modifies.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared field-local OR read-modify-write transactions.\n\
             pub mod field_or_modify {\n",
        );
        for binding in &self.field_or_modifies {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                ("index: usize, ", "index")
            } else {
                ("", "")
            };
            let (input_parameter, fixed_input) = if binding.domain.is_some() {
                ("input: u32", String::new())
            } else {
                (
                    "",
                    format!(
                        "let input = 0x{:08x}_u32;\n                         ",
                        binding
                            .value
                            .expect("pack validation requires a fixed field-OR value")
                    ),
                )
            };
            let mut update = String::from("writer");
            let mut requires_unsafe = false;
            for projection in &binding.fields {
                let selected_field =
                    pac_api_svd::field(&binding.name, register_binding.info, &projection.field)?;
                let field = member_binding_name(&projection.field);
                let width = selected_field.bit_width();
                let mask = if width == 32 {
                    u32::MAX
                } else {
                    (1_u32 << width) - 1
                };
                let projected = if projection.source_bit_offset == 0 {
                    format!("input & 0x{mask:08x}")
                } else {
                    format!("(input >> {}) & 0x{mask:08x}", projection.source_bit_offset)
                };
                if width == 1 {
                    update.push_str(&format!(
                        "\n                             .{field}().bit(reader.{field}().bit() || ({projected}) != 0)"
                    ));
                } else {
                    requires_unsafe = true;
                    let projected = match width {
                        2..=8 => format!("({projected}) as u8"),
                        9..=16 => format!("({projected}) as u16"),
                        17..=32 => projected,
                        _ => unreachable!("SVD validation rejects invalid field widths"),
                    };
                    update.push_str(&format!(
                        "\n                             .{field}().bits(reader.{field}().bits() | {projected})"
                    ));
                }
            }
            let update = if requires_unsafe {
                format!("unsafe {{ {update} }}")
            } else {
                update
            };
            let fields = binding
                .fields
                .iter()
                .map(|projection| projection.field.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!(
                "\n    /// OR one reviewed logical image into {}.{} fields [{}] while preserving the fresh register observation.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, {index_parameter}{input_parameter}) {{\n\
                     registers.{register}({index_argument}).modify(|reader, writer| {{\n\
                         {fixed_input}// SAFETY: generator validation proves every logical input projection\n\
                         // fits its named SVD field; no whole-register image crosses this API.\n\
                         {update}\n\
                     }});\n\
                 }}\n",
                binding.peripheral, binding.register, fields, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_field_replace_modifies(&self, device: &Device) -> Result<String> {
        if self.field_replace_modifies.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared field-replacement read-modify-write transactions.\n\
             pub mod field_replace_modify {\n",
        );
        for binding in &self.field_replace_modifies {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                ("index: usize, ", "index")
            } else {
                ("", "")
            };
            let (input_parameter, fixed_input) = if binding.domain.is_some() {
                let input_transform = binding.input_transform.map_or_else(String::new, |transform| {
                    format!(
                        "let input = input.wrapping_sub(0x{:08x}) & 0x{:08x};\n                         ",
                        transform.wrapping_subtract, transform.retain_mask,
                    )
                });
                ("input: u32", input_transform)
            } else {
                (
                    "",
                    format!(
                        "let input = 0x{:08x}_u32;\n                         ",
                        binding
                            .value
                            .expect("pack validation requires a fixed field-replace value")
                    ),
                )
            };
            let mut update = String::from("writer");
            let mut requires_unsafe = false;
            for projection in &binding.fields {
                let selected_field =
                    pac_api_svd::field(&binding.name, register_binding.info, &projection.field)?;
                let field = member_binding_name(&projection.field);
                let width = selected_field.bit_width();
                let mask = if width == 32 {
                    u32::MAX
                } else {
                    (1_u32 << width) - 1
                };
                let projected = if projection.source_bit_offset == 0 {
                    format!("input & 0x{mask:08x}")
                } else {
                    format!("(input >> {}) & 0x{mask:08x}", projection.source_bit_offset)
                };
                if width == 1 {
                    update.push_str(&format!(
                        "\n                             .{field}().bit(({projected}) != 0)"
                    ));
                } else {
                    requires_unsafe = true;
                    let projected = match width {
                        2..=8 => format!("({projected}) as u8"),
                        9..=16 => format!("({projected}) as u16"),
                        17..=32 => projected,
                        _ => unreachable!("SVD validation rejects invalid field widths"),
                    };
                    update.push_str(&format!(
                        "\n                             .{field}().bits({projected})"
                    ));
                }
            }
            let update = if requires_unsafe {
                format!("unsafe {{ {update} }}")
            } else {
                update
            };
            let fields = binding
                .fields
                .iter()
                .map(|projection| projection.field.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!(
                "\n    /// Replace {}.{} fields [{}] from one reviewed logical image while preserving every other bit.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, {index_parameter}{input_parameter}) {{\n\
                     registers.{register}({index_argument}).modify(|_, writer| {{\n\
                         {fixed_input}// SAFETY: generator validation proves every logical input projection\n\
                         // fits its named SVD field; no whole-register image crosses this API.\n\
                         {update}\n\
                     }});\n\
                 }}\n",
                binding.peripheral, binding.register, fields, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_field_argument_modifies(&self, device: &Device) -> Result<String> {
        if self.field_argument_modifies.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared multi-argument field-replacement transactions.\n\
             pub mod field_argument_modify {\n",
        );
        for binding in &self.field_argument_modifies {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                ("index: usize, ", "index")
            } else {
                ("", "")
            };
            let parameters = binding
                .arguments
                .iter()
                .map(|argument| {
                    format!(
                        "{}: {}",
                        argument.name,
                        if argument.domain.is_some() {
                            "u32"
                        } else {
                            "bool"
                        }
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            let mut update = String::from("writer");
            let mut requires_unsafe = false;
            for argument in &binding.arguments {
                let selected_field =
                    pac_api_svd::field(&binding.name, register_binding.info, &argument.field)?;
                let field = member_binding_name(&argument.field);
                let width = selected_field.bit_width();
                if argument.domain.is_none() {
                    update.push_str(&format!(
                        "\n                             .{field}().bit({})",
                        argument.name
                    ));
                } else if width == 1 {
                    update.push_str(&format!(
                        "\n                             .{field}().bit({} != 0)",
                        argument.name
                    ));
                } else {
                    requires_unsafe = true;
                    let value = match width {
                        2..=8 => format!("{} as u8", argument.name),
                        9..=16 => format!("{} as u16", argument.name),
                        17..=32 => argument.name.clone(),
                        _ => unreachable!("SVD validation rejects invalid field widths"),
                    };
                    update.push_str(&format!(
                        "\n                             .{field}().bits({value})"
                    ));
                }
            }
            let update = if requires_unsafe {
                format!("unsafe {{ {update} }}")
            } else {
                update
            };
            let fields = binding
                .arguments
                .iter()
                .map(|argument| format!("{} -> {}", argument.name, argument.field))
                .collect::<Vec<_>>()
                .join(", ");
            let too_many_arguments =
                too_many_arguments_attribute(binding.arguments.len(), register_binding.is_array);
            output.push_str(&format!(
                "\n    /// Replace {}.{} fields [{}] from independently typed arguments while preserving every other bit.\n\
                 {too_many_arguments}#[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, {index_parameter}{parameters}) {{\n\
                     registers.{register}({index_argument}).modify(|_, writer| {{\n\
                         // SAFETY: generator validation proves every typed argument fits its named SVD field;\n\
                         // no whole-register image crosses this API.\n\
                         {update}\n\
                     }});\n\
                 }}\n",
                binding.peripheral, binding.register, fields, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }

    fn render_indexed_bit_set_modifies(&self, device: &Device) -> Result<String> {
        if self.indexed_bit_set_modifies.is_empty() {
            return Ok(String::new());
        }
        let mut output = String::from(
            "\n/// Safe, SVD-declared indexed bit-set read-modify-write transactions.\n\
             pub mod indexed_bit_set_modify {\n",
        );
        for binding in &self.indexed_bit_set_modifies {
            let peripheral_type = type_binding_name(&binding.peripheral);
            let register = member_binding_name(&binding.register);
            let field = member_binding_name(&binding.field);
            let register_binding = pac_api_svd::register(
                device,
                &binding.name,
                &binding.peripheral,
                &binding.register,
            )?;
            let field_binding =
                pac_api_svd::field(&binding.name, register_binding.info, &binding.field)?;
            let (index_parameter, index_argument) = if register_binding.is_array {
                ("register_index: usize, ", "register_index")
            } else {
                ("", "")
            };
            let update = match field_binding.bit_width() {
                1 => format!("writer.{field}().set_bit()"),
                2..=8 => format!(
                    "writer.{field}().set((u32::from(reader.{field}().bits()) | (1_u32 << bit_index)) as u8)"
                ),
                9..=16 => format!(
                    "writer.{field}().set((u32::from(reader.{field}().bits()) | (1_u32 << bit_index)) as u16)"
                ),
                17..=32 => {
                    format!("writer.{field}().set(reader.{field}().bits() | (1_u32 << bit_index))")
                }
                _ => unreachable!("SVD validation rejects invalid field widths"),
            };
            output.push_str(&format!(
                "\n    /// Set one bit selected by the reviewed `{}` domain in {}.{}.\n\
                 #[inline]\n\
                 pub fn {}(registers: &crate::{peripheral_type}, {index_parameter}bit_index: u32) {{\n\
                     registers.{register}({index_argument}).modify(|reader, writer| {{\n\
                         {update}\n\
                     }});\n\
                 }}\n",
                binding.domain, binding.peripheral, binding.register, binding.name,
            ));
        }
        output.push_str("}\n");
        Ok(output)
    }
}

fn domain_value_expression(domain: &str, flag_or_enum_domains: &BTreeSet<&str>) -> &'static str {
    if flag_or_enum_domains.contains(domain) {
        "value.bits()"
    } else {
        "value.get()"
    }
}

fn push_doc(output: &mut String, description: &str, indent: &str) {
    for line in description.lines() {
        output.push_str(indent);
        output.push_str("///");
        if !line.is_empty() {
            output.push(' ');
            output.push_str(line);
        }
        output.push('\n');
    }
}

fn too_many_arguments_attribute(field_count: usize, is_array: bool) -> &'static str {
    if field_count + usize::from(is_array) > 6 {
        "    #[allow(clippy::too_many_arguments, reason = \"reviewed hardware transaction exposes one typed argument per field\")]\n"
    } else {
        ""
    }
}

fn masked_image_expression(preserve_mask: u32, input_mask: u32, set_mask: u32) -> String {
    let mut expression =
        format!("(reader.bits() & 0x{preserve_mask:08x}) | (input & 0x{input_mask:08x})");
    if set_mask != 0 {
        expression.push_str(&format!(" | 0x{set_mask:08x}"));
    }
    expression
}

fn remove_dimension_placeholder(value: &str) -> String {
    value.replace("[%s]", "").replace("%s", "")
}

fn member_binding_name(value: &str) -> String {
    remove_dimension_placeholder(value).to_ascii_lowercase()
}

fn type_binding_name(value: &str) -> String {
    let value = remove_dimension_placeholder(value);
    let mut output = String::new();
    let mut previous_ended_with_digit = false;
    for part in value.split(['_', '-']).filter(|part| !part.is_empty()) {
        if previous_ended_with_digit
            && part.starts_with(|character: char| character.is_ascii_digit())
        {
            output.push('_');
        }
        for (index, character) in part.chars().enumerate() {
            if index == 0 {
                output.push(character.to_ascii_uppercase());
            } else {
                output.push(character.to_ascii_lowercase());
            }
        }
        previous_ended_with_digit = part.ends_with(|character: char| character.is_ascii_digit());
    }
    output
}

fn device_access_api() -> &'static str {
    "\n/// Architecture-specific device-memory ordering primitives.\n\
     pub mod device_access {\n\
         /// Order all preceding and following device-memory accesses.\n\
         #[inline]\n\
         pub fn fence() {\n\
             #[cfg(target_arch = \"riscv32\")]\n\
             // SAFETY: this instruction only orders memory and device accesses.\n\
             unsafe { core::arch::asm!(\"fence iorw, iorw\") }\n\
             #[cfg(target_arch = \"arm\")]\n\
             // SAFETY: this instruction only orders memory and device accesses.\n\
             unsafe { core::arch::asm!(\"dmb sy\") }\n\
             #[cfg(target_arch = \"xtensa\")]\n\
             // SAFETY: this instruction only orders memory and device accesses.\n\
             unsafe { core::arch::asm!(\"memw\") }\n\
             #[cfg(not(any(\n\
                 target_arch = \"riscv32\",\n\
                 target_arch = \"arm\",\n\
                 target_arch = \"xtensa\",\n\
             )))]\n\
             core::sync::atomic::compiler_fence(core::sync::atomic::Ordering::SeqCst);\n\
         }\n\
     }\n"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn type_binding_matches_svd2rust_for_adjacent_numeric_segments() {
        assert_eq!(type_binding_name("BT_V3_2_BASEBAND"), "BtV3_2Baseband");
        assert_eq!(type_binding_name("UART0_CONTROL"), "Uart0Control");
    }

    #[test]
    fn renders_target_declared_n_way_ownership_without_legacy_split() {
        let pack: PacApiPack = toml_edit::de::from_str(
            r#"schema = 5

[[ownership-partitions]]
name = "TaskPeripherals"
member = "task"
description = "Task-owned register bank."
peripherals = ["RADIO"]

[[ownership-partitions]]
name = "IrqPeripherals"
member = "irq"
description = "Interrupt-owned register bank."
peripherals = ["INTERRUPT"]
"#,
        )
        .unwrap();
        let svd = r#"<?xml version="1.0" encoding="UTF-8"?>
<device schemaVersion="1.3" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
  <name>FIXTURE</name>
  <version>1</version>
  <description>fixture</description>
  <addressUnitBits>8</addressUnitBits>
  <width>32</width>
  <peripherals>
    <peripheral><name>RADIO</name><description>radio</description><baseAddress>0x40000000</baseAddress></peripheral>
    <peripheral><name>INTERRUPT</name><description>irq</description><baseAddress>0x40001000</baseAddress></peripheral>
  </peripherals>
</device>
"#;

        let source = pack.render_rust(svd).unwrap();
        assert!(source.contains("pub struct TaskPeripherals"));
        assert!(source.contains("pub struct IrqPeripherals"));
        assert!(source.contains("pub struct PeripheralPartitions"));
        assert!(source.contains("pub task: TaskPeripherals"));
        assert!(source.contains("pub irq: IrqPeripherals"));
        assert!(source.contains("pub fn partition("));
        assert!(
            source.contains("let crate::Peripherals {\n            radio,\n            interrupt,")
        );
        assert!(!source.contains("RadioPeripherals"));
        assert!(!source.contains("InterruptPeripherals"));
        assert!(!source.contains("pub fn split("));
        assert!(!source.contains(".."));
    }

    #[test]
    fn feature_modules_are_reproducible_and_feature_gated() {
        let pack: PacApiPack = toml_edit::de::from_str(
            r#"schema = 5

[[feature-modules]]
name = "event_status_validation"
feature = "validation-probes"
"#,
        )
        .unwrap();

        assert_eq!(
            pack.render_feature_modules(),
            "\n#[cfg(feature = \"validation-probes\")]\n#[doc(hidden)]\npub mod event_status_validation;\n"
        );
    }

    #[test]
    fn sidecar_modules_are_reproducible_without_a_feature_gate() {
        let pack: PacApiPack = toml_edit::de::from_str(
            r#"schema = 5

[[sidecar-modules]]
name = "interrupt_route_observation"
"#,
        )
        .unwrap();

        assert_eq!(
            pack.render_sidecar_modules(),
            "\n#[doc(hidden)]\npub mod interrupt_route_observation;\n"
        );
    }

    #[test]
    fn interrupt_snapshot_exposes_status_fields_without_public_construction() {
        let pack: PacApiPack = toml_edit::de::from_str(
            r#"schema = 5

[[interrupt-snapshots]]
name = "radio_interrupt"
peripheral = "RADIO"
status-register = "STATUS"
clear-register = "CLEAR"
sources = ["PUBLIC_IRQ"]
"#,
        )
        .unwrap();
        let svd = r#"<?xml version="1.0" encoding="UTF-8"?>
<device schemaVersion="1.3" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
  <name>FIXTURE</name><version>1</version><description>interrupt snapshot fixture</description>
  <addressUnitBits>8</addressUnitBits><width>32</width>
  <peripherals><peripheral>
    <name>RADIO</name><description>radio</description><baseAddress>0x40000000</baseAddress>
    <registers>
      <register><name>STATUS</name><description>status</description><addressOffset>0</addressOffset><size>32</size><access>read-only</access>
        <fields>
          <field><name>READY</name><description>ready</description><bitOffset>3</bitOffset><bitWidth>1</bitWidth></field>
          <field><name>OPAQUE_CAUSES</name><description>opaque causes</description><bitOffset>8</bitOffset><bitWidth>6</bitWidth></field>
        </fields>
      </register>
      <register><name>CLEAR</name><description>clear</description><addressOffset>4</addressOffset><size>32</size><access>write-only</access><modifiedWriteValues>oneToClear</modifiedWriteValues>
        <fields><field><name>EVENTS</name><description>events</description><bitOffset>0</bitOffset><bitWidth>32</bitWidth></field></fields>
      </register>
    </registers>
  </peripheral></peripherals>
</device>
"#;

        let source = pack.render_rust(svd).unwrap();
        assert!(source.contains("pub const fn ready(&self) -> bool"));
        assert!(source.contains("pub const fn opaque_causes(&self) -> u8"));
        assert!(source.contains("pub const fn is_empty(&self) -> bool"));
        assert!(!source.contains("pub const fn from_bits"));
    }

    #[test]
    fn w1c_register_snapshot_renders_an_affine_masked_transaction() {
        let pack: PacApiPack = toml_edit::de::from_str(
            r#"schema = 5

[[w1c-register-snapshots]]
name = "event_status"
peripheral = "RADIO"
register = "EVENT_STATUS"
sources = ["PUBLIC_EVENT_STATUS_W1C"]
"#,
        )
        .unwrap();
        let svd = r#"<?xml version="1.0" encoding="UTF-8"?>
<device schemaVersion="1.3" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
  <name>FIXTURE</name>
  <version>1</version>
  <description>W1C snapshot fixture</description>
  <addressUnitBits>8</addressUnitBits>
  <width>32</width>
  <peripherals>
    <peripheral>
      <name>RADIO</name>
      <description>radio</description>
      <baseAddress>0x40000000</baseAddress>
      <registers>
        <register>
          <name>EVENT_STATUS</name>
          <description>event status W1C field</description>
          <addressOffset>0</addressOffset>
          <size>32</size>
          <access>read-write</access>
          <modifiedWriteValues>oneToClear</modifiedWriteValues>
          <fields>
            <field><name>READY</name><description>ready</description><bitOffset>0</bitOffset><bitWidth>1</bitWidth></field>
            <field><name>CAUSES</name><description>causes</description><bitOffset>4</bitOffset><bitWidth>3</bitWidth></field>
          </fields>
        </register>
      </registers>
    </peripheral>
  </peripherals>
</device>
"#;

        let source = pack.render_rust(svd).unwrap();
        assert!(source.contains("pub mod w1c_register_snapshot"));
        assert!(source.contains("pub fn sample_event_status(registers: &crate::Radio)"));
        assert!(!source.contains("#[cfg(feature"));
        assert!(!source.contains("core::ptr::write_volatile"));
        assert!(source.contains("pub struct EventStatusSnapshot(u32)"));
        assert!(!source.contains("pub const fn bits(&self)"));
        assert!(source.contains("pub fn acknowledge_event_status("));
        assert!(source.contains("snapshot: EventStatusSnapshot"));
        assert!(source.contains("writer.bits(snapshot.0)"));
        assert!(!source.contains("image: u32"));
        assert!(!source.contains("impl Clone for EventStatusSnapshot"));
        assert!(!source.contains("impl Copy for EventStatusSnapshot"));
    }

    #[test]
    fn masked_image_omits_a_zero_identity_term() {
        assert_eq!(
            masked_image_expression(0xf000_0000, 0x0fff_ffff, 0),
            "(reader.bits() & 0xf0000000) | (input & 0x0fffffff)"
        );
        assert_eq!(
            masked_image_expression(0xffff_0000, 0x0000_fff0, 0x0000_000f),
            "(reader.bits() & 0xffff0000) | (input & 0x0000fff0) | 0x0000000f"
        );
    }

    #[test]
    fn wide_typed_hardware_transaction_explains_its_argument_shape() {
        assert!(too_many_arguments_attribute(6, false).is_empty());
        assert!(too_many_arguments_attribute(5, true).is_empty());
        assert!(!too_many_arguments_attribute(7, false).is_empty());
        assert!(!too_many_arguments_attribute(6, true).is_empty());
    }

    #[test]
    fn facade_flags_have_no_public_integer_constructor() {
        let pack: PacApiPack = toml_edit::de::from_str(
            r#"schema = 5

[[flag-domains]]
name = "InterruptMask"
description = "Reviewed writable interrupt bits."

[[flag-domains.values]]
name = "RX_READY"
value = 8
description = "Enable receive-ready."
sources = ["VENDOR_IRQ"]

[[enum-domains]]
name = "RadioMode"
description = "Reviewed radio mode."

[[enum-domains.values]]
name = "Receive"
value = 1
description = "Receive mode."
sources = ["VENDOR_MODE"]

[[bounded-domains]]
name = "QueueIndex"
description = "Reviewed queue index."
min = 0
max = 3
sources = ["VENDOR_QUEUE"]

[[opaque-domains]]
name = "CalibrationWord"
description = "Opaque calibration word for one register."
peripheral = "RADIO"
register = "CALIBRATION"
sources = ["VENDOR_CALIBRATION"]

[[full-register-writes]]
name = "write_interrupt_mask"
peripheral = "RADIO"
register = "ENABLE"
field = "EVENTS"
domain = "InterruptMask"
exposure = "facade"
sources = ["VENDOR_IRQ"]

[[register-image-writes]]
name = "write_calibration"
peripheral = "RADIO"
register = "CALIBRATION"
domain = "CalibrationWord"
exposure = "facade"
sources = ["VENDOR_CALIBRATION"]

[[indexed-bit-set-modifies]]
name = "request_receive"
peripheral = "RADIO"
register = "REQUESTS"
field = "REQUEST"
domain = "RadioMode"
exposure = "facade"
sources = ["VENDOR_MODE"]
"#,
        )
        .unwrap();
        let source = pack.render_facade_rust().unwrap();
        assert!(source.contains("pub struct InterruptMask(u32);"));
        assert!(source.contains("pub const RX_READY: Self = Self(0x00000008);"));
        assert!(source.contains("pub enum RadioMode"));
        assert!(source.contains("pub const MAX: u32 = 0x00000003;"));
        assert!(source.contains("if value <= 0x00000003"));
        assert!(!source.contains("value >= Self::MIN"));
        assert!(source.contains("pub struct CalibrationWord(u32);"));
        assert!(source.contains("value: InterruptMask"));
        assert!(source.contains("full_register_write::write_interrupt_mask"));
        assert!(source.contains("value: CalibrationWord"));
        assert!(source.contains("register_image_write::write_calibration"));
        assert!(source.contains("index: RadioMode"));
        assert!(
            source.contains("indexed_bit_set_modify::request_receive(registers, index.bits())")
        );
        assert!(!source.contains("from_bits"));
        assert!(!source.contains("impl InterruptMask {\n    pub fn new"));
    }

    #[test]
    fn raw_only_operations_skip_facade_bridges_but_keep_generated_leaves() {
        let pack: PacApiPack = toml_edit::de::from_str(
            r#"schema = 5

[[opaque-domains]]
name = "CommandWord"
description = "Complete command word."
peripheral = "RADIO"
register = "COMMAND"
sources = ["PUBLIC_LL"]

[[opaque-domains]]
name = "StatusWord"
description = "Complete status word."
peripheral = "RADIO"
register = "STATUS"
sources = ["PUBLIC_LL"]

[[opaque-domains]]
name = "ControlWord"
description = "Complete control image."
peripheral = "RADIO"
register = "CONTROL"
sources = ["PUBLIC_LL"]

[[opaque-domains]]
name = "MaskedBits"
description = "Reviewed caller-controlled masked bits."
peripheral = "RADIO"
register = "MASKED"
sources = ["PUBLIC_LL"]

[[full-register-writes]]
name = "publish_command"
peripheral = "RADIO"
register = "COMMAND"
field = "WORD"
domain = "CommandWord"
exposure = "raw-only"
sources = ["PUBLIC_LL"]

[[full-register-reads]]
name = "observe_status"
peripheral = "RADIO"
register = "STATUS"
field = "WORD"
domain = "StatusWord"
exposure = "raw-only"
sources = ["PUBLIC_LL"]

[[register-image-writes]]
name = "publish_control"
peripheral = "RADIO"
register = "CONTROL"
domain = "ControlWord"
exposure = "raw-only"
sources = ["PUBLIC_LL"]

[[masked-register-modifies]]
name = "publish_masked_bits"
peripheral = "RADIO"
register = "MASKED"
domain = "MaskedBits"
preserve-mask = 0xffff0000
input-mask = 0x0000ffff
set-mask = 0
exposure = "raw-only"
sources = ["PUBLIC_LL"]
"#,
        )
        .unwrap();
        let svd = r#"<?xml version="1.0" encoding="UTF-8"?>
<device schemaVersion="1.3" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
  <name>FIXTURE</name>
  <version>1</version>
  <description>full-word fixture</description>
  <addressUnitBits>8</addressUnitBits>
  <width>32</width>
  <peripherals>
    <peripheral>
      <name>RADIO</name>
      <description>radio</description>
      <baseAddress>0x40000000</baseAddress>
      <registers>
        <register>
          <name>COMMAND</name><description>command</description><addressOffset>0</addressOffset>
          <size>32</size><access>write-only</access>
          <fields><field><name>WORD</name><description>word</description><bitOffset>0</bitOffset><bitWidth>32</bitWidth><writeConstraint><range><minimum>0</minimum><maximum>4294967295</maximum></range></writeConstraint></field></fields>
        </register>
        <register>
          <name>STATUS</name><description>status</description><addressOffset>4</addressOffset>
          <size>32</size><access>read-only</access>
          <fields><field><name>WORD</name><description>word</description><bitOffset>0</bitOffset><bitWidth>32</bitWidth></field></fields>
        </register>
        <register>
          <name>CONTROL</name><description>control</description><addressOffset>8</addressOffset>
          <size>32</size><access>read-write</access>
          <fields><field><name>WORD</name><description>word</description><bitOffset>0</bitOffset><bitWidth>32</bitWidth></field></fields>
        </register>
        <register>
          <name>MASKED</name><description>masked control</description><addressOffset>12</addressOffset>
          <size>32</size><access>read-write</access>
          <fields><field><name>WORD</name><description>word</description><bitOffset>0</bitOffset><bitWidth>32</bitWidth></field></fields>
        </register>
      </registers>
    </peripheral>
  </peripherals>
</device>
"#;

        let facade = pack.render_facade_rust().unwrap();
        assert!(facade.contains("pub struct CommandWord(u32);"));
        assert!(facade.contains("pub struct StatusWord(u32);"));
        assert!(!facade.contains("fn publish_command"));
        assert!(!facade.contains("fn observe_status"));
        assert!(!facade.contains("fn publish_control"));
        assert!(!facade.contains("fn publish_masked_bits"));

        let raw = pack.render_rust(svd).unwrap();
        assert!(raw.contains("pub mod full_register_write"));
        assert!(raw.contains("pub fn publish_command"));
        assert!(raw.contains("pub mod full_register_read"));
        assert!(raw.contains("pub fn observe_status"));
        assert!(raw.contains("registers.status().read().word().bits()"));
        assert!(raw.contains("pub fn publish_control"));
        assert!(raw.contains("pub fn publish_masked_bits"));
    }
}
