[package]
name = "open-esp-radio-esp32s31-wifi-mac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allocation-free source-owned ESP32-S31 Wi-Fi MAC primitives"

[features]
default = []
large-rx-pool-48 = []
rx-ba-window-8 = []
validation-raw-dma = ["open-esp-radio-esp32s31-wifi-dma/validation-raw-dma"]

[dependencies]
open-esp-radio-dma = { path = "../../../../common/dma" }
open-esp-radio-esp32s31-pac = { path = "../../pac" }
open-esp-radio-esp32s31-wifi-dma = { path = "../dma" }
open-esp-radio-ieee80211 = { path = "../../../../wifi/ieee80211" }
open-esp-radio-wifi-softmac = { path = "../../../../wifi/softmac" }
pin-project = "1.1.13"

[dev-dependencies]
open-esp-radio-esp32s31-pac = { path = "../../pac", features = ["test-register-catalog"] }

[lints]
workspace = true
