[package]
name = "open-esp-radio-mac-esp32s31"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Allocation-free source-owned ESP32-S31 Wi-Fi MAC primitives"

[dependencies]
open-esp-radio-ieee80211 = { path = "../open-esp-radio-ieee80211" }
open-esp-radio-pac-esp32s31 = { path = "../open-esp-radio-pac-esp32s31" }

[lints]
workspace = true
