[package]
name = "open-esp-radio-esp32s31-wifi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Role-neutral ESP32-S31 Wi-Fi device composition"

[dependencies]
open-esp-radio-esp32s31-hal = { path = "../hal" }
open-esp-radio-esp32s31-phy = { path = "../phy" }
open-esp-radio-esp32s31-wifi-mac = { path = "mac" }
open-esp-radio-ieee80211 = { path = "../../../wifi/ieee80211" }
open-esp-radio-wifi-softmac = { path = "../../../wifi/softmac" }

[lints]
workspace = true
