[package]
name = "open-esp-radio-esp32s31-access-point"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
open-esp-radio-wifi-embassy = { path = "../../driver/adapters/embassy/ieee80211" }
oer-esp32s31-runtime = { path = "../../platform/esp32s31/runtime", features = ["psram-task-stack"] }
edge-dhcp = { version = "0.8.0", default-features = false }
embassy-net = { git = "https://github.com/ermacv/embassy.git", rev = "317fb69357779a844a502fc171518395529c6394", features = ["medium-ethernet", "proto-ipv4", "tcp", "udp"] }
embassy-time = "0.5.1"
static_cell = "2.1.1"

[target.'cfg(target_arch = "riscv32")'.dependencies]
embassy-executor = { version = "0.10.0", default-features = false }
embassy-futures = "0.1.2"
esp-backtrace = { git = "https://github.com/ermacv/esp-hal", rev = "bee3369c35dfc10048b1d524150d99869f8a4352", default-features = false, features = ["esp32s31", "panic-handler", "println"] }
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "bee3369c35dfc10048b1d524150d99869f8a4352", default-features = false, features = ["esp32s31", "rt", "unstable"] }
esp-println = { git = "https://github.com/ermacv/esp-hal", rev = "bee3369c35dfc10048b1d524150d99869f8a4352", default-features = false, features = ["auto", "esp32s31", "log-04"] }
open-esp-radio = { path = "../../driver/radio", default-features = false, features = ["wifi"] }
open-esp-radio-esp32s31-embassy-runtime = { path = "../../driver/adapters/embassy/esp32s31/runtime", features = ["esp32s31"] }
open-esp-radio-esp32s31-phy = { path = "../../driver/chips/esp32s31/phy" }
open-esp-radio-esp32s31-wifi-esp-hal = { path = "../../driver/adapters/esp-hal/esp32s31/ieee80211", features = ["esp32s31"] }
open-esp-radio-esp32s31-embassy-wifi = { path = "../../driver/integration/esp32s31/embassy/ieee80211" }

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
opt-level = 3
panic = "abort"
strip = false

[patch."https://github.com/esp-rs/esp-pacs"]
esp32s31 = { git = "https://github.com/ermacv/esp-pacs", rev = "507d14dbccfc26128b929b044d76f09cf2d1d2f6" }

[patch."https://github.com/ermacv/embassy.git"]
embassy-futures = { version = "0.1.2", registry = "crates-io" }
embassy-sync = { version = "0.8.0", registry = "crates-io" }
embassy-time = { version = "0.5.1", registry = "crates-io" }

[workspace]
resolver = "3"

[build-dependencies]
oer-firmware = { path = "../../tools/firmware", default-features = false }
