[package]
name = "open-esp-radio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Application facade for the source-only Rust ESP radio stack"
readme = "README.md"

[features]
default = ["esp32s31-wifi"]
wifi = [
    "dep:open-esp-radio-ieee80211",
    "dep:open-esp-radio-wifi-softmac",
    "dep:open-esp-radio-wifi-sta",
    "dep:open-esp-radio-wpa2",
]
adapter-embassy-net = ["dep:open-esp-radio-embassy-net"]
adapter-embassy-wifi = ["wifi", "dep:open-esp-radio-wifi-embassy"]
esp32s31 = [
    "dep:open-esp-radio-esp32s31-hal",
    "dep:open-esp-radio-esp32s31-pac",
    "dep:open-esp-radio-esp32s31-registers",
    "dep:open-esp-radio-esp32s31-phy",
]
esp32s31-wifi = [
    "esp32s31",
    "wifi",
    "dep:open-esp-radio-esp32s31-wifi",
    "dep:open-esp-radio-esp32s31-wifi-dma",
    "dep:open-esp-radio-esp32s31-wifi-mac",
    "dep:open-esp-radio-esp32s31-wifi-sta",
]
esp32s31-wifi-embassy = [
    "esp32s31-wifi",
    "adapter-embassy-net",
    "adapter-embassy-wifi",
    "dep:open-esp-radio-esp32s31-wifi-embassy",
]
validation-raw-dma = [
    "esp32s31-wifi",
    "open-esp-radio-esp32s31-wifi-mac/validation-raw-dma",
]

[dependencies]
open-esp-radio-embassy-net = { path = "../adapters/embassy-net", optional = true }
open-esp-radio-esp32s31-hal = { path = "../chips/esp32s31/hal", optional = true }
open-esp-radio-esp32s31-pac = { path = "../chips/esp32s31/pac", optional = true }
open-esp-radio-esp32s31-wifi = { path = "../chips/esp32s31/wifi", optional = true }
open-esp-radio-esp32s31-wifi-dma = { path = "../chips/esp32s31/wifi/dma", optional = true }
open-esp-radio-esp32s31-wifi-mac = { path = "../chips/esp32s31/wifi/mac", optional = true }
open-esp-radio-esp32s31-wifi-sta = { path = "../chips/esp32s31/wifi/sta", optional = true }
open-esp-radio-esp32s31-wifi-embassy = { path = "../adapters/embassy/esp32s31-wifi", optional = true }
open-esp-radio-esp32s31-registers = { path = "../chips/esp32s31/registers", optional = true }
open-esp-radio-esp32s31-phy = { path = "../chips/esp32s31/phy", optional = true }
open-esp-radio-ieee80211 = { path = "../wifi/ieee80211", optional = true }
open-esp-radio-wifi-softmac = { path = "../wifi/softmac", optional = true }
open-esp-radio-wifi-sta = { path = "../wifi/sta", optional = true }
open-esp-radio-wpa2 = { path = "../wifi/wpa2", optional = true }
open-esp-radio-wifi-embassy = { path = "../adapters/embassy/wifi", optional = true }

[lints]
workspace = true
