[package]
name = "open-esp-radio-wifi-lmac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Executor-independent Wi-Fi HMAC/LMAC service contract"

[dependencies]
open-esp-radio-ieee80211 = { path = "../ieee80211" }

[lints]
workspace = true
