[package]
name = "open-esp-radio-esp32s31-platform-pac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP32-S31 SoC cache, flash and DMA services backed by esp-hal"

[features]
default = []
esp32s31 = ["dep:esp-hal"]
axi-gdma-mem2mem = ["esp32s31", "dep:atomic-waker"]
psram-dma-diagnostic = ["axi-gdma-mem2mem"]

[dependencies]
atomic-waker = { version = "1.1.2", optional = true }
critical-section = "1.2.0"
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "81cd5c341f71f9d070b5d2b115d3ab2c7595a4df", default-features = false, features = ["esp32s31", "unstable"], optional = true }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }

[lints]
workspace = true
