[package]
name = "open-esp-radio-esp32s31-bluetooth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP32-S31 Bluetooth controller hardware boundary"

[features]
validation-probes = [
    "open-esp-radio-esp32s31-pac/validation-probes",
    "open-esp-radio-esp32s31-phy/validation-probes",
]

[dependencies]
critical-section = "1.2.0"
embassy-sync = "0.8.0"
open-esp-radio-bluetooth-hci = { path = "../../../bluetooth/hci" }
open-esp-radio-bluetooth-ll = { path = "../../../bluetooth/ll" }
open-esp-radio-esp32s31-hal = { path = "../hal" }
open-esp-radio-esp32s31-bluetooth-memory = { path = "memory" }
open-esp-radio-esp32s31-pac = { path = "../pac" }
open-esp-radio-esp32s31-phy = { path = "../phy" }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
embassy-futures = "0.1.2"
open-esp-radio-esp32s31-pac = { path = "../pac", features = ["validation-probes"] }

[lints]
workspace = true
