[package]
name = "oer-esp32s31-example-station"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
oer-espressif-staged-runtime = { path = "../../../platform/espressif/staged-runtime", features = ["esp32s31", "two-harts"] }
oer-esp32s31-platform-board = { path = "../../../platform/esp32s31/board", features = ["stage-two"] }
embassy-executor = { version = "0.10.0", default-features = false }
embassy-futures = "0.1.2"
embassy-net-owned = { package = "embassy-net", git = "https://github.com/ermacv/embassy.git", rev = "4868fd9acfd4191173cd6531b537d6009d3ae5d0", features = ["dhcpv4", "icmp-ping-reply", "ipv4-fragmentation", "ipv4-reassembly", "medium-ethernet", "udp"], optional = true }
esp-hal = { git = "https://github.com/ermacv/esp-hal", rev = "4fd4ba9b78aa9f96e54115c3d784491c1e12df02", default-features = false, features = ["esp32s31", "static-interrupts", "rt", "unstable"] }
esp-println = { git = "https://github.com/ermacv/esp-hal", rev = "4fd4ba9b78aa9f96e54115c3d784491c1e12df02", default-features = false, features = ["auto", "esp32s31", "log-04"] }
oer = { package = "open-esp-radio", path = "../../../crates/oer", default-features = false, features = ["wifi"] }
oer-espressif-executor-embassy = { path = "../../../crates/adapters/embassy/espressif/executor", features = ["esp32s31"] }
static_cell = "2.1.1"

[features]
default = ["owned-network"]
owned-network = [
    "dep:embassy-net-owned",
    "oer/owned-xarxa",
]

[build-dependencies]
oer-esp32s31-platform-layout = { path = "../../../platform/esp32s31/layout", features = ["build"] }

[package.metadata.open-radio]
layer = "application"
platform = "chip"
chip = "esp32s31"

[lints]
workspace = true
