[package]
name = "open-esp-radio-esp32s31-phy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allocation-free Rust ESP32-S31 PHY state machines"

[features]
default = []
validation-probes = []

[dependencies]
open-esp-radio-esp32s31-hal = { path = "../hal" }

[lints]
workspace = true
