[package]
name = "open-esp-radio-esp32s31-wifi-mac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allocation-free source-owned ESP32-S31 Wi-Fi MAC primitives"

[features]
default = []
large-rx-pool-48 = []
rx-ba-window-8 = []
task-poll-telemetry = ["dep:riscv"]
validation-raw-dma = ["open-esp-radio-esp32s31-wifi-dma/validation-raw-dma"]
validation-probes = ["open-esp-radio-esp32s31-hal/validation-probes"]

[dependencies]
open-esp-radio-dma = { path = "../../../../memory" }
open-esp-radio-esp32s31-hal = { path = "../../hal" }
open-esp-radio-esp32s31-wifi-dma = { path = "../dma" }
open-esp-radio-ieee80211 = { path = "../../../../ieee80211/mac" }
open-esp-radio-wifi-softmac = { path = "../../../../ieee80211/softmac" }
pin-project = "1.1.13"
subtle = { version = "2.6.1", default-features = false }
zeroize = { version = "1.9.0", default-features = false }

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = { version = "0.15", optional = true }

[lints]
workspace = true
